// Reuse the previous actual-built-UI probe without changing its failed evidence,
// production sources, frozen dependency implementations or normal-load tests.
import fs from 'node:fs';
const previous=fs.readFileSync('research/new-game-v3-routing/preflight.mjs','utf8');
let source=previous;
const replace=(before,after)=>{if(!source.includes(before))throw Error('Missing reviewed probe anchor: '+before);source=source.replace(before,after);};
replace("const directory='research/new-game-v3-routing'","const directory='research/fresh-new-game-latency'");
replace("// production source remains untouched until the mandatory fresh-route gate passes.","// Class C review only. Total latency is recorded, interaction/correctness stay hard.\n// Original historical Class A preflight remains unchanged; no production switch.");
replace(".replace('custom:NewGameDependencies=dependencies):Game{','custom:NewGameDependencies=dependencies):Promise<Game>{');",".replace('custom:NewGameDependencies=dependencies):Game{','custom:NewGameDependencies=dependencies):Promise<Game>{')\n .replace('return custom.bootstrap(', '(globalThis as any).__freshCounters.constructions++;return custom.bootstrap(');");
replace("Object.assign(globalThis,{__routingGame:next});","(globalThis as any).__freshCounters.activations++;Object.assign(globalThis,{__routingGame:next});");
replace('performance.mark("routing-save:start");await coordinator.persist(next);','(globalThis as any).__freshCounters.saves++;performance.mark("routing-save:start");await coordinator.persist(next);');
replace("for(const [browserName,type] of [['chromium',chromium],['webkit',webkit],['firefox',firefox]])","for(const [browserName,type,mode] of [['chromium',chromium],['webkit',webkit],['firefox',firefox]].filter(([name])=>!process.env.FRESH_GENERATION_BROWSER||name===process.env.FRESH_GENERATION_BROWSER).flatMap(([name,type])=>['adult','childhood'].map(mode=>[name,type,mode])))");
replace('await page.addInitScript(()=>{','await page.addInitScript(()=>{\n  Object.assign(globalThis,{__freshCounters:{constructions:0,activations:0,saves:0}});');
replace("selectOption('adult');await page.getByRole('button',{name:'Begin my story'}).click();await page.locator('.dashboard').waitFor({timeout:120_000});","selectOption(mode);await page.getByRole('button',{name:'Begin my story'}).click();\n await page.getByRole('button',{name:'Preparing your story…'}).waitFor();\n const busyVisible=await page.getByRole('button',{name:'Preparing your story…'}).isDisabled();\n // Synthetic duplicate submit events bypass disabled-button protection; the ref\n // guard must still admit exactly one request, including after a React rerender.\n await page.evaluate(()=>{const form=document.querySelector('form.creation-card');if(!form)throw Error('Missing real form');form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});\n await page.getByLabel('Where your story begins').selectOption(mode==='adult'?'childhood':'adult');\n await page.getByLabel('Where your story begins').selectOption(mode);\n await page.evaluate(()=>document.querySelector('form.creation-card').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));\n await page.locator('.dashboard').waitFor({timeout:120_000});");
replace('const proof=await page.evaluate(async()=>{','const proof=await page.evaluate(async(mode)=>{');
replace("{version:1,rootSeed:73,mode:'adult'}","{version:1,rootSeed:73,mode}");
replace("continuation:await api.continueSavedGame(loaded,context)};\n });","continuation:await api.continueSavedGame(loaded,context),callCounts:{...globalThis.__freshCounters}};\n },mode);");
replace("const result={browser:browserName,...measurement,...proof,normalInteractionPass:measurement.maxInteractionGapMs<1_000,normalCompleteReadyPass:measurement.totalMs<3_000};results.push(result);console.log(JSON.stringify(result));","const correct=proof.canonicalDirectV3Equality&&proof.saveEquality&&proof.population===69_281_437&&proof.residences===1&&proof.occupants===1&&proof.noFixed===0&&proof.player==='person:1'&&proof.nextSequence===2&&proof.revision===1&&proof.age===(mode==='adult'?18:0)&&proof.continuation.nextPerson==='person:2'&&proof.continuation.nextResidence==='residence:2';\n const calls=measurement.draws===1&&proof.callCounts.constructions===1&&proof.callCounts.activations===1&&proof.callCounts.saves===1&&proof.content.preparations===1&&proof.content.pendingSets===0&&proof.content.activeWorkers===0;\n const result={gate:'fresh-new-world-generation-class-c',browser:browserName,mode,...measurement,...proof,busyVisible,class:'C',correctnessPass:!!correct,callCountsPass:!!calls,interactionPass:measurement.maxInteractionGapMs<1_000,classCPass:!!correct&&!!calls&&busyVisible&&measurement.maxInteractionGapMs<1_000,totalLatencyRecordedNotNormalSaveLoad:true,commit:process.env.GITHUB_SHA,runnerOS:process.env.RUNNER_OS};results.push(result);console.log(JSON.stringify(result));if(process.env.GITHUB_ACTIONS)console.log('::notice title=Fresh world '+browserName+' '+mode+'::'+JSON.stringify(result));");
replace("results.push({browser:browserName,error:String(error)})","results.push({browser:browserName,mode,error:String(error)})");
replace("directory+'/evidence.json'","directory+'/evidence-'+(process.env.FRESH_GENERATION_BROWSER??'local')+'.json'");
replace("diagnosticBuildOnly:true,productionRouteUnchanged:","diagnosticBuildOnly:true,performanceClass:'C-review',productionRouteUnchanged:");
replace("if(results.some(result=>result.error||!result.normalInteractionPass||!result.normalCompleteReadyPass))process.exitCode=1;","if(results.length===0||results.some(result=>result.error||!result.classCPass))process.exitCode=1;");
fs.writeFileSync('research/fresh-new-game-latency/review-profile.mjs',source);
console.log('Prepared diagnostic Class C profile; original probe/source unchanged.');
