import {expect,test} from '@playwright/test';

test('round-trips a one-byte ArrayBuffer after IndexedDB close and reopen',async({page},testInfo)=>{await page.goto('/');const result=await page.evaluate(async browserName=>{const name=`turning-pages-arraybuffer-probe-${browserName}`;await new Promise<void>((resolve,reject)=>{const remove=indexedDB.deleteDatabase(name);remove.onsuccess=()=>resolve();remove.onerror=()=>reject(remove.error);});await new Promise<void>((resolve,reject)=>{const open=indexedDB.open(name,1);open.onupgradeneeded=()=>open.result.createObjectStore('records');open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,tx=db.transaction('records','readwrite'),request=tx.objectStore('records').put(new Uint8Array([173]).buffer,'one');request.onerror=()=>reject(request.error);tx.onabort=()=>reject(tx.error??Error('ArrayBuffer transaction aborted.'));tx.oncomplete=()=>{db.close();resolve();};};});const byte=await new Promise<number>((resolve,reject)=>{const open=indexedDB.open(name,1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,request=db.transaction('records','readonly').objectStore('records').get('one');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const payload=request.result;db.close();if(!(payload instanceof ArrayBuffer)||payload.byteLength!==1){reject(Error('Stored payload was not an exact one-byte ArrayBuffer.'));return;}resolve(new Uint8Array(payload)[0]);};};});await new Promise<void>((resolve,reject)=>{const remove=indexedDB.deleteDatabase(name);remove.onsuccess=()=>resolve();remove.onerror=()=>reject(remove.error);});return byte;},testInfo.project.name);expect(result).toBe(173);});

test('round-trips the exact v3 candidate through a real IndexedDB reopen',async({page},testInfo)=>{
  await page.goto('/');
  const result=await page.evaluate(async browserName=>{
    const [{GamePersistence},{createV3PersistenceProbeGame,continueV3PersistenceProbe,V3_PERSISTENCE_IDENTITY},{serializeGame},{deletePersistenceDatabase},{PRIMARY_SLOT,PREVIOUS_SLOT},{sha256Bytes,verifyRecord}]=await Promise.all([
      import('/src/persistence/service.ts'),import('/src/persistence/testing/v3Gate.ts'),import('/src/engine/save.ts'),import('/src/persistence/indexedDb.ts'),import('/src/persistence/record.ts'),import('/src/persistence/payload.ts'),
    ]);
    let stage='delete';try{const name=`turning-pages-browser-${browserName}`;await deletePersistenceDatabase(indexedDB,name).catch(()=>{});localStorage.removeItem('turning-pages:v1');localStorage.removeItem('turning-pages:indexeddb-authority-v1');
    const game=createV3PersistenceProbeGame(),canonicalStart=performance.now(),canonical=serializeGame(game);if(!canonical.ok)throw Error(canonical.error);const canonicalMs=performance.now()-canonicalStart,encodingStart=performance.now(),canonicalBytesValue=new TextEncoder().encode(canonical.raw),utf8EncodingMs=performance.now()-encodingStart,hashStart=performance.now();await sha256Bytes(canonicalBytesValue);const sha256Ms=performance.now()-hashStart;
    stage='first-open';const first=await GamePersistence.open(localStorage,indexedDB,name),writeStart=performance.now();stage='first-save';await first.save(game,null);const writeMs=performance.now()-writeStart;first.close();
    stage='reopen';const readStart=performance.now(),second=await GamePersistence.open(localStorage,indexedDB,name),started=await second.initialize(),loadMs=performance.now()-readStart;if(!started.game)throw Error(started.error??'No loaded Game.');stage='semantic-equality';const loadedCanonical=serializeGame(started.game);if(!loadedCanonical.ok||loadedCanonical.raw!==canonical.raw)throw Error('Reopened canonical Game differs from the saved Game.');stage='continue';const continued=continueV3PersistenceProbe(started.game);stage='second-save';await second.save(started.game,started.revision);
    const storedReadStart=performance.now(),stored=await second.repository.getRecord(PRIMARY_SLOT),indexedDbReadMs=performance.now()-storedReadStart,storedPayload=(stored as {payload:ArrayBuffer;sha256:string}).payload,checksumStart=performance.now(),storedHash=await sha256Bytes(new Uint8Array(storedPayload)),checksumMs=performance.now()-checksumStart;if(storedHash!==(stored as {sha256:string}).sha256)throw Error('Measured checksum mismatch.');const decodeStart=performance.now();new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(storedPayload));const decodeMs=performance.now()-decodeStart,primary=await verifyRecord(stored,PRIMARY_SLOT),previous=await verifyRecord(await second.repository.getRecord(PREVIOUS_SLOT),PREVIOUS_SLOT),estimate=await navigator.storage?.estimate?.(),persistRequest=await navigator.storage?.persist?.(),persisted=await navigator.storage?.persisted?.();second.close();await deletePersistenceDatabase(indexedDB,name);
    return {identity:V3_PERSISTENCE_IDENTITY,canonicalBytes:canonicalBytesValue.byteLength,primaryBytes:primary.record.byteLength,previousBytes:previous.record.byteLength,primaryRevision:primary.record.revision,previousRevision:previous.record.revision,representedPopulation:V3_PERSISTENCE_IDENTITY.total,continuationPersonId:continued.persons[0]?.id,canonicalMs,utf8EncodingMs,sha256Ms,writeMs,indexedDbReadMs,checksumMs,decodeMs,completeValidatedLoadMs:loadMs,estimate,persistRequest:typeof persistRequest==='boolean'?persistRequest:null,persisted:typeof persisted==='boolean'?persisted:null};}catch(error){throw Error(`${stage}: ${error instanceof Error?`${error.name}: ${error.message}`:String(error)}`);}
  },testInfo.project.name);
  expect(result.identity.id).toBe('uk.population.mid-2024.v3');expect(result.identity.fingerprint).toBe('fnv1a64-v1:2894f4c1b1fdd274');expect(result.identity.artifactSha256).toBe('c4b13eb67a1b7e231da1250b27f8e596c6535e7f260013d8a8638bda2b81188a');expect(result.canonicalBytes).toBe(9_595_304);expect(result.primaryBytes).toBe(result.canonicalBytes);expect(result.previousBytes).toBe(result.canonicalBytes);expect(result.primaryRevision).toBe(2);expect(result.previousRevision).toBe(1);expect(result.representedPopulation).toBe(69_281_437);expect(result.continuationPersonId).toBe('person:2');expect(result.completeValidatedLoadMs).toBeLessThanOrEqual(3_000);testInfo.attach('measurements',{body:JSON.stringify(result,null,2),contentType:'application/json'});console.log(JSON.stringify({browser:testInfo.project.name,...result}));
});
