import {expect,test} from '@playwright/test';

test('root7 preserves nonempty Partnership and FormalUnion, exact pre-migration recovery, kinds and continuation',async({page},testInfo)=>{
 await page.goto('/research/country-start-v3/worker-browser-blank.html');
 const result=await page.evaluate(async browser=>{
  const [fixture,oldFixture,save,service,payload,unions,kinds,host]=await Promise.all([import('/src/engine/testing/relationshipUnionRootFixture.ts'),import('/src/engine/testing/kinshipRootFixture.ts'),import('/src/engine/save.ts'),import('/src/persistence/service.ts'),import('/src/persistence/payload.ts'),import('/src/engine/formalUnion/state.ts'),import('/src/engine/formalUnion/fixtures.ts'),import('/src/ui/gameContent.ts')]);
  const name='turning-pages-relationship-union-root7-'+browser,legacy={getItem:()=>null,setItem:()=>{}},historical=save.serializeGameV6(oldFixture.syntheticKinshipGame()),game=fixture.syntheticRelationshipUnionGame();if(!historical.ok||new TextEncoder().encode(historical.raw).byteLength!==4118)throw Error('Historical6 byte contract changed');
  const pending=new Set<Promise<void>>(),native=IDBDatabase.prototype.transaction;
  IDBDatabase.prototype.transaction=function(...args:Parameters<IDBDatabase['transaction']>){const tx=native.apply(this,args);if(this.name===name){const done=new Promise<void>((resolve,reject)=>{tx.addEventListener('complete',()=>resolve(),{once:true});tx.addEventListener('abort',()=>reject(tx.error),{once:true});});pending.add(done);void done.then(()=>pending.delete(done),()=>pending.delete(done));}return tx;};
  let first:InstanceType<typeof service.GamePersistence>|undefined,second:InstanceType<typeof service.GamePersistence>|undefined;
  try{
   first=await service.GamePersistence.open(legacy,indexedDB,name);await first.repository.commitSave(await payload.recordFromRaw('primary','primary',1,'canonical-game',historical.raw),null);
   const opened=await first.initialize();if(opened.game?.version!==7||opened.game.partnership.partnerships.length||opened.game.formalUnion.unions.length||opened.game.formalUnion.nextSequence!==1)throw Error('Migration inferred relationships');
   if((await payload.verifyRecord(await first.repository.getRecord('primary'),'primary')).raw!==historical.raw)throw Error('Initialization rewrote historical6');
   await first.save(opened.game,1);const slot='recovery:'+save.PRE_RELATIONSHIP_UNION_SAVE_KEY,recovery=await payload.verifyRecord(await first.repository.getRecord(slot),slot);if(recovery.raw!==historical.raw||recovery.record.sha256!==await payload.sha256Text(historical.raw))throw Error('Recovery bytes changed');
   await first.save(game,2);await Promise.all([...pending]);first.close();second=await service.GamePersistence.open(legacy,indexedDB,name);
   const started=performance.now(),reopened=await second.initialize(),loadMs=performance.now()-started,canonical=save.serializeCurrentGame(game),loaded=save.serializeCurrentGame(reopened.game);if(!canonical.ok||!loaded.ok||canonical.raw!==loaded.raw||reopened.game?.version!==7)throw Error('Nonempty root7 roundtrip failed');
   let unavailable=false;try{await host.acceptApplicationGame(reopened.game);}catch{unavailable=true;}if(!unavailable)throw Error('Missing kind/Residence content was accepted');
   await host.acceptApplicationGame(reopened.game,fixture.relationshipUnionContext(game));
   const noResidence={...reopened.game,residence:{version:1 as const,nextSequence:1,residences:[],occupants:[],noFixedAbodePersonIds:[]}};let blocked=false;try{await host.acceptApplicationGame(noResidence);}catch{blocked=true;}if(!blocked)throw Error('Empty Residence bypassed Union kinds');await host.acceptApplicationGame(noResidence,fixture.relationshipUnionContext(game));
   const ctx={people:reopened.game.people,referenceDate:reopened.game.clock!.date,kinds:kinds.fixtureKinds()},continued=unions.createFormalUnion(reopened.game.formalUnion,{personIds:['person:2','person:3'],kindId:'formal-union-kind.synthetic.pair-v1',formedOn:null},ctx);if(continued.union.id!=='formal-union:5')throw Error('Allocator continuation changed');
   await second.save({...reopened.game,formalUnion:continued.state},3);const final=await second.initialize();if(final.game?.version!==7||JSON.stringify(final.game.formalUnion)!==JSON.stringify(continued.state))throw Error('Continued contract save failed');if((await payload.verifyRecord(await second.repository.getRecord(slot),slot)).raw!==historical.raw)throw Error('Recovery overwritten');
   return {browser,root:7,partnershipPairs:game.partnership.partnerships.length,unionRecords:game.formalUnion.unions.length,terminalRecords:game.formalUnion.unions.filter(record=>record.standing.kind==='ended').length,nextUnion:continued.union.id,revision:final.revision,canonicalEquality:true,recoveryExact:true,kindResolution:true,emptyResidenceKindGuard:true,byteLength:new TextEncoder().encode(canonical.raw).byteLength,sha256:await payload.sha256Text(canonical.raw),historicalSha256:await payload.sha256Text(historical.raw),loadMs};
  }finally{await Promise.all([...pending]);first?.close();second?.close();IDBDatabase.prototype.transaction=native;await new Promise<void>((resolve,reject)=>{const deletion=indexedDB.deleteDatabase(name);deletion.onsuccess=()=>resolve();deletion.onerror=()=>reject(deletion.error);deletion.onblocked=()=>reject(Error('Root7 test connection lifecycle blocked cleanup'));});}
 },testInfo.project.name);
 expect(result).toMatchObject({root:7,partnershipPairs:1,unionRecords:4,terminalRecords:1,nextUnion:'formal-union:5',revision:4,canonicalEquality:true,recoveryExact:true,kindResolution:true,emptyResidenceKindGuard:true,byteLength:5147,sha256:'sha256:7dff13940c31d50885ec0397e5abfcedddb14e67f91bcac96dd0677fe35adc7e',historicalSha256:'sha256:903eaf5d78bc6ef1441731d3916abe35992832f0f4c17728566b7402ef929180'});
 console.log('::notice title=Relationship Union root7 persistence::'+JSON.stringify({gate:'relationship-union-root7',...result}));await testInfo.attach('relationship-union-root7',{body:JSON.stringify(result,null,2),contentType:'application/json'});
});
