import {describe,expect,it} from 'vitest';
import {createGame} from '../game';
import {compilePopulationCalibration} from '../human/calibration/compiler';
import {withCalibrationFingerprint} from '../human/calibration/package';
import {allocatePerson,type PersonInput} from '../human/person';
import {deriveCountryPopulation,populationCohortId,type PopulationCohortInput,type PopulationState,validPopulationWithPeople} from '../human/population';
import {parseGame,serializeGame} from '../save';
import {createGeographyRegistry,fingerprintGeographyPartition,fingerprintPlaceIdentity,validateGeographyPartitionPackage,validateGeographyRegistry,withGeographyPartitionFingerprint} from './package';
import {deriveGeographicPopulation,geographyAreaExists,validPopulationGeography} from './population';
import {createGeographyRuntime,validGeographicAreaReference} from './runtime';
import type {GeographyPartitionNodeV1,GeographyPartitionPackageV1,GeographyRegistryV1,PlaceIdentityV1} from './types';

const now={year:2024,month:6,day:30} as const,source={version:1 as const,id:'geography.source.synthetic-v1',producer:'Synthetic test producer',datasetId:'synthetic-geography',releaseId:'v1',title:'Synthetic geography',jurisdiction:'synthetic',referenceDate:now,classification:'authored-gameplay-abstraction' as const,methodology:'Authored synthetic hierarchy for structural tests only.',licence:'Test fixture.'};
const node=(placeId:string,parentPlaceId:string|null,populationAllocationCell=false,overrides:Partial<GeographyPartitionNodeV1>={}):GeographyPartitionNodeV1=>({placeId,displayName:placeId.split('.').at(-1)!,kindId:'geo.synthetic-area',parentPlaceId,populationAllocationCell,sourceIds:[source.id],...overrides});
const caNodes:readonly GeographyPartitionNodeV1[]=[node('place.synthetic.ca.north','place.synthetic.ca.root'),node('place.synthetic.ca.root',null,false,{displayName:'Synthetic Canada',kindId:'geo.synthetic-root'}),node('place.synthetic.ca.south','place.synthetic.ca.root',true),node('place.synthetic.ca.spare','place.synthetic.ca.root'),node('place.synthetic.ca.village','place.synthetic.ca.north',true)];
const nzNodes:readonly GeographyPartitionNodeV1[]=[node('place.synthetic.nz.cell','place.synthetic.nz.root',true),node('place.synthetic.nz.root',null,false,{kindId:'geo.synthetic-root'})];
const rawPartition=(partitionId:string,countryId:string,nodes:readonly GeographyPartitionNodeV1[],overrides:Partial<Omit<GeographyPartitionPackageV1,'fingerprint'>>={}):Omit<GeographyPartitionPackageV1,'fingerprint'>=>({version:1,partitionId,countryId,effectiveDate:now,sources:[source],nodes,limitations:['Synthetic content only.'],...overrides});
const partition=(partitionId:string,countryId:string,nodes:readonly GeographyPartitionNodeV1[],overrides:Partial<Omit<GeographyPartitionPackageV1,'fingerprint'>>={})=>withGeographyPartitionFingerprint(rawPartition(partitionId,countryId,nodes,overrides));
const caV1=()=>partition('geography.synthetic-ca-v1','ca',caNodes),caV2=()=>partition('geography.synthetic-ca-v2','ca',[node('place.synthetic.ca.north','place.synthetic.ca.root',false,{displayName:'Northern successor name',kindId:'geo.changed-classification'}),node('place.synthetic.ca.root',null,false,{kindId:'geo.synthetic-root'}),node('place.synthetic.ca.south','place.synthetic.ca.root'),node('place.synthetic.ca.spare','place.synthetic.ca.north'),node('place.synthetic.ca.village','place.synthetic.ca.south',true)]);
const nzV1=()=>partition('geography.synthetic-nz-v1','nz',nzNodes);
const identities:readonly PlaceIdentityV1[]=[...new Set([...caNodes,...nzNodes].map(item=>item.placeId))].map(placeId=>({placeId,countryId:placeId.includes('.nz.')?'nz':'ca'}));
const placeManifest=(places:readonly PlaceIdentityV1[])=>places.map(item=>({placeId:item.placeId,fingerprint:fingerprintPlaceIdentity(item)}));
const registry=():GeographyRegistryV1=>{const packages=[caV1(),caV2(),nzV1()];return createGeographyRegistry(identities,packages,packages.map(item=>({partitionId:item.partitionId,fingerprint:item.fingerprint})),placeManifest(identities));};
const personInput=(name:string,lifeStatus:'living'|'deceased'='living'):PersonInput=>({name,dateOfBirth:{year:1990,month:1,day:1},genderLabel:'Unspecified',lifeStatus,...(lifeStatus==='deceased'?{diedAt:{year:2020,month:1,day:1}}:{}),traits:[],temperament:{},aptitudes:{}});
const cohort=(countryId:string,areaId:string,count:number):PopulationCohortInput=>({countryId,areaId,birthYear:1990,generationProfileId:'human.synthetic-v1',count});

function populationFixture(){
 const game=createGame('Player','Any','ca',17);let people=game.people!;people=allocatePerson(people,personInput('Deceased','deceased')).state;people=allocatePerson(people,personInput('Foreign')).state;people=allocatePerson(people,personInput('Unassigned')).state;
 const inputs=[cohort('ca','place.synthetic.ca.south',20),cohort('ca','place.synthetic.ca.village',10),cohort('nz','place.synthetic.nz.cell',7)],cohorts=inputs.map(item=>({...item,id:populationCohortId(item)})).sort((a,b)=>a.id<b.id?-1:1),origin={kind:'explicit' as const,source:'population.synthetic-geography-v1'};
 const population:PopulationState={version:1,coverage:[{countryId:'ca',status:'complete',source:'population.synthetic-geography-v1',areaPartitionId:'geography.synthetic-ca-v1'},{countryId:'nz',status:'partial',source:'population.synthetic-geography-v1',areaPartitionId:'geography.synthetic-nz-v1'}],cohorts,memberships:[{personId:'person:1',countryId:'ca',areaId:'place.synthetic.ca.village',origin},{personId:'person:2',countryId:'ca',areaId:'place.synthetic.ca.village',origin},{personId:'person:3',countryId:'nz',areaId:'place.synthetic.nz.cell',origin},{personId:'person:4',countryId:null,areaId:null,origin}]};
 expect(validPopulationWithPeople(population,people)).toBe(true);return {game,people,population};
}

describe('country-neutral Geography Foundation v1',()=>{
 it('constructs immutable canonical packages and detects material semantic changes',()=>{const first=caV1(),reordered=withGeographyPartitionFingerprint({...rawPartition(first.partitionId,'ca',[...caNodes].reverse()),sources:[source],limitations:['Synthetic content only.']});expect(reordered).toEqual(first);expect(fingerprintGeographyPartition(first)).toBe(first.fingerprint);expect(Object.isFrozen(first)).toBe(true);expect(Object.isFrozen(first.nodes)).toBe(true);expect(partition('geography.synthetic-changed-v1','ca',caNodes.map(item=>item.placeId==='place.synthetic.ca.south'?{...item,displayName:'Changed'}:item)).fingerprint).not.toBe(first.fingerprint);});
 it('does not retain mutable nested registry aliases in canonical content or runtime indexes',()=>{const canonical=registry(),mutable=structuredClone(canonical),runtime=createGeographyRuntime(mutable);(mutable.partitions[0].nodes[0] as {displayName:string}).displayName='Caller mutation';(mutable.partitions[0].nodes[0].sourceIds as string[]).push('geography.source.caller-v1');(mutable.partitions[0].sources[0].referenceDate as {year:number}).year=1999;(mutable.placeManifest[0] as {fingerprint:string}).fingerprint='fnv1a64-v1:0000000000000000';expect(runtime.registry).toEqual(canonical);expect(runtime.resolvePlace('geography.synthetic-ca-v1','place.synthetic.ca.north')?.node.displayName).not.toBe('Caller mutation');expect(Object.isFrozen(runtime.registry)).toBe(true);expect(Object.isFrozen(runtime.registry.partitions[0].sources[0].referenceDate)).toBe(true);});
 it('keeps partition identities immutable through the registry manifest',()=>{const first=caV1(),changed=partition(first.partitionId,'ca',caNodes.map(item=>item.placeId==='place.synthetic.ca.south'?{...item,displayName:'Changed'}:item)),identityManifest=placeManifest(identities);expect(()=>createGeographyRegistry(identities,[changed],[{partitionId:first.partitionId,fingerprint:first.fingerprint}],identityManifest)).toThrow('Invalid Geography registry');expect(()=>createGeographyRegistry(identities,[first,changed],[{partitionId:first.partitionId,fingerprint:first.fingerprint},{partitionId:changed.partitionId,fingerprint:changed.fingerprint}],identityManifest)).toThrow();});
 it('separates durable identity from boundary-era name, kind, and containment',()=>{const runtime=createGeographyRuntime(registry()),old=runtime.resolvePlace('geography.synthetic-ca-v1','place.synthetic.ca.north')!,newer=runtime.resolvePlace('geography.synthetic-ca-v2','place.synthetic.ca.north')!;expect(old.identity).toEqual({placeId:'place.synthetic.ca.north',countryId:'ca'});expect(newer.identity).toBe(old.identity);expect(newer.node.displayName).not.toBe(old.node.displayName);expect(newer.node.kindId).not.toBe(old.node.kindId);expect(runtime.getParent('geography.synthetic-ca-v1','place.synthetic.ca.village')?.placeId).toBe('place.synthetic.ca.north');expect(runtime.getParent('geography.synthetic-ca-v2','place.synthetic.ca.village')?.placeId).toBe('place.synthetic.ca.south');});
 it('binds each durable Place to an immutable identity-manifest fingerprint',()=>{const canonical=registry(),reordered=createGeographyRegistry([...identities].reverse(),[nzV1(),caV2(),caV1()],[...canonical.manifest].reverse(),[...canonical.placeManifest].reverse());expect(reordered).toEqual(canonical);const changed=structuredClone(canonical);(changed.places.find(item=>item.placeId==='place.synthetic.ca.north') as {countryId:string}).countryId='nz';expect(validateGeographyRegistry(changed)).toBe(false);const tampered=structuredClone(canonical);(tampered.placeManifest[0] as {fingerprint:string}).fingerprint='fnv1a64-v1:0000000000000000';expect(validateGeographyRegistry(tampered)).toBe(false);expect(fingerprintPlaceIdentity({placeId:'place.synthetic.ca.north',countryId:'ca'})).not.toBe(fingerprintPlaceIdentity({placeId:'place.synthetic.ca.north',countryId:'nz'}));});
 it('rejects conflicting country identity and unregistered Place reuse',()=>{const pkg=caV1(),wrong=identities.map(item=>item.placeId==='place.synthetic.ca.north'?{...item,countryId:'nz'}:item),partitionManifest=[{partitionId:pkg.partitionId,fingerprint:pkg.fingerprint}];expect(()=>createGeographyRegistry(wrong,[pkg],partitionManifest,placeManifest(wrong))).toThrow();const incomplete=identities.filter(item=>item.placeId!=='place.synthetic.ca.north');expect(()=>createGeographyRegistry(incomplete,[pkg],partitionManifest,placeManifest(incomplete))).toThrow();});
 it('requires a new durable identity for a true successor Place',()=>{const merged=node('place.synthetic.ca.merged','place.synthetic.ca.root',true),pkg=partition('geography.synthetic-ca-merged-v1','ca',[node('place.synthetic.ca.root',null,false,{kindId:'geo.synthetic-root'}),merged]),partitionManifest=[{partitionId:pkg.partitionId,fingerprint:pkg.fingerprint}];expect(()=>createGeographyRegistry(identities,[pkg],partitionManifest,placeManifest(identities))).toThrow();const withSuccessor=[...identities,{placeId:merged.placeId,countryId:'ca'}];expect(createGeographyRegistry(withSuccessor,[pkg],partitionManifest,placeManifest(withSuccessor)).places).toContainEqual({placeId:merged.placeId,countryId:'ca'});});
 it('uses partition-qualified deterministic hierarchy operations',()=>{const runtime=createGeographyRuntime(registry());expect(runtime.getParent('geography.synthetic-ca-v1','place.synthetic.ca.root')).toBeNull();expect(runtime.getChildren('geography.synthetic-ca-v1','place.synthetic.ca.root').map(item=>item.placeId)).toEqual(['place.synthetic.ca.north','place.synthetic.ca.south','place.synthetic.ca.spare']);expect(runtime.getAncestors('geography.synthetic-ca-v1','place.synthetic.ca.village').map(item=>item.placeId)).toEqual(['place.synthetic.ca.north','place.synthetic.ca.root']);expect(runtime.isWithin('geography.synthetic-ca-v1','place.synthetic.ca.village','place.synthetic.ca.north')).toBe(true);expect(runtime.isWithin('geography.synthetic-ca-v2','place.synthetic.ca.village','place.synthetic.ca.north')).toBe(false);expect(runtime.isWithin('geography.synthetic-ca-v1','place.synthetic.ca.north','place.synthetic.ca.north')).toBe(false);expect(()=>runtime.getParent('geography.synthetic-ca-v1','place.synthetic.nz.cell')).toThrow('Unknown Geography');});
 it('keeps allocation status explicit and requires allocation cells to be leaves',()=>{const runtime=createGeographyRuntime(registry());expect(runtime.isPopulationAllocationCell('geography.synthetic-ca-v1','place.synthetic.ca.village')).toBe(true);expect(runtime.isPopulationAllocationCell('geography.synthetic-ca-v1','place.synthetic.ca.spare')).toBe(false);expect(()=>partition('geography.synthetic-invalid-v1','ca',caNodes.map(item=>item.placeId==='place.synthetic.ca.north'?{...item,populationAllocationCell:true}:item))).toThrow();});
 it('rejects malformed trees without recursion',()=>{const cases=[caNodes.map(item=>item.placeId==='place.synthetic.ca.village'?{...item,parentPlaceId:'place.missing'}:item),caNodes.map(item=>item.placeId==='place.synthetic.ca.north'?{...item,parentPlaceId:null}:item),caNodes.map(item=>item.placeId==='place.synthetic.ca.root'?{...item,parentPlaceId:'place.synthetic.ca.village'}:item)];for(const [index,nodes] of cases.entries())expect(()=>partition(`geography.synthetic-broken-${index}-v1`,'ca',nodes)).toThrow('Invalid Geography');});
 it('supports technically deep and large flat content with iterative traversal',()=>{const count=3000,nodes:Array<GeographyPartitionNodeV1>=[];for(let index=0;index<count;index++)nodes.push(node(`place.deep.${String(index).padStart(4,'0')}`,index===0?null:`place.deep.${String(index-1).padStart(4,'0')}`,index===count-1));const pkg=partition('geography.synthetic-deep-v1','ca',nodes),places=nodes.map(item=>({placeId:item.placeId,countryId:'ca'})),deepRegistry=createGeographyRegistry(places,[pkg],[{partitionId:pkg.partitionId,fingerprint:pkg.fingerprint}],placeManifest(places)),runtime=createGeographyRuntime(deepRegistry);expect(runtime.getAncestors(pkg.partitionId,nodes.at(-1)!.placeId)).toHaveLength(count-1);expect(runtime.isWithin(pkg.partitionId,nodes.at(-1)!.placeId,nodes[0].placeId)).toBe(true);});
 it('does not impose a low modelling cap on source descriptors',()=>{const sources=Array.from({length:1200},(_,index)=>({...source,id:`geography.source.synthetic-${String(index).padStart(4,'0')}`})),root=node('place.sources.root',null,true,{sourceIds:sources.map(item=>item.id)}),pkg=withGeographyPartitionFingerprint({...rawPartition('geography.synthetic-many-sources-v1','ca',[root]),sources});expect(pkg.sources).toHaveLength(1200);});
 it('rejects sparse, accessor-backed, hidden, symbolic, unsupported-prototype, malformed, and revoked structures predictably',()=>{const pkg=caV1(),sparse=[...pkg.nodes] as GeographyPartitionNodeV1[];delete sparse[1];expect(validateGeographyPartitionPackage({...pkg,nodes:sparse})).toBe(false);let accessed=false;const accessor={...pkg};Object.defineProperty(accessor,'countryId',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validateGeographyPartitionPackage(accessor)).toBe(false);expect(accessed).toBe(false);const hostileRegistry=structuredClone(registry());Object.defineProperty(hostileRegistry.placeManifest[0],'fingerprint',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validateGeographyRegistry(hostileRegistry)).toBe(false);expect(accessed).toBe(false);expect(validateGeographyPartitionPackage({...pkg,[Symbol('x')]:true})).toBe(false);const hidden={...pkg};Object.defineProperty(hidden,'extra',{value:true});expect(validateGeographyPartitionPackage(hidden)).toBe(false);expect(validateGeographyPartitionPackage(Object.assign(Object.create({inherited:true}),pkg))).toBe(false);expect(validateGeographyPartitionPackage({...pkg,partitionId:'not-versioned',fingerprint:'bad'})).toBe(false);const revoked=Proxy.revocable(pkg,{});revoked.revoke();expect(validateGeographyPartitionPackage(revoked.proxy)).toBe(false);});
 it('validates exact partition-qualified area references',()=>{const runtime=createGeographyRuntime(registry());expect(validGeographicAreaReference({version:1,partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.village'},runtime)).toBe(true);expect(validGeographicAreaReference({version:1,partitionId:'geography.synthetic-ca-v2',placeId:'place.synthetic.nz.cell'},runtime)).toBe(false);expect(validGeographicAreaReference({version:1,partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.village',extra:true},runtime)).toBe(false);});
 it('validates Population areas per coverage without inferring country',()=>{const {people,population}=populationFixture(),runtime=createGeographyRuntime(registry());expect(validPopulationGeography(population,people,runtime)).toBe(true);const foreignArea={...population,memberships:population.memberships.map(item=>item.personId==='person:3'?{...item,areaId:'place.synthetic.ca.village'}:item)};expect(validPopulationWithPeople(foreignArea,people)).toBe(true);expect(validPopulationGeography(foreignArea,people,runtime)).toBe(false);expect(population.memberships.at(-1)).toMatchObject({countryId:null,areaId:null});});
 it('leaves frozen unpartitioned coverage semantics unchanged',()=>{const game=createGame('Unpartitioned','Any','ca',71);expect(game.population?.coverage).toContainEqual(expect.objectContaining({countryId:'ca',areaPartitionId:null}));expect(validPopulationGeography(game.population,game.people,createGeographyRuntime(registry()))).toBe(true);});
 it('derives coverage-scoped living rollups without persisted totals',()=>{const {people,population}=populationFixture(),runtime=createGeographyRuntime(registry());expect(deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.root'})).toEqual({knownLiving:31,complete:true});expect(deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.north'})).toEqual({knownLiving:11,complete:true});expect(deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.south'})).toEqual({knownLiving:20,complete:true});expect(deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.spare'})).toEqual({knownLiving:0,complete:true});expect(deriveGeographicPopulation(population,people,runtime,{countryId:'nz',partitionId:'geography.synthetic-nz-v1',placeId:'place.synthetic.nz.root'})).toEqual({knownLiving:8,complete:false});expect(()=>deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v2',placeId:'place.synthetic.ca.root'})).toThrow('does not match');});
 it('conserves assigned complete rollups and distinguishes partial assigned population',()=>{const {people,population}=populationFixture(),runtime=createGeographyRuntime(registry()),complete=deriveCountryPopulation(population,people,'ca'),completeRoot=deriveGeographicPopulation(population,people,runtime,{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:'place.synthetic.ca.root'});expect(completeRoot).toEqual(complete);const partial={...population,memberships:population.memberships.map(item=>item.personId==='person:4'?{...item,countryId:'nz'}:item)};expect(validPopulationWithPeople(partial,people)).toBe(true);expect(validPopulationGeography(partial,people,runtime)).toBe(true);expect(deriveCountryPopulation(partial,people,'nz')).toEqual({knownLiving:9,complete:false});expect(deriveGeographicPopulation(partial,people,runtime,{countryId:'nz',partitionId:'geography.synthetic-nz-v1',placeId:'place.synthetic.nz.root'})).toEqual({knownLiving:8,complete:false});});
 it('rejects unsafe represented-population arithmetic before rollup',()=>{const {people,population}=populationFixture(),first=population.cohorts[0],overflow={...population,cohorts:population.cohorts.map((item,index)=>index===0?{...item,count:Number.MAX_SAFE_INTEGER}:item)};expect(first).toBeDefined();expect(validPopulationWithPeople(overflow,people)).toBe(false);expect(()=>deriveGeographicPopulation(overflow,people,createGeographyRuntime(registry()),{countryId:'ca',partitionId:'geography.synthetic-ca-v1',placeId:first.areaId!})).toThrow('Invalid geographic population query');});
 it('provides allocation-cell resolution for calibration without mutating content',()=>{const value=registry(),before=JSON.stringify(value),exists=geographyAreaExists(createGeographyRuntime(value));expect(exists('geography.synthetic-ca-v1','place.synthetic.ca.village')).toBe(true);expect(exists('geography.synthetic-ca-v1','place.synthetic.ca.spare')).toBe(false);expect(exists('geography.unknown-v1','place.synthetic.ca.village')).toBe(false);expect(JSON.stringify(value)).toBe(before);expect(Reflect.ownKeys(value.partitions[0]).some(key=>typeof key==='string'&&/map|cache|index/i.test(key))).toBe(false);});
 it('compiles synthetic area evidence through the existing calibration resolver contract',()=>{const geography=createGeographyRuntime(registry()),calibrationSource={version:1 as const,id:'source.synthetic-geography-calibration',organisation:'Synthetic',datasetId:'synthetic',releaseId:'v1',title:'Synthetic area evidence',referencePeriod:{from:now,through:now},jurisdiction:'ca',publicationStatus:'final' as const,methodologyNote:'Synthetic test evidence.'},universe={id:'population-universe.synthetic-geography',description:'Synthetic exhaustive residents.',exhaustive:true},measure=(id:string,value:string,areaId?:string)=>({version:1 as const,id,sourceId:calibrationSource.id,series:id,semantic:'population-count' as const,unit:'persons' as const,referenceDate:now,universeId:universe.id,classification:'observed' as const,dimensions:areaId?{kind:'birth-year' as const,birthYear:2000,areaId}:{kind:'total' as const},value}),total=measure('measure.synthetic-geography-total','10'),village=measure('measure.synthetic-geography-village','4','place.synthetic.ca.village'),south=measure('measure.synthetic-geography-south','6','place.synthetic.ca.south'),pkg=withCalibrationFingerprint({schemaVersion:1,methodologyId:'population-calibration.method-v1',id:'calibration.synthetic-geography-v1',countryId:'ca',effectiveDate:now,coverageIntent:'complete',partition:{areaPartitionId:'geography.synthetic-ca-v1',birthYearFrom:2000,birthYearThrough:2000},universes:[universe],sources:[calibrationSource],measures:[south,total,village],derivedTotals:[],authority:{kind:'measure',id:total.id},distributionMeasureIds:[south.id,village.id],reconciliation:{kind:'exact'},ageConversion:{kind:'direct-birth-year'},generationProfileBindings:[{fromBirthYear:2000,throughBirthYear:2000,generationProfileId:'human.synthetic-v1'}],gaps:[]}),result=compilePopulationCalibration(pkg,{profileExists:id=>id==='human.synthetic-v1',areaExists:geographyAreaExists(geography)});expect(result.coverage).toBe('complete');expect(result.cohorts.map(item=>[item.areaId,item.count])).toEqual([['place.synthetic.ca.south',6],['place.synthetic.ca.village',4]]);});
 it('round trips Population references without persisting Geography packages or indexes',()=>{const {game,people,population}=populationFixture(),candidate={...game,people,population},serialized=serializeGame(candidate);expect(serialized.ok).toBe(true);if(!serialized.ok)return;expect(serialized.raw).toContain('geography.synthetic-ca-v1');expect(serialized.raw).not.toContain('Synthetic Canada');const parsed=parseGame(serialized.raw);expect(parsed.reason).toBeNull();expect(parsed.game?.population).toEqual(population);expect(validPopulationGeography(parsed.game!.population,parsed.game!.people,createGeographyRuntime(registry()))).toBe(true);});
 it('has no React, UI, UK, politics, Mereford, Human-generation, host-randomness, or wall-clock dependency',()=>{const modules=import.meta.glob<string>(['./*.ts','!./*.test.ts'],{eager:true,query:'?raw',import:'default'});for(const [path,sourceText] of Object.entries(modules)){expect(sourceText,path).not.toMatch(/from\s+['"][^'"]*(?:react|ui|politics|ukWorld|national|mereford|human\/generation)/i);expect(sourceText,path).not.toMatch(/Math\.random|Date\.now|randomUUID/);}});
});
