import {useState} from 'react';
import type {Game} from '../engine/types';
import type {NationalState} from '../engine/national';
import {createInstitutions,bankAssets,bankLiabilities,capitalRatio,mortgagePayment,consentRegions,factionAssessment} from '../engine/institutions';
import {institutionAction,institutionReason} from '../engine/institutionActions';
import {nationalLaws,type Budget} from '../data/national';
import {scenarioRisks,type RiskId} from '../data/institutions';
import {forecast,type Forecast} from '../engine/forecast';

type Props={game:Game;nation:NationalState;view:string;draft:Budget;update:(fn:(g:Game)=>Game)=>void};
const bn=(v:number)=>`£${v.toFixed(2)}bn`;
export function InstitutionTask({game,update,action,id,label}:{game:Game;update:Props['update'];action:string;id?:string;label:string}){
 const reason=institutionReason(game,action,id);
 return <button className="political-task" disabled={!!reason} onClick={()=>update(g=>institutionAction(g,action,id))}><b>{label}</b><small>{reason??'One shared monthly activity'}</small></button>;
}
export function InstitutionsPanel({game:g,nation:n,view,draft,update}:Props){
 const p=g.politics!,i=n.institutions??createInstitutions(n.month,p.seats,p.party);
 const task=(action:string,label:string,id?:string)=><InstitutionTask game={g} update={update} action={action} label={label} id={id}/>;
 const proposal=n.proposal,law=proposal?.kind==='law'?nationalLaws.find(l=>l.id===proposal.id):undefined;
 return <section className="institutions-panel">
 {!n.institutions&&<p className="political-notice">An opening institutional briefing. These institutions join your saved timeline on your next month or parliamentary action.</p>}
 {view==='Banking'&&<>
  <h3>Credit has a balance sheet.</h3><p>New loans create matching deposits. Repayments remove both; defaults reduce bank capital. Rates, unemployment, regulation and confidence change the supply of credit, which feeds back into investment and output.</p>
  <div className="national-stats">{[['New lending / desired',`${Math.round(i.credit*100)}%`],['Deposits',bn(i.banks.reduce((s,b)=>s+b.deposits,0))],['Cash withdrawn',bn(i.cashOutside)],['Resolution this month',bn(i.publicCost)]].map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</div>
  <div className="institution-cards">{i.banks.map(b=><article key={b.id}><div className="eyebrow">{b.status}</div><h4>{b.name}</h4><div className="institution-facts"><span>Capital / weighted assets <b>{capitalRatio(b).toFixed(1)}%</b></span><span>Mortgage book rate <b>{b.mortgageRate.toFixed(2)}%</b></span><span>Business loan rate <b>{b.loanRate.toFixed(2)}%</b></span><span>Arrears index <b>{b.arrears.toFixed(1)}%</b></span><span>New credit this month <b>{bn(b.newCredit)}</b></span><span>Loan losses this month <b>{bn(b.losses)}</b></span></div><p className="national-note">£200,000 repayment mortgage over 25 years at this modelled rate: <b>£{Math.round(mortgagePayment(200000,b.mortgageRate)).toLocaleString('en-GB')}/month</b>. An illustration, not a personal offer or your character’s debt.</p><details><summary>Open the balance sheet</summary><div className="national-table"><table><tbody>{[['Mortgages',b.mortgages],['Business loans',b.business],['Reserves',b.reserves],['Gilts',b.gilts],['Total assets',bankAssets(b)],['Deposits',b.deposits],['Wholesale creditors',b.wholesale],['Central bank borrowing',b.central],['Equity',b.equity],['Liabilities + equity',bankLiabilities(b)]].map(([label,value])=><tr key={label}><th>{label}</th><td>{bn(Number(value))}</td></tr>)}</tbody></table></div></details></article>)}</div>
  {task('bank','Question the financial regulators')}
  <details className="political-details"><summary>Money creation and resolution record</summary><div className="national-table"><table><thead><tr><th>Month / bank</th><th>Created</th><th>Repaid</th><th>Written off</th><th>Public support</th></tr></thead><tbody>{i.bankLog.slice(-18).reverse().map((r,k)=><tr key={k}><th>{r.month} · {i.banks.find(b=>b.id===r.bank)?.name}</th><td>{bn(r.created)}</td><td>{bn(r.repaid)}</td><td>{bn(r.losses)}</td><td>{bn(r.support)}</td></tr>)}</tbody></table></div></details>
  <p className="fine">Three fictional aggregate lenders; all balances in £bn. Capital weights, stress responses and resolution thresholds are game assumptions. Collateralised liquidity is repayable central-bank borrowing; a capital shortfall instead triggers creditor conversion and, if needed, a public recapitalisation. Interbank settlement, the full regulatory rulebook and individual depositor claims are not yet modelled.</p>
 </>}
 {view==='Devolution'&&<>
  <h3>One union. Distinct political mandates.</h3><p>Changes to comparable England spending generate modelled block-grant changes. Scotland, Wales and Northern Ireland choose their own allocations. Working relationships affect pressure and the chance of securing legislative consent.</p>
  <div className="institution-cards">{i.regions.map(r=><article key={r.id}><div className="eyebrow">DEVOLVED ADMINISTRATION</div><h4>{r.name}</h4><div className="institution-facts"><span>Annual block grant <b>{bn(r.grant)}</b></span><span>Own revenue proxy <b>{bn(r.ownRevenue)}</b></span><span>Working relationship <b>{Math.round(r.trust)}/100</b></span><span>Political pressure <b>{Math.round(r.pressure)}/100</b></span><span>Health allocation <b>{Math.round(r.healthShare*100)}%</b></span><span>Education allocation <b>{Math.round(r.educationShare*100)}%</b></span><span>Health / skills capacity <b>{Math.round(r.health)} / {Math.round(r.skills)}</b></span></div><p className="fine">Remaining allocation: {Math.round((1-r.healthShare-r.educationShare)*100)}% for other devolved services. Allocations can change autonomously each month.</p>{task('region',`Meet ${r.name}’s government`,r.id)}{law&&proposal?.design?.scope==='agreement'&&consentRegions(law).includes(r.id)&&(r.consent===proposal.id?<p className="national-status">Consent secured for {law.name}</p>:task('consent','Seek legislative consent',r.id))}</article>)}</div>
  <p className="fine">Barnett is represented through spending changes, population ratios and simplified comparability, with an assumed inflation-adjusted starting settlement. This is not the actual Treasury settlement or a full fiscal framework. Justice uses England and Wales together; other listed devolved areas use England as the default. Real reservations differ within each policy area. Sewel is a political convention: an agreement-based bill requires consent by your chosen design; an override is possible when drafting, at a cost to relations.</p>
 </>}
 {view==='Factions'&&<>
  <h3>A majority is a relationship.</h3><p>Ten model caucuses share 650 seats. Policy priorities, trust, past promises, discipline, negotiating work and the strength of the whip affect divisions. Opposition groups can be persuaded; government groups can rebel.</p>
  <div className="political-task-grid">{(['free','normal','three-line'] as const).map(w=><div key={w}>{task('whip',`${w===i.whip?'Current: ':''}${w} whip`,w)}</div>)}</div><p className="fine">Three-line pressure can bring votes but leaves resentment among dissenters. These are fictional ideological groupings, not a reconstruction of named real MPs or the present party composition.</p>
  <div className="institution-cards">{i.factions.filter(f=>f.seats>0).map(f=><article key={f.id}><div className="eyebrow">{f.side==='own'?'YOUR PARLIAMENTARY PARTY':'OPPOSITION'} · {f.seats} SEATS</div><h4>{f.name}</h4><p>Priority: <b>{f.priority}</b> · Trust {Math.round(f.trust)} · Grievance {Math.round(f.grievance)}</p>{proposal&&<p className="national-note">Before the House: {factionAssessment(n,proposal,f).reasons.join('. ')}.</p>}<p className="fine">Last division: {f.lastAyes} Ayes · {f.lastNoes} Noes · {f.seats-f.lastAyes-f.lastNoes} other seats. Counts reset after a change in party seats.</p>{f.promise&&<p className="national-note">Commitment: enact a {f.promise.toLowerCase()} measure by month {f.promiseDue}. {Math.max(0,f.promiseDue-n.month)} months remain.</p>}{task('faction','Negotiate with this caucus',f.id)}{task('promise','Offer a twelve-month legislative commitment',f.id)}</article>)}</div>
  <div className="political-task-grid">{task('hearing','Commission committee evidence')}{task('court','Commission a legal review')}</div><p className="fine">Evidence {Math.round(i.evidence)}/100 · Consultation {Math.round(i.consultation)}/100 · Implementation legal-risk index {Math.round(i.judicialRisk)}/100. Scrutiny can reduce delivery risk, but does not guarantee a court outcome.</p>
 </>}
 {view==='Forecasts'&&<ForecastDesk nation={n} draft={draft}/>}
 {view!=='Forecasts'&&<details className="political-details"><summary>Institutional minutes</summary>{i.minutes.length?i.minutes.slice(0,20).map((r,k)=><p key={k}>Month {r.month} · {r.text}</p>):<p>Negotiations, commitments and interventions will be recorded here.</p>}</details>}
 </section>;
}
function ForecastDesk({nation:n,draft}:{nation:NationalState;draft:Budget}){
 const [risk,setRisk]=useState<RiskId>('baseline'),[horizon,setHorizon]=useState(24),[useDraft,setUseDraft]=useState(false),[result,setResult]=useState<Forecast|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sourceKey,setSourceKey]=useState('');
 const budget=useDraft?draft:n.budget;
 const run=()=>{setBusy(true);setError('');setTimeout(()=>{try{setResult(forecast(n,budget,risk,horizon));setSourceKey(JSON.stringify(n));}catch{setError('This scenario could not be calculated. Check the Budget rates and limits.');}finally{setBusy(false);}},30);};
 const stale=result&&(sourceKey!==JSON.stringify(n)||result.at!==n.month||result.risk!==risk||result.horizon!==horizon||JSON.stringify(result.draft)!==JSON.stringify(budget));
 const band=(v:number[],unit='%')=>`${v[1].toFixed(1)}${unit} (${v[0].toFixed(1)}–${v[2].toFixed(1)})`;
 return <><h3>Test an argument before you make it.</h3><p>Explore 24 alternative simulated paths over one to three years. The engine applies your chosen policy, then lets credit, prices, employment and uncertain incidents interact. Running this desk does not advance your life or consume its random sequence.</p><div className="bill-design"><label>External scenario<select value={risk} onChange={e=>setRisk(e.target.value as RiskId)}>{scenarioRisks.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Horizon<select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}>{[12,24,36].map(m=><option key={m} value={m}>{m} months</option>)}</select></label><label>Policy assumption<select value={useDraft?'draft':'current'} onChange={e=>setUseDraft(e.target.value==='draft')}><option value="current">Current enacted Budget</option><option value="draft">My Budget desk draft, assumed enacted now</option></select></label></div><p className="national-note">{scenarioRisks.find(r=>r.id===risk)!.description}</p><button className="political-task" disabled={busy} onClick={run}><b>{busy?'Calculating alternative histories…':'Run the stress test'}</b><small>No monthly activity required</small></button>{error&&<p role="alert">{error}</p>}
 {result&&<section aria-live="polite"><h4>{result.samples} paths from month {result.at}</h4>{stale&&<p className="political-notice">The timeline or assumptions have changed. Run again for an updated comparison.</p>}<p className="fine">Median with 10th–90th sample percentiles in brackets. These are model outcomes, not calibrated probabilities, confidence intervals or official forecasts. They hold the selected Budget fixed and do not assume any pending bill passes.</p><ForecastChart result={result}/><div className="national-table"><table><caption>Conditional outlook · annualised output pace and rates</caption><thead><tr><th>Month</th><th>Output pace</th><th>Inflation</th><th>Unemployment</th><th>Net debt £bn</th><th>Credit supply index</th></tr></thead><tbody>{result.points.filter((_,k)=>(k+1)%3===0).map(r=><tr key={r.month}><th>{r.month}</th><td>{band(r.growth)}</td><td>{band(r.inflation)}</td><td>{band(r.unemployment)}</td><td>{band(r.debt,'')}</td><td>{band(r.credit.map(x=>x*100),'%')}</td></tr>)}</tbody></table></div></section>}
 <p className="fine">Research anchor: September 2026 Bank of England discussions of rates, energy uncertainty and refinancing. Shock magnitudes and responses are explicit game assumptions. News does not automatically rewrite your alternate history. See Sources & assumptions for the dated evidence.</p></>;
}
function ForecastChart({result:r}:{result:Forecast}){
 const [metric,setMetric]=useState<'growth'|'inflation'|'unemployment'>('growth');
 const labels={growth:'Output pace',inflation:'Inflation',unemployment:'Unemployment'};
 const values=r.points.flatMap(p=>p[metric]),low=Math.min(0,...values)-.2,high=Math.max(...values)+.2;
 const x=(index:number)=>45+index/(r.points.length-1)*500,y=(value:number)=>190-(value-low)/(high-low)*165;
 const points=(band:number)=>r.points.map((p,index)=>`${x(index)},${y(p[metric][band])}`);
 const final=r.points.at(-1)!;
 return <figure className="national-chart"><label className="forecast-metric">Explore a measure<select value={metric} onChange={e=>setMetric(e.target.value as typeof metric)}>{Object.entries(labels).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><svg viewBox="0 0 570 225" role="img" aria-label={`${labels[metric]} median and 10th to 90th sample percentile range over ${r.horizon} months`}><line x1="45" y1={y(0)} x2="545" y2={y(0)} stroke="#a5b499" strokeDasharray="4 4"/><polygon points={[...points(0),...points(2).reverse()].join(' ')} fill="#bed0aa" opacity=".6"/><polyline points={points(1).join(' ')} fill="none" stroke="#456c51" strokeWidth="3"/><text x="2" y="30" fontSize="12" fill="#526b4c">{high.toFixed(1)}%</text><text x="2" y="193" fontSize="12" fill="#526b4c">{low.toFixed(1)}%</text><text x="45" y="216" fontSize="12" fill="#526b4c">Month {r.points[0].month}</text><text x="545" y="216" textAnchor="end" fontSize="12" fill="#526b4c">Month {final.month}</text></svg><figcaption>Dark line: median · Shaded band: middle 80% of simulated samples</figcaption><p className="fine">At month {final.month}: {labels[metric].toLowerCase()} median {final[metric][1].toFixed(1)}%, with sample range {final[metric][0].toFixed(1)}% to {final[metric][2].toFixed(1)}%. Different assumptions can move the entire range.</p></figure>;
}
