import {useState} from 'react';
import {nationalLaws} from '../data/national';
import {nationalAction,nationalReason,type NationalState} from '../engine/national';
import {defaultDesign,designFor,devolvedLaw,lawCost,lawDelay,lawActive,type BillDesign} from '../engine/institutions';
import type {Game} from '../engine/types';
export function LegislationCatalogue({game:g,nation:n,update}:{game:Game;nation:NationalState;update:(fn:(g:Game)=>Game)=>void}){
 const [area,setArea]=useState('All'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[design,setDesign]=useState<BillDesign>({...defaultDesign,scope:'england'});
 const filtered=nationalLaws.filter(l=>(area==='All'||l.area===area)&&`${l.name} ${l.summary} ${l.tradeoff}`.toLowerCase().includes(search.toLowerCase()));
 const pages=Math.ceil(filtered.length/12),safePage=Math.min(page,Math.max(0,pages-1));
 return <><h3>Build a legislative programme.</h3><p className="muted">{nationalLaws.length} original policy templates. Configure a proposal before introducing it. These are alternative Acts for your timeline, not descriptions of existing UK law. The settings below apply to the next bill; enacted programmes and a submitted proposal keep their own terms.</p>
 <div className="bill-design">
 <label>Programme scale<select value={design.scale} onChange={e=>setDesign({...design,scale:Number(e.target.value) as BillDesign['scale']})}><option value={.5}>Targeted · 50%</option><option value={1}>Standard · 100%</option><option value={1.5}>Expanded · 150%</option></select></label>
 <label>Devolved policy approach<select value={design.scope} onChange={e=>setDesign({...design,scope:e.target.value as BillDesign['scope']})}><option value="england">Home jurisdiction only</option><option value="agreement">Seek devolved agreement</option><option value="override">Legislate across the UK without consent</option></select></label>
 <label>Delivery programme<select value={design.delivery} onChange={e=>setDesign({...design,delivery:e.target.value as BillDesign['delivery']})}><option value="standard">Standard timetable</option><option value="accelerated">Accelerated · costs 25% more</option></select></label>
 <label>Duration<select value={design.sunset} onChange={e=>setDesign({...design,sunset:Number(e.target.value) as BillDesign['sunset']})}><option value={0}>Ongoing programme</option><option value={60}>Five-year sunset from enactment</option></select></label>
 </div><p className="fine">Reserved policies apply UK-wide. For devolved templates, home jurisdiction means England, or England and Wales for justice. Accelerating delivery raises implementation risk; a sunset ends programme funding and ongoing market effects, while completed infrastructure and training remain. Scotland, Wales and Northern Ireland retain their own spending choices.</p>
 <div className="national-filter"><label>Policy area<select value={area} onChange={e=>{setArea(e.target.value);setPage(0);}}>{['All',...new Set(nationalLaws.map(l=>l.area))].map(x=><option key={x}>{x}</option>)}</select></label><label>Find a proposal<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Housing, credit, rights…"/></label></div>
 <p className="fine" role="status">{filtered.length} matching proposals{pages>0?` · Page ${safePage+1} of ${pages}`:''}</p>
 <div className="national-law-list">{filtered.slice(safePage*12,safePage*12+12).map(l=>{const enacted=n.enacted.find(e=>e.id===l.id),resolved=designFor(l,design),reason=nationalReason(g,'law',l.id),active=enacted&&lawActive(enacted,n.month);return <article key={l.id}><div className="eyebrow">{l.area} · £{lawCost(l,resolved.scale,resolved).toFixed(1)}bn/YEAR · {lawDelay(l,resolved)}+ MONTHS</div><h3>{l.name}</h3><p>{l.summary}</p><p className="muted">{l.tradeoff}</p><p className="fine">{devolvedLaw(l)?resolved.scope==='england'?(l.area==='Justice'?'England and Wales':'England only'):resolved.scope==='agreement'?'Devolved consent required':'UK-wide override · relations at risk':'UK-wide reserved policy'} · {Math.round(resolved.scale*100)}% scale</p><details><summary>Modelled channels</summary><p className="fine">{Object.entries(l.effect).map(([key,value])=>`${key}: ${Number(value)>0?'+':''}${value}`).join(' · ')} at full scale before territorial adjustment. These are scenario coefficients, not empirically estimated effects. Delivery timing and the wider economy affect the eventual outcome.</p></details>{enacted?<p className="national-status">{!active?'Sunset reached':enacted.delivered?'In delivery':`Enacted · expected from month ${enacted.due}`} · {Math.round(enacted.intensity*100)}% scale · £{lawCost(l,enacted.intensity,enacted.design).toFixed(1)}bn/year{enacted.design?.sunset?` · sunset month ${enacted.month+60}`:''}</p>:<button className="political-task" disabled={!!reason} onClick={()=>update(x=>nationalAction(x,'law',l.id,undefined,resolved))}><b>Introduce this bill</b><small>{reason??'One shared monthly activity'}</small></button>}</article>;})}</div>
 {pages>1&&<div className="catalogue-pages"><button className="quiet outlined" disabled={safePage===0} onClick={()=>setPage(safePage-1)}>Previous proposals</button><span>{safePage+1} / {pages}</span><button className="quiet outlined" disabled={safePage>=pages-1} onClick={()=>setPage(safePage+1)}>Next proposals</button></div>}
 </>;
}
