import { useState } from 'react';
import { baselineBudget,budgetFields,budgetStages,legislativeStages,nationalLaws,nationalSources,sectors,type Budget,type BudgetKey } from '../data/national';
import { createNational,costBudget,distribution,nationalAction,nationalReason,validBudget,type NationalState } from '../engine/national';
import type { Game } from '../engine/types';
import './national.css';
import {InstitutionsPanel,InstitutionTask} from './InstitutionsPanel';
import {LegislationCatalogue} from './LegislationCatalogue';
import {institutionalSources} from '../data/institutions';
import {consentRegions} from '../engine/institutions';
type Props={game:Game;update:(fn:(g:Game)=>Game)=>void;legislation?:boolean};
const bn=(v:number)=>`£${v.toLocaleString('en-GB',{minimumFractionDigits:1,maximumFractionDigits:1})}bn`;
const pct=(v:number)=>`${v.toFixed(1)}%`;
export function NationalEconomy({game:g,update,legislation=false}:Props){
 const p=g.politics!;const n=p.national??createNational(g.seed,p.months);
 const [view,setView]=useState('Briefing');const [draft,setDraft]=useState<Budget>(()=>({...n.budget}));
 const proposal=n.proposal;const estimate=costBudget(n,draft),current=costBudget(n,n.budget);const latest=n.history.at(-1);
 const submit=(action:string,id?:string,b?:Budget)=>update(x=>nationalAction(x,action,id,b));
 const task=(action:string,label:string,id?:string,b?:Budget)=>{const reason=nationalReason(g,action,id)??(b&&!validBudget(b)?'Keep rates in ascending order and values within the shown limits.':null);return <button className="political-task" disabled={!!reason} onClick={()=>submit(action,id,b)}><b>{label}</b><small>{reason??'Uses one shared monthly activity'}</small></button>;};
 const passage=<>
  {proposal&&<section className="national-proposal"><div className="eyebrow">BEFORE PARLIAMENT · NOT YET IN FORCE</div><h3>{proposal.kind==='budget'?'Your Treasury package':nationalLaws.find(l=>l.id===proposal.id)!.name}</h3><ol>{(proposal.kind==='budget'?budgetStages:legislativeStages).map((stage,i)=><li key={stage} className={i<=proposal.stage?'reached':''}>{stage}</li>)}</ol><p>{proposal.kind==='law'?`${Math.round(proposal.intensity*100)}% scale programme · ${proposal.consent?'Government money-resolution support secured':'Government money-resolution support still needed'}.`:'Tax legislation and spending authorisation are bundled into this playable sequence; in Parliament they are distinct processes.'} Negotiated backing: {Math.round(proposal.support)}/35.</p>
   {proposal.budget&&<p>Submitted package: {bn(costBudget(n,proposal.budget).revenue*12)} annualised receipts / {bn(costBudget(n,proposal.budget).spending*12)} spending at today’s modelled economy.</p>}
   <div className="political-task-grid"><InstitutionTask game={g} update={update} action="hearing" label="Hear committee evidence"/><InstitutionTask game={g} update={update} action="court" label="Review the legal drafting"/>{task('advance','Take the next legislative stage')}{task('lobby','Negotiate across the House')}{proposal.kind==='law'&&task('amend','Offer a half-scale compromise')}{task('withdraw','Withdraw this proposal')}</div><p className="fine">Commons divisions use party backing, negotiating work, controversy, attendance and uncertain rebellion. Defeat ends the bill. Lords scrutiny may delay ordinary legislation; financial scrutiny does not become an invented Lords tax veto. Royal Assent is not a random obstacle.</p>
   {proposal.design&&<p className="fine">Territory: {proposal.design.scope} · Delivery: {proposal.design.delivery} · {proposal.design.sunset?'Five-year sunset':'Ongoing programme'}</p>}
   {proposal.kind==='law'&&proposal.design?.scope==='agreement'&&n.institutions?.regions.filter(r=>consentRegions(nationalLaws.find(l=>l.id===proposal.id)!).includes(r.id)).map(r=>r.consent===proposal.id?<p className="national-status" key={r.id}>{r.name}: consent secured</p>:<InstitutionTask key={r.id} game={g} update={update} action="consent" id={r.id} label={`Seek ${r.name}’s legislative consent`}/>)}
  </section>}
  <LegislationCatalogue game={g} nation={n} update={update}/>
  <h3 className="political-subheading">The division record</h3>{n.divisions.length?n.divisions.slice(0,10).map((d,i)=><p className="national-division" key={i}><b>{d.title} · {d.passed?'Passed':'Defeated'}</b><span>Month {d.month}: {d.ayes} Ayes · {d.noes} Noes · {d.abstain} not voting</span></p>):<p className="muted">Recorded Commons votes will appear here.</p>}
 </>;
 return <section className="national-economy">
  <div className="national-banner"><div className="eyebrow">UNITED KINGDOM · YOUR ALTERNATE TIMELINE</div><h3>{legislation?'From an idea to an Act.':'A country beyond your constituency.'}</h3><p>Starting rules researched on 21 September 2026. Events after entry are simulated. Your character, family and constituency live through the same months.</p></div>
  {!p.national&&<p className="political-notice">This national layer begins on your next month or parliamentary action. Your existing life and earlier constituency history stay intact.</p>}
  {legislation?passage:<>
  <nav className="national-tabs" aria-label="National economy areas">{['Briefing','Budget desk','Households & sectors','Public accounts','Banking','Devolution','Factions','Forecasts','Sources & assumptions'].map(x=><button aria-current={view===x?'page':undefined} key={x} onClick={()=>setView(x)}>{x}</button>)}</nav>
  {['Banking','Devolution','Factions','Forecasts'].includes(view)&&<InstitutionsPanel game={g} nation={n} view={view} draft={draft} update={update}/>}
  {view==='Briefing'&&<>
   <div className="national-stats">{[['Annual output',bn(n.realGDP*n.prices)],['Output pace¹',pct(n.growth)],['CPI inflation',pct(n.inflation)],['Unemployment',pct(n.unemployment)],['Bank Rate',(n.bankRate.toFixed(2)+'%')],['Net debt / GDP',pct(n.debt/(n.realGDP*n.prices)*100)],['Gilt yield',(n.yield.toFixed(2)+'%')],['Monthly borrowing',bn(n.fiscal.balance)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
   <p className="fine">¹ Current monthly output change annualised, not a published ONS year-on-year statistic. Output and fiscal starting totals are explicit scenario assumptions.</p>
   <HistoryChart nation={n}/>
   <h3 className="political-subheading">On your desk this month</h3>{latest?latest.notes.map((x,i)=><p className="national-note" key={i}>{x}</p>):<p className="muted">Your first national briefing arrives after the next month. There is no fixed sequence of crises.</p>}
   <h3 className="political-subheading">Dispatches from the country</h3>{n.news.length?n.news.slice(0,6).map((x,i)=><article className="national-news" key={i}><small>SIMULATED · MONTH {x.month}</small><h4>{x.title}</h4><p>{x.text}</p></article>):<p className="muted">Quiet months are possible. News emerges from uncertain events and economic pressures, not a repeating two-year script.</p>}
   <details className="political-details"><summary>How this reaches your life</summary><p>National prices and VAT changes alter personal living costs. Changes in Income Tax and employee NI alter your take-home pay relative to the original career baseline. Pensions, benefits and local grants reach constituency accounts. Sterling and energy affect bills; orders and output affect employers. Delivered housing programmes ease modelled local rent pressure. National performance also affects political support and which dilemmas are more likely.</p><p>Old salaries were take-home amounts. We preserve them and estimate the effect of tax changes using a gross-income proxy (take-home divided by 0.8). This is a game bridge, not a payroll calculator.</p></details>
  </>}
  {view==='Budget desk'&&<>
   <h3>Write a Budget. Defend its consequences.</h3><p className="muted">Anyone can draft and compare; only a submitted package is saved. As Prime Minister, submit it through the Treasury and Parliament. Until passage, the existing Budget remains in force. A council seat or the housing brief does not confer tax-setting powers.</p>
   <div className="national-estimate"><div><small>ANNUALISED RECEIPTS</small><strong>{bn(estimate.revenue*12)}</strong></div><div><small>ANNUALISED SPENDING</small><strong>{bn(estimate.spending*12)}</strong></div><div><small>BORROWING AT TODAY’S ECONOMY</small><strong>{bn(estimate.balance*12)}</strong></div><p>Change from current policy: {bn((estimate.balance-current.balance)*12)} borrowing/year. A static costing, not a promise: employment, prices, confidence and interest costs will react.</p></div>
   <div className="national-controls">{Object.entries(budgetFields).map(([key,f])=><label key={key}><span>{f.label}<small>Current: {n.budget[key as BudgetKey]} {f.unit}</small></span><span><input aria-label={f.label} type="number" min={f.min} max={f.max} step={f.step} value={draft[key as BudgetKey]} onChange={e=>setDraft(d=>({...d,[key]:Number(e.target.value)}))}/><small>{f.unit} · {f.min}–{f.max}</small></span></label>)}</div>
   <div className="life-backup-controls"><button className="quiet outlined" onClick={()=>setDraft({...n.budget})}>Copy current policy</button><button className="quiet outlined" onClick={()=>setDraft({...baselineBudget})}>Compare starting policy</button></div>{task('budget','Submit the tax and supply package',undefined,draft)}
   <details className="political-details"><summary>What these figures do and do not represent</summary><p>Income Tax uses the personal allowance taper above £100,000, the £37,700 basic taxable band, and the additional threshold at £125,140. Employee NI uses a main rate and 2% upper rate. National receipts use representative earners, not the complete tax register. VAT uses taxable consumption and Corporation Tax a profit proxy.</p><p>Spending amounts are editable scenario envelopes in nominal £bn/year, not official departmental settlements. Comparable health, education and transport changes feed a simplified Barnett calculation. The separate Devolution desk shows block grants and devolved allocations; Westminster cannot prescribe those allocations. Fiscal frameworks and tax adjustments remain simplified.</p></details>
   {proposal&&<p className="political-notice">A proposal is before the House. Continue it in Parliament; editing this desk does not change the submitted package.</p>}
  </>}
  {view==='Households & sectors'&&<>
   <h3>Who gains, who pays, and who can deliver?</h3><div className="national-table"><table><caption>Representative employed earners · annual values</caption><thead><tr><th>Group</th><th>Gross</th><th>Tax + NI</th><th>Real take-home</th><th>Draft change</th></tr></thead><tbody>{distribution(n).map((e,i)=>{const changed=distribution(n,draft)[i];return <tr key={e.name}><th>{e.name}</th><td>£{Math.round(e.gross).toLocaleString()}</td><td>£{Math.round(e.tax+e.ni).toLocaleString()}</td><td>£{Math.round(e.realNet).toLocaleString()}</td><td>£{Math.round(changed.realNet-e.realNet).toLocaleString()}</td></tr>;})}</tbody></table></div><p className="fine">Illustrative earnings cohorts; excludes full household composition, benefit eligibility, Scottish tax differences and individual deductions. Real take-home includes a simplified VAT exposure.</p>
   <div className="national-sector-list">{n.sectors.map((s,i)=><article key={s.id}><h4>{sectors[i].name}</h4><strong>{bn(s.output*n.prices)}</strong><p>{pct(s.growth)} output pace · {Math.round(sectors[i].trade*100)}% trade exposure index</p></article>)}</div>
   <div className="political-indicators">{[['Health capacity',n.health],['Skills capacity',n.skills],['Housing access',n.housing],['Worker protections',n.rights],['Competition',n.competition],['Business confidence',n.confidence]].map(([label,value])=><div key={label}><span>{label}</span><b>{Math.round(Number(value))}</b><meter aria-label={String(label)} min={0} max={100} value={Number(value)}/></div>)}</div><p className="fine">Capacity and institutional scores are model indices. Training and building Acts have uncertain delivery dates. Higher spending cannot instantly create trained staff.</p>
  </>}
  {view==='Public accounts'&&<>
   <h3>The monthly public ledger</h3><p className="muted">Treasury receipts and outlays are in £bn. The financing counterpart is a change in net bondholder claims: deficits add liabilities; surpluses reduce them. The Banking desk separately tracks lenders’ balance sheets. These are linked simulations, not a complete consolidated national accounts system.</p>
   <div className="national-table"><table><thead><tr><th>Flow</th><th>From → to</th><th>£bn/month</th></tr></thead><tbody>{n.fiscal.flows.map((f,i)=><tr key={i}><th>{f.name}</th><td>{f.from} → {f.to}</td><td>{f.amount.toFixed(2)}</td></tr>)}</tbody></table></div>
   <p className="national-note">{bn(latest?.openingDebt??n.openingDebt)} opening net debt + {bn(latest?.borrowing??0)} net borrowing = {bn(n.debt)} closing net debt. Matching net bondholder claims: {bn(n.bondAssets)}.</p>
   <p className="fine">The constituency is a representative satellite model, not an extra addition to national totals. Its clearing-account transfers should not be summed into this ledger. Other receipts/expenditure are explicit aggregate proxies; the public balance excludes a detailed asset valuation and stock-flow-adjustment model.</p>
  </>}
  {view==='Sources & assumptions'&&<>
   <h3>A dated starting point, then your history.</h3><p className="muted">Verified on 21 September 2026: CPI 3.1% (August), unemployment 4.9% (May–July), Bank Rate 3.75%, and 2026/27 headline tax rules. No live headlines overwrite your timeline.</p>
   <p>Scenario assumptions: £3,050bn initial annual output, £2,950bn initial net debt, four sector weights, representative incomes, spending envelopes and all behavioural responses. These totals are rounded game assumptions, not a claimed current ONS/OBR dataset or forecast. Scottish tax schedules, reliefs and detailed trade accounts remain incomplete. Banks, factions and devolved governments use fictional aggregate balance sheets, caucuses and settlements; they do not reproduce the current real institutions individually.</p>
   <p>The independent monetary response, investment delays, tax effects and incident probabilities are contestable model choices. Random draws are saved with your life so reloading preserves continuity. Outcomes vary with the seed, decisions and conditions; no route is scripted to succeed.</p>
   {[...nationalSources,...institutionalSources].map(s=><a className="national-source" key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>)}
  </>}
  </>}
 </section>;
}
function HistoryChart({nation:n}:{nation:NationalState}){
 const rows=n.history.slice(-36);if(rows.length<2)return null;const values=rows.flatMap(x=>[x.inflation,x.unemployment,x.growth]);const low=Math.min(0,...values)-1,high=Math.max(...values)+1;
 const points=(key:'inflation'|'unemployment'|'growth')=>rows.map((r,i)=>`${i/(rows.length-1)*600},${120-(r[key]-low)/(high-low)*110}`).join(' ');
 return <figure className="national-chart"><svg viewBox="0 0 600 130" role="img" aria-label="Recent inflation, unemployment and growth trend"><polyline points={points('inflation')} fill="none" stroke="#ae7548" strokeWidth="3"/><polyline points={points('unemployment')} fill="none" stroke="#7f699c" strokeWidth="3"/><polyline points={points('growth')} fill="none" stroke="#456c51" strokeWidth="3"/></svg><figcaption><span>● Inflation</span><span>● Unemployment</span><span>● Output pace</span>Months {rows[0].month}–{rows.at(-1)!.month}</figcaption><details><summary>Read monthly figures</summary><div className="national-table"><table><thead><tr><th>Month</th><th>Inflation</th><th>Unemployment</th><th>Output pace</th></tr></thead><tbody>{rows.map(r=><tr key={r.month}><td>{r.month}</td><td>{pct(r.inflation)}</td><td>{pct(r.unemployment)}</td><td>{pct(r.growth)}</td></tr>)}</tbody></table></div></details></figure>;
}
