import {describe,expect,it,vi} from 'vitest';
import {createNewGameSubmission} from './newGameSubmission';
const deferred=<T>()=>{let resolve!:(value:T)=>void,reject!:(error:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
const fixture=()=>{const phase=vi.fn(),cancelConstruction=vi.fn(),controller=createNewGameSubmission<object>({phase,cancelConstruction}),prepare=vi.fn(async()=>{}),commit=vi.fn(async()=>{}),activate=vi.fn();return {controller,phase,cancelConstruction,prepare,commit,activate};};
describe('fresh world application submission lifetime',()=>{
 it('admits exactly one build synchronously across duplicate callbacks and keeps no candidate cache',async()=>{const f=fixture(),wait=deferred<object>(),build=vi.fn(()=>wait.promise),first=f.controller.run(build,f.prepare,f.commit,f.activate);expect(f.controller.busy()).toBe(true);expect(await f.controller.run(build,f.prepare,f.commit,f.activate)).toBe(false);wait.resolve({id:1});expect(await first).toBe(true);expect(build).toHaveBeenCalledTimes(1);expect(f.commit).toHaveBeenCalledTimes(1);expect(f.activate).toHaveBeenCalledTimes(1);expect(f.controller.busy()).toBe(false);expect(Object.keys(f.controller).sort()).toEqual(['abandon','busy','cancel','run']);expect(f.phase.mock.calls.map(call=>call[0])).toEqual(['constructing','preparing','committing','idle']);});
 it('cancels construction, disposes its Worker, ignores a late result, and allows an immediate independent retry',async()=>{const f=fixture(),old=deferred<object>(),signals:AbortSignal[]=[],first=f.controller.run(signal=>{signals.push(signal);return old.promise;},f.prepare,f.commit,f.activate);expect(f.controller.cancel()).toBe(true);expect(signals[0].aborted).toBe(true);expect(f.cancelConstruction).toHaveBeenCalledTimes(1);expect(await f.controller.run(async()=>({id:2}),f.prepare,f.commit,f.activate)).toBe(true);old.resolve({id:1});expect(await first).toBe(false);expect(f.activate).toHaveBeenCalledExactlyOnceWith({id:2});expect(f.commit).toHaveBeenCalledExactlyOnceWith({id:2});});
 it('cancels content acceptance before saving and prevents stale preparation publishing',async()=>{const f=fixture(),wait=deferred<void>(),first=f.controller.run(async()=>({id:1}),()=>wait.promise,f.commit,f.activate);await Promise.resolve();expect(f.controller.cancel()).toBe(true);wait.resolve();expect(await first).toBe(false);expect(f.commit).not.toHaveBeenCalled();expect(f.activate).not.toHaveBeenCalled();expect(f.cancelConstruction).not.toHaveBeenCalled();});
 it.each(['build','prepare','commit'] as const)('preserves the active world on %s failure without fallback and permits retry',async stage=>{const f=fixture(),error=Error(stage),fail=async()=>{throw error;};await expect(f.controller.run(stage==='build'?fail:async()=>({id:1}),stage==='prepare'?fail:f.prepare,stage==='commit'?fail:f.commit,f.activate)).rejects.toBe(error);expect(f.activate).not.toHaveBeenCalled();expect(f.controller.busy()).toBe(false);expect(await f.controller.run(async()=>({id:2}),f.prepare,f.commit,f.activate)).toBe(true);});
 it('does not claim a started atomic commit can be cancelled; unmount prevents its late activation',async()=>{const f=fixture(),wait=deferred<void>(),first=f.controller.run(async()=>({id:1}),f.prepare,()=>wait.promise,f.activate);await Promise.resolve();await Promise.resolve();expect(f.controller.cancel()).toBe(false);f.controller.abandon();wait.resolve();expect(await first).toBe(false);expect(f.activate).not.toHaveBeenCalled();});
 it('invalidates unmounted requests without notifying obsolete React state, then works on remount',async()=>{const f=fixture(),wait=deferred<object>(),first=f.controller.run(()=>wait.promise,f.prepare,f.commit,f.activate);f.controller.abandon();expect(f.phase).toHaveBeenCalledTimes(1);wait.reject(Error('late worker failure'));expect(await first).toBe(false);expect(await f.controller.run(async()=>({id:2}),f.prepare,f.commit,f.activate)).toBe(true);});
});
