import {afterEach,describe,expect,it,vi} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {createUkMid2024Game} from '../data/uk/countryStart';
import type {UkMid2024StartRequestV1} from '../data/uk/countryStart';
import {UK_GEOGRAPHIC_COUNTRY_START_SCENARIO} from '../data/uk/countryStartGeographic';
import {createUkGeographyRegistry} from '../data/geography/uk/primary-local-admin-2024/adapter';
import {createUkHumanGenerationContentRegistry} from '../data/human/uk/generation/adapter';
import {createGeographyRuntime} from '../engine/geography/runtime';
import {instantiateFromCohortWithContent} from '../engine/human/content/integration';
import {deriveCountryPopulation} from '../engine/human/population';
import type {Game} from '../engine/types';
import {deletePersistenceDatabase} from '../persistence/indexedDb';
import {GamePersistence,type LegacyStorage} from '../persistence/service';
import {createProductionUkNewGame,NewGameInputError,newGameNameError,platformRootSeed} from './newGame';

const fakeGame={version:3} as Game;
const call=(overrides:Partial<{mode:'childhood'|'adult';name:string;genderLabel:string}>={},seed=73)=>{const bootstrap=vi.fn<(request:UkMid2024StartRequestV1)=>Game>(()=>fakeGame),rootSeed=vi.fn<()=>number>(()=>seed),form={mode:'childhood' as const,name:'',genderLabel:'',...overrides},game=createProductionUkNewGame(form,{bootstrap,rootSeed});return {game,bootstrap,rootSeed,request:bootstrap.mock.calls[0]![0]};};
const production=(mode:'childhood'|'adult',seed=73,identity:Partial<{name:string;genderLabel:string}>={})=>{const getRandomValues=vi.fn((value:Uint32Array)=>{value[0]=seed;return value;}),original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{configurable:true,value:{getRandomValues}});try{return {game:createProductionUkNewGame({mode,name:identity.name??'',genderLabel:identity.genderLabel??''}),getRandomValues};}finally{Object.defineProperty(globalThis,'crypto',{configurable:true,value:original});}};
const legacy:LegacyStorage={getItem:()=>null,setItem:()=>{}};
const cleanups:Array<()=>Promise<void>>=[];
afterEach(async()=>{for(const cleanup of cleanups.splice(0))await cleanup();});

describe('New Game UI production composition',()=>{
 it('submits the two exact domain modes without age, DOB, country, or package fields',()=>{for(const mode of ['childhood','adult'] as const){const result=call({mode});expect(result.game).toBe(fakeGame);expect(result.request).toEqual({version:1,rootSeed:73,mode});expect(result.request).not.toHaveProperty('age');expect(result.request).not.toHaveProperty('dateOfBirth');expect(result.request).not.toHaveProperty('countryId');}});
 it('omits blank identity fields and passes trimmed valid overrides',()=>{expect(call({name:'   ',genderLabel:''}).request).not.toHaveProperty('identity');expect(call({name:'  Ada Example  ',genderLabel:'  Self-described  '}).request.identity).toEqual({name:'Ada Example',genderLabel:'Self-described'});});
 it('accepts 256 Unicode code points, rejects 257, and never truncates',()=>{const accepted='😀'.repeat(256),result=call({name:accepted});expect(result.request.identity?.name).toBe(accepted);expect([...result.request.identity!.name!]).toHaveLength(256);expect(newGameNameError('😀'.repeat(257))).toContain('256');const bootstrap=vi.fn(()=>fakeGame),rootSeed=vi.fn(()=>1);expect(()=>createProductionUkNewGame({mode:'adult',name:'😀'.repeat(257),genderLabel:''},{bootstrap,rootSeed})).toThrow(NewGameInputError);expect(bootstrap).not.toHaveBeenCalled();expect(rootSeed).not.toHaveBeenCalled();});
 it('generates one uint32 seed per valid submission and none for invalid input',()=>{const valid=call({mode:'adult'});expect(valid.rootSeed).toHaveBeenCalledTimes(1);expect(valid.request.rootSeed).toBe(73);const bootstrap=vi.fn(()=>fakeGame),rootSeed=vi.fn(()=>9);expect(()=>createProductionUkNewGame({mode:'adult',name:'x'.repeat(257),genderLabel:''},{bootstrap,rootSeed})).toThrow();expect(rootSeed).not.toHaveBeenCalled();expect(bootstrap).not.toHaveBeenCalled();expect(()=>createProductionUkNewGame({mode:'adult',name:'',genderLabel:'',country:'ca'} as never,{bootstrap,rootSeed})).toThrow(NewGameInputError);expect(bootstrap).not.toHaveBeenCalled();});
 it('surfaces bootstrap failure without mutating existing application state',()=>{const current={id:'existing'},rootSeed=vi.fn(()=>4),bootstrap=vi.fn(()=>{throw Error('internal package detail');});expect(()=>createProductionUkNewGame({mode:'childhood',name:'',genderLabel:''},{rootSeed,bootstrap})).toThrow('internal package detail');expect(current).toEqual({id:'existing'});expect(rootSeed).toHaveBeenCalledTimes(1);expect(bootstrap).toHaveBeenCalledTimes(1);});
 it('uses secure platform randomness as one exact uint32 draw',()=>{const getRandomValues=vi.fn((value:Uint32Array)=>{value[0]=0xffffffff;return value;}),original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{configurable:true,value:{getRandomValues}});try{expect(platformRootSeed()).toBe(0xffffffff);expect(getRandomValues).toHaveBeenCalledTimes(1);expect(getRandomValues.mock.calls[0][0]).toHaveLength(1);}finally{Object.defineProperty(globalThis,'crypto',{configurable:true,value:original});}});
 it('routes both production modes through frozen geographic content with one real allocation-cell membership',()=>{const runtime=createGeographyRuntime(createUkGeographyRegistry());expect(UK_GEOGRAPHIC_COUNTRY_START_SCENARIO.id).toBe('country-start.uk.mid-2024-v2');for(const [mode,age,birthYear] of [['childhood',0,2024],['adult',18,2006]] as const){const {game,getRandomValues}=production(mode);expect(getRandomValues).toHaveBeenCalledTimes(1);expect(game).toMatchObject({version:4,age,clock:{version:2,date:{year:2024,month:6,day:30}},people:{version:1,playerId:'person:1',nextSequence:2},population:{version:1,coverage:[{countryId:'uk',status:'complete',source:'uk.population.mid-2024.v3',areaPartitionId:'geography.uk.primary-local-admin-2024-06-30-v1'}]}});expect(game.people!.people).toHaveLength(1);expect(game.people!.people[0].dateOfBirth.year).toBe(birthYear);expect(game.population!.memberships).toHaveLength(1);const membership=game.population!.memberships[0];expect(membership).toMatchObject({personId:'person:1',countryId:'uk',origin:{kind:'cohort',requestIndex:0}});expect(membership.areaId).not.toBeNull();expect(runtime.isPopulationAllocationCell(UK_GEOGRAPHIC_COUNTRY_START_SCENARIO.geographyPartitionId,membership.areaId!)).toBe(true);expect(deriveCountryPopulation(game.population!,game.people!,'uk')).toEqual({knownLiving:69_281_437,complete:true});expect((game.people!.people[0] as unknown as Record<string,unknown>).residence).toBeUndefined();expect((game.people!.people[0] as unknown as Record<string,unknown>).presence).toBeUndefined();}},30_000);
 it('is deterministic through the default route and identity overrides do not change geographic allocation',()=>{const generated=production('adult',419).game,repeat=production('adult',419).game,overridden=production('adult',419,{name:'Geographic Player',genderLabel:'Self-described'}).game;expect(repeat).toEqual(generated);expect(overridden.population).toEqual(generated.population);expect(overridden.randomness).toEqual(generated.randomness);expect(overridden.people!.people[0]).toMatchObject({name:'Geographic Player',genderLabel:'Self-described'});expect(overridden.population!.memberships[0].areaId).toBe(generated.population!.memberships[0].areaId);},30_000);
 it('persists the production route through IndexedDB, reopens canonically, and continues at person:2',async()=>{const game=production('adult',2024).game,factory=new IDBFactory(),databaseName='new-game-geographic-route-v1',first=await GamePersistence.open(legacy,factory,databaseName);expect(await first.save(game,null)).toBe(1);first.close();const second=await GamePersistence.open(legacy,factory,databaseName),loaded=await second.initialize();cleanups.push(async()=>{second.close();await deletePersistenceDatabase(factory,databaseName);});expect(loaded.game).toEqual(game);expect(loaded.revision).toBe(1);expect(loaded.game!.population!.memberships[0].areaId).not.toBeNull();expect(JSON.stringify(loaded.game)).not.toContain('human-content.uk.mid-2024-v1');const cohort=loaded.game!.population!.cohorts.find(item=>item.birthYear===2000)!,next=instantiateFromCohortWithContent({people:loaded.game!.people!,population:loaded.game!.population!,rootSeed:2024,cohortId:cohort.id,requestKey:'new-game.uk.mid-2024-v2.continuation',count:1,referenceDate:UK_GEOGRAPHIC_COUNTRY_START_SCENARIO.simulationStartDate,contentRegistry:createUkHumanGenerationContentRegistry()});expect(next.persons[0].id).toBe('person:2');expect(next.population.memberships.at(-1)?.areaId).toBe(cohort.areaId);expect(deriveCountryPopulation(next.population,next.people,'uk')).toEqual({knownLiving:69_281_437,complete:true});},30_000);
 it('keeps direct v1 construction as frozen non-geographic compatibility content',()=>{const game=createUkMid2024Game({version:1,rootSeed:73,mode:'adult'});expect(game.population!.coverage).toEqual([{countryId:'uk',status:'complete',source:'uk.population.mid-2024.v2',areaPartitionId:null}]);expect(game.population!.memberships[0].areaId).toBeNull();expect(deriveCountryPopulation(game.population!,game.people!,'uk')).toEqual({knownLiving:69_281_437,complete:true});});
 it('keeps LifeApp on the UI wrapper and leaves scenario rules and legacy constructors outside production submission',()=>{const sources=import.meta.glob<string>(['./LifeApp.tsx','./newGame.ts'],{eager:true,query:'?raw',import:'default'}),app=Object.entries(sources).find(([path])=>path.endsWith('/LifeApp.tsx'))![1],wrapper=Object.entries(sources).find(([path])=>path.endsWith('/newGame.ts'))![1];expect(app).toContain('createProductionUkNewGame');expect(app).not.toMatch(/\bcreateGame\b|\badultStart\b/);expect(wrapper).toContain("from '../data/uk/countryStartGeographic'");expect(wrapper).toContain('bootstrap:createUkMid2024GeographicGame');expect(wrapper).not.toContain('bootstrap:createUkMid2024Game');expect(wrapper).not.toMatch(/dateOfBirth|populationPackageId|humanContentPackageId|humanProfileId/);});
});
