import {describe,expect,it,vi} from 'vitest';
import {createUkMid2024Game} from '../data/uk/countryStart';
import type {UkMid2024StartRequestV1} from '../data/uk/countryStart';
import {loadGame,saveGame} from '../engine/save';
import type {Game} from '../engine/types';
import {createProductionUkNewGame,NewGameInputError,newGameNameError,platformRootSeed} from './newGame';

const fakeGame={version:3} as Game;
const call=(overrides:Partial<{mode:'childhood'|'adult';name:string;genderLabel:string}>={},seed=73)=>{const bootstrap=vi.fn<(request:UkMid2024StartRequestV1)=>Game>(()=>fakeGame),rootSeed=vi.fn<()=>number>(()=>seed),form={mode:'childhood' as const,name:'',genderLabel:'',...overrides},game=createProductionUkNewGame(form,{bootstrap,rootSeed});return {game,bootstrap,rootSeed,request:bootstrap.mock.calls[0]![0]};};

describe('New Game UI production composition',()=>{
 it('submits the two exact domain modes without age, DOB, country, or package fields',()=>{for(const mode of ['childhood','adult'] as const){const result=call({mode});expect(result.game).toBe(fakeGame);expect(result.request).toEqual({version:1,rootSeed:73,mode});expect(result.request).not.toHaveProperty('age');expect(result.request).not.toHaveProperty('dateOfBirth');expect(result.request).not.toHaveProperty('countryId');}});
 it('omits blank identity fields and passes trimmed valid overrides',()=>{expect(call({name:'   ',genderLabel:''}).request).not.toHaveProperty('identity');expect(call({name:'  Ada Example  ',genderLabel:'  Self-described  '}).request.identity).toEqual({name:'Ada Example',genderLabel:'Self-described'});});
 it('accepts 256 Unicode code points, rejects 257, and never truncates',()=>{const accepted='😀'.repeat(256),result=call({name:accepted});expect(result.request.identity?.name).toBe(accepted);expect([...result.request.identity!.name!]).toHaveLength(256);expect(newGameNameError('😀'.repeat(257))).toContain('256');const bootstrap=vi.fn(()=>fakeGame),rootSeed=vi.fn(()=>1);expect(()=>createProductionUkNewGame({mode:'adult',name:'😀'.repeat(257),genderLabel:''},{bootstrap,rootSeed})).toThrow(NewGameInputError);expect(bootstrap).not.toHaveBeenCalled();expect(rootSeed).not.toHaveBeenCalled();});
 it('generates one uint32 seed per valid submission and none for invalid input',()=>{const valid=call({mode:'adult'});expect(valid.rootSeed).toHaveBeenCalledTimes(1);expect(valid.request.rootSeed).toBe(73);const bootstrap=vi.fn(()=>fakeGame),rootSeed=vi.fn(()=>9);expect(()=>createProductionUkNewGame({mode:'adult',name:'x'.repeat(257),genderLabel:''},{bootstrap,rootSeed})).toThrow();expect(rootSeed).not.toHaveBeenCalled();expect(bootstrap).not.toHaveBeenCalled();expect(()=>createProductionUkNewGame({mode:'adult',name:'',genderLabel:'',country:'ca'} as never,{bootstrap,rootSeed})).toThrow(NewGameInputError);expect(bootstrap).not.toHaveBeenCalled();});
 it('surfaces bootstrap failure without mutating existing application state',()=>{const current={id:'existing'},rootSeed=vi.fn(()=>4),bootstrap=vi.fn(()=>{throw Error('internal package detail');});expect(()=>createProductionUkNewGame({mode:'childhood',name:'',genderLabel:''},{rootSeed,bootstrap})).toThrow('internal package detail');expect(current).toEqual({id:'existing'});expect(rootSeed).toHaveBeenCalledTimes(1);expect(bootstrap).toHaveBeenCalledTimes(1);});
 it('uses secure platform randomness as one exact uint32 draw',()=>{const getRandomValues=vi.fn((value:Uint32Array)=>{value[0]=0xffffffff;return value;}),original=globalThis.crypto;Object.defineProperty(globalThis,'crypto',{configurable:true,value:{getRandomValues}});try{expect(platformRootSeed()).toBe(0xffffffff);expect(getRandomValues).toHaveBeenCalledTimes(1);expect(getRandomValues.mock.calls[0][0]).toHaveLength(1);}finally{Object.defineProperty(globalThis,'crypto',{configurable:true,value:original});}});
 it('persists the returned canonical game through the standard pipeline and reloads person:1 unchanged',()=>{const game=createProductionUkNewGame({mode:'adult',name:'',genderLabel:''},{rootSeed:()=>73,bootstrap:createUkMid2024Game}),values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);}};expect(saveGame(storage,game)).toBeNull();const loaded=loadGame(storage).game!;expect(loaded).toEqual(game);expect(loaded.people?.playerId).toBe('person:1');expect(loaded.people?.nextSequence).toBe(2);expect(JSON.stringify(loaded)).not.toContain('human-content.uk.mid-2024-v1');});
 it('keeps LifeApp on the UI wrapper and leaves legacy constructors outside production submission',()=>{const sources=import.meta.glob<string>(['./LifeApp.tsx','./newGame.ts'],{eager:true,query:'?raw',import:'default'}),app=Object.entries(sources).find(([path])=>path.endsWith('/LifeApp.tsx'))![1],wrapper=Object.entries(sources).find(([path])=>path.endsWith('/newGame.ts'))![1];expect(app).toContain('createProductionUkNewGame');expect(app).not.toMatch(/\bcreateGame\b|\badultStart\b/);expect(wrapper).toContain('createUkMid2024Game');expect(wrapper).not.toMatch(/dateOfBirth|populationPackageId|humanContentPackageId|humanProfileId/);});
});
