import { useEffect, useRef, useState } from 'react';
import { townLenses, townPolicies, townShocks, type PolicyId, type LensId } from '../data/town';
import { advanceTown, createTown, policyReason, townTotal, townVoice, type Town } from '../engine/town';
import { readTown, validTown, writeTown } from '../engine/townSave';
const pounds=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
function initialSave(){try{return readTown(localStorage);}catch{return {town:null,error:'Storage is unavailable. You can still start an experiment and export backups.'};}}
const policyName=(id:string)=>townPolicies.find(p=>p.id===id)?.name??id;
export function TownApp(){
  const [initial]=useState(initialSave);const [town,setTown]=useState<Town|null>(initial.town);
  const [message,setMessage]=useState(initial.error??'');const [tab,setTab]=useState('People');const [policy,setPolicy]=useState<PolicyId>('hold');
  const [reset,setReset]=useState(false);const [saved,setSaved]=useState(false);const fileInput=useRef<HTMLInputElement>(null);
  const policyPanel=useRef<HTMLElement>(null);const reportPanel=useRef<HTMLDivElement>(null);
  const scrollTo=(target:HTMLElement|null)=>target?.scrollIntoView({behavior:'smooth',block:'start'});
  const advance=()=>{setTown(g=>g?advanceTown(g,policy):g);setTab('Consequences');setMessage('');requestAnimationFrame(()=>scrollTo(reportPanel.current));};
  useEffect(()=>{if(!town)return;try{const error=writeTown(localStorage,town);setSaved(!error);if(error)setMessage(error);}catch{setSaved(false);setMessage('Saving is unavailable. Export a backup before closing.');}},[town]);
  function exportSave(){if(!town)return;const url=URL.createObjectURL(new Blob([JSON.stringify(town,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`mereford-month-${town.month}.json`;a.click();URL.revokeObjectURL(url);setMessage('Backup exported. Keep this file to restore this experiment.');}
  async function importSave(file:File|undefined){if(!file)return;try{if(file.size>2_000_000)throw Error();const data:unknown=JSON.parse(await file.text());if(!validTown(data))throw Error();setPendingImport(data);setMessage('Backup checked. Confirm below to replace only the town experiment.');}catch{setMessage('This file is not a valid town backup. Your existing saves were not changed.');}finally{if(fileInput.current)fileInput.current.value='';}}
  const [pendingImport,setPendingImport]=useState<Town|null>(null);
  const latest=town?.history.at(-1);const lens=townLenses.find(l=>l.id===town?.lens)??townLenses[0];
  const nextShock=town?[...townShocks].reverse().find(s=>s.month<=Math.min(24,town.month+1))!:townShocks[0];
  const start=()=>{setTown(createTown());setReset(false);setMessage('A new town experiment has begun. Your life save is unchanged.');setPolicy('hold');setTab('People');};
  return <div className="town-shell">
    <header className="town-header"><a href="#town" className="town-wordmark">Mereford<span>A TOWN. MANY LIVES.</span></a><div className="town-tools"><span className="town-save">{saved?'● Town saved':'○ Local experiment'}</span>{town&&<button className="quiet" onClick={exportSave}>Export backup</button>}<button className="quiet" onClick={()=>fileInput.current?.click()}>Restore backup</button>{town&&<button className="quiet" onClick={()=>setReset(true)}>New experiment</button>}<input ref={fileInput} type="file" accept="application/json,.json" hidden onChange={e=>void importSave(e.target.files?.[0])}/></div></header>
    {message&&<div className="notice" role="status">{message}<button className="quiet" onClick={()=>setMessage('')}>Dismiss</button></div>}
    {pendingImport&&<section className="town-confirm" role="alert"><p>Restore month {pendingImport.month}? This replaces the town save. Your life save stays unchanged.</p><button onClick={()=>{setTown(pendingImport);setPendingImport(null);setPolicy('hold');setMessage('Town backup restored.');}}>Restore this town</button><button onClick={()=>setPendingImport(null)}>Cancel restore</button></section>}
    {reset&&<section className="town-confirm" role="alert"><p>Start over? Export a backup first if you want to keep this town. Your life save stays unchanged.</p><button onClick={start}>Start a new town</button><button onClick={()=>setReset(false)}>Keep this town</button></section>}
    {!town?<main className="town-welcome"><div className="eyebrow">POLITICAL ECONOMY · FIRST PLAYABLE CHAPTER</div><h1>Behind every number,<br/><em>someone’s life.</em></h1><p>Eight hundred households. Two employers. Twenty-four months to discover what your decisions change—and what they leave untouched.</p><div className="town-welcome-grid"><div><b>Follow the money</b><p>Wages, rents, bills and grants move between real accounts in the simulation.</p></div><div><b>Choose your commitments</b><p>Relieve hardship, support employment or invest in warmer homes.</p></div><div><b>Question the outcome</b><p>Read people’s experiences alongside competing philosophical questions.</p></div></div><button className="primary" onClick={start}>{initial.error?'Replace town save and begin':'Begin the Mereford experiment'} <span>→</span></button><p className="fine">A fictional British town and an economic experiment, not a calibrated model of the UK. This mode has a separate save and does not advance your character’s age.</p></main>:<main>
      <section className="town-hero"><div><div className="eyebrow">THE MEREFORD EXPERIMENT</div><h1>{town.month===24?'What did your choices leave behind?':'A place worth understanding.'}</h1><p>Town laboratory · fictional UK setting · 800 households</p></div><div className="month-counter"><strong>{String(town.month).padStart(2,'0')}</strong><span>OF 24<br/>MONTHS</span></div></section>
      <div className="town-progress" role="progressbar" aria-label="Experiment progress" aria-valuenow={town.month} aria-valuemin={0} aria-valuemax={24}><span style={{width:`${town.month/24*100}%`}}/></div>
      <section className="town-metrics" aria-label="Town indicators"><div><small>PROGRAMME FUND</small><strong>{pounds(town.fund)}</strong><span>Available for commitments</span></div><div><small>EMPLOYMENT</small><strong>{town.employers.reduce((s,f)=>s+f.jobs,0)} <em>/ 480</em></strong><span>Jobs across two employers</span></div><div><small>ENERGY PRICE</small><strong>{Math.round(town.energy*100)} <em>/ 100</em></strong><span>Index against opening prices</span></div><div><small>UNMET ESSENTIALS</small><strong>{pounds(latest?.unmet??0)}</strong><span>Across all households this month</span></div></section>
      <div className="town-columns"><section className="town-main">
        {town.month===24?<section className="town-result"><div className="eyebrow">THE EXPERIMENT IS COMPLETE</div><h2>There is more than one way to judge a town.</h2><p>Average wellbeing moved from 68.8 to {latest!.wellbeing.toFixed(1)}. Your fund holds {pounds(town.fund)}. Insulated homes use {Math.round(town.insulation*100)}% less energy.</p><p>{town.projects.length>0?`${town.projects.length} contracted project(s) mature after this experiment. Their costs are paid, but their future benefits are not included here.`:'All commissioned projects have matured.'}</p><p className="fine">Compare household outcomes below. A large fund, healthy employer reserves and secure households are different achievements.</p><button className="quiet outlined" onClick={exportSave}>Keep this experiment</button><button className="quiet outlined" onClick={()=>setReset(true)}>Try a different approach</button></section>:<section className="town-brief"><div className="eyebrow">BRIEFING FOR MONTH {town.month+1}</div><h2>{nextShock.title}</h2><p>{nextShock.body}</p><small>Scenario conditions are announced before you commit. Small seeded fluctuations vary the exact prices and orders.</small></section>}
        <nav className="tabs" aria-label="Town views">{['People','Employers','Consequences','Accounts','Ideas'].map(item=><button key={item} aria-current={tab===item?'page':undefined} onClick={()=>setTab(item)}>{item}</button>)}</nav>
        <div className="town-tab" ref={reportPanel}>
        {tab==='People'&&<><div className="section-label"><h3>The town, at kitchen-table level</h3><span>GROUP AVERAGES</span></div><p className="fine">Each voice represents a household group. People within a group are simplified into averages in this first model.</p><div className="household-grid">{town.households.map(h=><article className="household-card" key={h.id}><div className="household-heading"><span className="mini-avatar">{h.person[0]}</span><div><h3>{h.person}</h3><small>{h.name} · {h.count} households</small></div></div><blockquote>{townVoice(town,h)}</blockquote><dl><div><dt>Cash per household</dt><dd>{pounds(h.cash/h.count)}</dd></div><div><dt>Monthly income</dt><dd>{pounds(h.income/h.count)}</dd></div><div><dt>Monthly spending</dt><dd>{pounds(h.outgoings/h.count)}</dd></div><div><dt>Essentials unpaid</dt><dd className={h.unmet>0?'negative':''}>{pounds(h.unmet/h.count)}</dd></div></dl><label className="wellbeing">Wellbeing <b>{Math.round(h.wellbeing)}/100</b><meter min={0} max={100} value={h.wellbeing}/></label></article>)}</div></>}
        {tab==='Employers'&&<><h3>Work depends on more than ambition.</h3><p className="muted">Outside orders, local spending, energy and cash reserves influence payroll. These employers retain their surplus; ownership transitions come in a later milestone.</p>{town.employers.map(f=><article className="employer-card" key={f.id}><h3>{f.name}</h3><div className="employer-stats"><div><small>JOBS</small><strong>{f.jobs}/{f.capacity}</strong></div><div><small>MONTHLY WAGE</small><strong>{pounds(f.wage)}</strong></div><div><small>CASH RESERVE</small><strong>{pounds(f.cash)}</strong></div><div><small>OPERATING CASH CHANGE</small><strong>{pounds(f.profit)}</strong></div></div><p className="fine">Operating cash change excludes programme grants. Hiring reacts to previous local sales and current external orders; it is not an economic forecast.</p></article>)}</>}
        {tab==='Consequences'&&<><h3>What changed, and why?</h3>{!latest&&<p className="muted">Advance a month to see the first consequences. Every completed month keeps its own explanation.</p>}{[...town.history].reverse().map(report=><details className="month-report" key={report.month} open={report.month===town.month}><summary>Month {report.month} · {policyName(report.policy)}<span>{report.jobs} jobs · wellbeing {report.wellbeing.toFixed(1)}</span></summary><ul>{report.notes.map((note,i)=><li key={i}>{note}</li>)}</ul><div className="report-groups">{report.groups.map(g=><p key={g.id}><b>{town.households.find(h=>h.id===g.id)!.name}</b>: {pounds(g.cash/town.households.find(h=>h.id===g.id)!.count)} cash per household · wellbeing {Math.round(g.wellbeing)}</p>)}</div></details>)}</>}
        {tab==='Accounts'&&<><h3>Every payment has another side.</h3><div className="account-check"><b>{Math.abs(townTotal(town)-town.initialTotal)<.05?'✓ All accounts balance':'Account imbalance detected'}</b><p>Opening total: {pounds(town.initialTotal)} · Current total: {pounds(townTotal(town))}</p></div><p className="muted">The outside account ({pounds(town.outside)}) records the other side of grants, imports, pensions and external sales. It is a balancing account for the wider economy, not a claim that the UK has this much cash or debt. Local accounts cannot spend cash they do not have.</p><div className="ledger"><div><span>Monthly programme grant</span><strong>£110,000</strong></div><div><span>Baseline services</span><strong>£80,000</strong></div><div><span>Insulation projects in progress</span><strong>{town.projects.length}</strong></div></div><h3>Month {town.month} transactions</h3><div className="transaction-list">{town.ledger.filter(x=>x.month===town.month).map((x,i)=><div key={i}><span><b>{x.reason}</b><small>{x.from} → {x.to}</small></span><strong>{pounds(x.amount)}</strong></div>)}</div><p className="fine">Unpaid essentials measure hardship and do not silently become loans. Credit, taxation, production inventories and national public finance are later additions.</p></>}
        {tab==='Ideas'&&<><h3>What does a good outcome mean?</h3><p className="muted">These lenses change the questions you ask, not the underlying rules or outcomes.</p><label className="town-label">Your analytical lens<select value={town.lens} onChange={e=>setTown({...town,lens:e.target.value as LensId})}>{townLenses.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><div className="philosophy-card"><div className="eyebrow">{lens.name}</div><h2>{lens.question}</h2><p>{lens.text}</p><a href={lens.source} target="_blank" rel="noreferrer">Read the source ↗</a></div><label className="town-label">Your guiding commitment<select value={town.pledge} onChange={e=>setTown({...town,pledge:e.target.value as Town['pledge']})}><option value="care">Keep households secure</option><option value="work">Protect the ability to earn a living</option><option value="future">Build lasting resilience</option></select></label><p className="muted">Your current commitment is a reflection prompt, not a score bonus. Ask whether your decisions uphold it when circumstances change.</p><details className="month-report"><summary>What this model assumes</summary><ul><li>Fictional starting amounts, fixed rents and wages, two aggregated employers and four household groups.</li><li>Monthly policy costs are one-off commitments. Only completed insulation has a persistent direct effect.</li><li>Energy and outside orders follow a published scenario with small deterministic variation.</li><li>Employers use a simplified cash-and-demand rule, not a full production model.</li><li>Wellbeing responds to cash buffers, unmet essentials and energy pressure. It is a game measure.</li><li>There are no elections, ideological party bonuses, national taxes, revolution mechanics or live news imports yet.</li></ul></details></>}
        </div>
      </section><aside className="town-policy" ref={policyPanel}><div className="eyebrow">YOUR NEXT COMMITMENT</div><h2>{town.month===24?'Time to reflect.':'What matters this month?'}</h2><p>Each choice is funded from the programme reserve. The monthly £30,000 net grant arrives after your commitment.</p><fieldset disabled={town.month>=24}><legend>Choose a policy</legend>{townPolicies.map(p=>{const reason=policyReason(town,p.id);return <label className={`policy-option ${policy===p.id?'selected':''}`} key={p.id}><span><input type="radio" name="policy" checked={policy===p.id} disabled={!!reason} onChange={()=>setPolicy(p.id)}/><b>{p.name}</b><strong>{pounds(p.cost)}</strong></span><small>{p.description}</small>{reason&&<em>{reason}</em>}</label>;})}</fieldset><p className="policy-reflection">{townPolicies.find(p=>p.id===policy)!.lens}</p><button className="primary" disabled={!!policyReason(town,policy)} onClick={advance}>Advance one month <span>→</span></button>{policyReason(town,policy)&&<p className="fine">{policyReason(town,policy)}</p>}<div className="town-commitment"><small>YOUR GUIDING COMMITMENT</small><p>{town.pledge==='care'?'Keep households secure.':town.pledge==='work'?'Protect the ability to earn a living.':'Build lasting resilience.'}</p><button className="quiet" onClick={()=>{setTab('Ideas');requestAnimationFrame(()=>scrollTo(reportPanel.current));}}>Examine your ideas ↗</button></div></aside></div>
      {town.month<24&&<div className="town-mobile-dock"><span>MONTH {town.month+1}<small>{pounds(town.fund)} in reserve</small></span><button onClick={()=>scrollTo(policyPanel.current)}>Choose this month’s policy ↓</button></div>}
    </main>}
    <footer>TURNING PAGES · MEREFORD <span>Fictional scenario · Separate local save · Model v1</span></footer>
  </div>;
}
