import {describe,expect,it} from 'vitest';
import {instantiateInitialPlayerFromCohort} from './initialPopulation';
import {deriveCountryPopulation,instantiateFromCohort,populationCohortId,type PopulationState} from './population';

const profile={version:1 as const,id:'profile.synthetic.initial-v1',naming:{givenNames:[{id:'name.given.initial-v1',text:'Initial',weight:1}],familyNames:[{id:'name.family.player-v1',text:'Player',weight:1}]},genderLabels:[{id:'gender.unspecified-v1',label:'Unspecified',weight:1}],temperament:[],aptitudes:[],traits:[]};
const cohort=(count:number)=>({countryId:'xy',areaId:'place.xy.synthetic.small-v1',birthYear:2000,generationProfileId:profile.id,count});
const state=(count:number):PopulationState=>{const value=cohort(count);return {version:1,coverage:[{countryId:'xy',status:'complete',source:'population.synthetic.initial-v1',areaPartitionId:'geography.xy.synthetic-v1'}],cohorts:[{id:populationCohortId(value),...value}],memberships:[]};};
const personInput={name:'Initial Player',dateOfBirth:{year:2000,month:6,day:30},genderLabel:'Unspecified',lifeStatus:'living' as const,traits:[],temperament:{},aptitudes:{}};

describe('initial cohort player composition',()=>{
 it('atomically transfers one cohort unit into person:1 using canonical receipt semantics',()=>{const original=state(2),id=original.cohorts[0].id,result=instantiateInitialPlayerFromCohort({population:original,cohortId:id,requestKey:'country-start.synthetic.initial-v1',personInput});expect(original.cohorts[0].count).toBe(2);expect(result.people).toMatchObject({playerId:'person:1',nextSequence:2});expect(result.population.cohorts[0].count).toBe(1);expect(result.population.memberships).toEqual([{personId:'person:1',countryId:'xy',areaId:'place.xy.synthetic.small-v1',origin:{kind:'cohort',cohortId:id,requestKey:'country-start.synthetic.initial-v1',requestIndex:0}}]);expect(deriveCountryPopulation(result.population,result.people,'xy')).toEqual({knownLiving:2,complete:true});
  const retry=instantiateFromCohort({people:result.people,population:result.population,rootSeed:1,cohortId:id,requestKey:'country-start.synthetic.initial-v1',count:1,referenceDate:{year:2024,month:6,day:30},profile});expect(retry.reused).toBe(true);expect(retry.persons).toEqual([result.person]);expect(retry.people).toEqual(result.people);expect(retry.population).toEqual(result.population);});
 it('removes a cohort at zero and fails without mutating the original state',()=>{const original=state(1),id=original.cohorts[0].id,result=instantiateInitialPlayerFromCohort({population:original,cohortId:id,requestKey:'country-start.synthetic.zero-v1',personInput});expect(result.population.cohorts).toEqual([]);expect(deriveCountryPopulation(result.population,result.people,'xy').knownLiving).toBe(1);expect(()=>instantiateInitialPlayerFromCohort({population:original,cohortId:'population-cohort:v1|bad',requestKey:'country-start.synthetic.failure-v1',personInput})).toThrow();expect(original.cohorts[0].count).toBe(1);expect(original.memberships).toEqual([]);});
 it('rejects Person/cohort birth-year disagreement without consuming the cohort',()=>{const original=state(2),before=structuredClone(original);expect(()=>instantiateInitialPlayerFromCohort({population:original,cohortId:original.cohorts[0].id,requestKey:'country-start.synthetic.birth-year-mismatch-v1',personInput:{...personInput,dateOfBirth:{year:1999,month:12,day:31}}})).toThrow('Invalid cohort membership receipt.');expect(original).toEqual(before);expect(original.memberships).toEqual([]);});
});
