import {describe,expect,it} from 'vitest';
import {adultStart,createGame} from '../../game';
import {createRandomness} from '../../core/rng';
import {serializeGame} from '../../save';
import type {Game} from '../../types';
import {createPeople} from '../person';
import {createPlayerPopulation,deriveCountryPopulation,validPopulationWithPeople} from '../population';
import {addRational,allocateLargestRemainder,parseExactDecimal,rational} from './arithmetic';
import {compilePopulationCalibration,renderPopulationCalibrationReport} from './compiler';
import {initializePopulationFromCalibration} from './integration';
import {fingerprintPopulationCalibrationPackage,validateCalibrationRegistry,validatePopulationCalibrationPackage,withCalibrationFingerprint} from './package';
import type {EvidenceClassification,PopulationCalibrationPackageV1,PopulationMeasureV1} from './types';

const date={year:2030,month:1,day:1} as const;
const source={version:1 as const,id:'source.synthetic-v1',organisation:'Synthetic Institute',datasetId:'synthetic-table',releaseId:'release-v1',title:'Synthetic population evidence',referencePeriod:{from:date,through:date},jurisdiction:'synthetic',publicationStatus:'final' as const,methodologyNote:'Synthetic evidence used only to test calibration mechanics.'};
const universe={id:'universe.resident-v1',description:'Synthetic exhaustive resident population.',exhaustive:true};
const measure=(id:string,value:string,dimensions:PopulationMeasureV1['dimensions'],classification:EvidenceClassification='observed',extra:Partial<PopulationMeasureV1>={}):PopulationMeasureV1=>({version:1,id,sourceId:source.id,series:id,semantic:'population-count',unit:'persons',referenceDate:date,universeId:universe.id,classification,dimensions,value,...extra});
function directPackage(overrides:Partial<Omit<PopulationCalibrationPackageV1,'fingerprint'>>={}):PopulationCalibrationPackageV1{
 const total=measure('measure.total','10',{kind:'total'}),year2000=measure('measure.birth-2000','4',{kind:'birth-year',birthYear:2000}),year2001=measure('measure.birth-2001','6',{kind:'birth-year',birthYear:2001});
 return withCalibrationFingerprint({schemaVersion:1,methodologyId:'population-calibration.method-v1',id:'calibration.synthetic-direct-v1',countryId:'synthetic',effectiveDate:date,coverageIntent:'complete',partition:{areaPartitionId:null,birthYearFrom:2000,birthYearThrough:2001},universes:[universe],sources:[source],measures:[total,year2000,year2001],derivedTotals:[],authority:{kind:'measure',id:total.id},distributionMeasureIds:[year2000.id,year2001.id],reconciliation:{kind:'exact'},ageConversion:{kind:'direct-birth-year'},generationProfileBindings:[{fromBirthYear:2000,throughBirthYear:2001,generationProfileId:'human.synthetic-v1'}],gaps:[],...overrides});
}
const compile=(pkg:PopulationCalibrationPackageV1,livingMemberships:readonly {birthYear:number;areaId:null;count:number}[]=[])=>compilePopulationCalibration(pkg,{profileExists:id=>id==='human.synthetic-v1',livingMemberships});

describe('exact demographic calibration arithmetic',()=>{
 it('parses canonical decimals exactly and rejects noncanonical or hostile magnitudes',()=>{expect(parseExactDecimal('12.34')).toEqual({numerator:617n,denominator:50n});expect(addRational(parseExactDecimal('0.1'),parseExactDecimal('0.2'))).toEqual({numerator:3n,denominator:10n});for(const value of ['-1','-0','00','01','1.0','1.230','1e3','NaN','Infinity'])expect(()=>parseExactDecimal(value)).toThrow();expect(()=>parseExactDecimal(`1${'0'.repeat(30)}`)).toThrow('precision');expect(()=>rational(1n,0n)).toThrow();});
 it('uses exact deterministic input-order-independent largest remainder allocation',()=>{const weights=[{id:'cell.d',weight:rational(1n)},{id:'cell.b',weight:rational(1n)},{id:'cell.a',weight:rational(1n)},{id:'cell.c',weight:rational(1n)}];expect(allocateLargestRemainder(7,weights)).toEqual(allocateLargestRemainder(7,[...weights].reverse()));expect(allocateLargestRemainder(7,weights).allocations).toEqual([{id:'cell.a',count:2},{id:'cell.b',count:2},{id:'cell.c',count:2},{id:'cell.d',count:1}]);expect(allocateLargestRemainder(7,weights).residualAssignments).toEqual(['cell.a','cell.b','cell.c']);expect(()=>allocateLargestRemainder(1,[{id:'x',weight:rational(0n)}])).toThrow('positive total weight');expect(()=>rational(-1n)).toThrow();expect(()=>allocateLargestRemainder(Number.MAX_SAFE_INTEGER,[{id:'a',weight:rational(1n)},{id:'b',weight:rational(1n)}])).not.toThrow();let accessed=false;const hostile:unknown[]=[];Object.defineProperty(hostile,0,{enumerable:true,get(){accessed=true;throw Error('hostile');}});hostile.length=1;expect(()=>allocateLargestRemainder(1,hostile as never)).toThrow('Invalid allocation weight');expect(accessed).toBe(false);});
});

describe('calibration packages and immutable identity',()=>{
 it('strictly validates provenance, classifications, versioned IDs and references',()=>{const pkg=directPackage();expect(validatePopulationCalibrationPackage(pkg)).toBe(true);for(const classification of ['observed','estimated','assumed','projected'] as const){const changed=directPackage({measures:pkg.measures.map(item=>item.id==='measure.birth-2000'?{...item,classification}:item)});expect(validatePopulationCalibrationPackage(changed)).toBe(true);}expect(validatePopulationCalibrationPackage({...pkg,sources:[{...source,publicationStatus:'draft'}]})).toBe(false);expect(validatePopulationCalibrationPackage({...pkg,extra:true})).toBe(false);expect(validatePopulationCalibrationPackage({...pkg,id:'calibration.synthetic'})).toBe(false);expect(()=>directPackage({id:'calibration.synthetic-dangling-v1',measures:pkg.measures.map(item=>item.id==='measure.birth-2000'?{...item,sourceId:'source.missing-v1'}:item)})).toThrow('Invalid calibration package');});
 it('canonicalizes semantically unordered package arrays, excludes identity from its digest and detects changed semantics',()=>{const first=directPackage(),reordered=directPackage({sources:[...first.sources].reverse(),measures:[...first.measures].reverse(),distributionMeasureIds:[...first.distributionMeasureIds].reverse()}),reidentified=directPackage({id:'calibration.synthetic-reidentified-v1'});expect(first.fingerprint).toBe(reordered.fingerprint);expect(first.fingerprint).toBe(reidentified.fingerprint);const changed=directPackage({partition:{...first.partition,birthYearFrom:1999}});expect(changed.fingerprint).not.toBe(first.fingerprint);expect(fingerprintPopulationCalibrationPackage(first)).toBe(first.fingerprint);expect(validateCalibrationRegistry([first],{[first.id]:first.fingerprint})).toBe(true);expect(validateCalibrationRegistry([changed],{[first.id]:first.fingerprint})).toBe(false);const hostileManifest=Object.create(null);Object.defineProperty(hostileManifest,first.id,{enumerable:true,get(){throw Error('hostile');}});expect(validateCalibrationRegistry([first],hostileManifest)).toBe(false);});
 it('rejects future living birth-year partitions',()=>{expect(()=>directPackage({id:'calibration.synthetic-future-v1',partition:{areaPartitionId:null,birthYearFrom:2031,birthYearThrough:2031},generationProfileBindings:[{fromBirthYear:2031,throughBirthYear:2031,generationProfileId:'human.synthetic-v1'}]})).toThrow('Invalid calibration package');});
 it('accepts pre-1900 evidence within the shared Gregorian range and rejects unsupported years',()=>{
  const total=measure('measure.historical-total','3',{kind:'total'}),cell=measure('measure.birth-1899','3',{kind:'birth-year',birthYear:1899}),pkg=directPackage({id:'calibration.synthetic-historical-v1',partition:{areaPartitionId:null,birthYearFrom:1899,birthYearThrough:1899},measures:[total,cell],authority:{kind:'measure',id:total.id},distributionMeasureIds:[cell.id],generationProfileBindings:[{fromBirthYear:1899,throughBirthYear:1899,generationProfileId:'human.synthetic-v1'}]});
  const result=compile(pkg);expect(result.coverage).toBe('complete');expect(result.cohorts.map(item=>[item.birthYear,item.count])).toEqual([[1899,3]]);
  expect(()=>directPackage({id:'calibration.synthetic-year-zero-v1',partition:{areaPartitionId:null,birthYearFrom:0,birthYearThrough:1}})).toThrow('Invalid calibration package');
  expect(()=>directPackage({id:'calibration.synthetic-year-overflow-v1',partition:{areaPartitionId:null,birthYearFrom:2000,birthYearThrough:10000}})).toThrow('Invalid calibration package');
 });
 it('fails safely for hostile package structures',()=>{const pkg=directPackage(),sparse=[...pkg.measures];delete sparse[0];expect(validatePopulationCalibrationPackage({...pkg,measures:sparse})).toBe(false);let accessed=false;const validationAccessor={...pkg};Object.defineProperty(validationAccessor,'countryId',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validatePopulationCalibrationPackage(validationAccessor)).toBe(false);const constructionAccessor={...pkg};delete (constructionAccessor as {fingerprint?:string}).fingerprint;Object.defineProperty(constructionAccessor,'countryId',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(()=>withCalibrationFingerprint(constructionAccessor as never)).toThrow('Invalid calibration package');expect(accessed).toBe(false);const revoked=Proxy.revocable(pkg,{});revoked.revoke();expect(validatePopulationCalibrationPackage(revoked.proxy)).toBe(false);expect(()=>fingerprintPopulationCalibrationPackage(revoked.proxy)).toThrow('Cannot fingerprint an invalid calibration package');});
});

describe('calibration compilation',()=>{
 it('compiles direct birth-year evidence and preserves exact totals',()=>{const result=compile(directPackage());expect(result.coverage).toBe('complete');expect(result.cohorts.map(item=>[item.birthYear,item.count])).toEqual([[2000,4],[2001,6]]);expect(result.report.finalCohortSum).toBe(10);expect(result.report.precision.every(item=>item.resolution==='direct-resolution')).toBe(true);});
 it('allocates completed ages uniformly by exact Gregorian day, including leap day',()=>{
  const effective={year:2024,month:2,day:29} as const,total=measure('measure.total','366',{kind:'total'},'estimated'),band={...measure('measure.age-0','366',{kind:'completed-age-band',minimumAge:0,maximumAge:0}),referenceDate:effective};
  const pkg=directPackage({id:'calibration.synthetic-age-v1',effectiveDate:effective,partition:{areaPartitionId:null,birthYearFrom:2023,birthYearThrough:2024},sources:[{...source,referencePeriod:{from:effective,through:effective}}],measures:[{...total,referenceDate:effective},band],authority:{kind:'measure',id:total.id},distributionMeasureIds:[band.id],ageConversion:{kind:'uniform-birthday-by-day'},generationProfileBindings:[{fromBirthYear:2023,throughBirthYear:2024,generationProfileId:'human.synthetic-v1'}],reconciliation:{kind:'exact'}});
  const result=compile(pkg);expect(result.cohorts.map(item=>[item.birthYear,item.count])).toEqual([[2023,306],[2024,60]]);expect(result.report.precision.every(item=>item.resolution==='calibrated-from-broader-evidence')).toBe(true);expect(result.report.transformations[0]).toContain('Gregorian birth day');
 });
 it('preserves both broad-band and rounded-source precision limitations',()=>{const effective={year:2024,month:2,day:29} as const,total={...measure('measure.total','366',{kind:'total'},'estimated'),referenceDate:effective},band={...measure('measure.age-rounded','0.366',{kind:'completed-age-band',minimumAge:0,maximumAge:0},'estimated',{unit:'thousand-persons',roundingNote:'Rounded synthetic evidence.'}),referenceDate:effective},pkg=directPackage({id:'calibration.synthetic-rounded-band-v1',effectiveDate:effective,partition:{areaPartitionId:null,birthYearFrom:2023,birthYearThrough:2024},sources:[{...source,referencePeriod:{from:effective,through:effective}}],measures:[total,band],authority:{kind:'measure',id:total.id},distributionMeasureIds:[band.id],ageConversion:{kind:'uniform-birthday-by-day'},generationProfileBindings:[{fromBirthYear:2023,throughBirthYear:2024,generationProfileId:'human.synthetic-v1'}]}),result=compile(pkg);expect(result.report.precision.every(item=>item.resolution==='calibrated-from-broader-rounded-evidence')).toBe(true);expect(result.report.inputs.find(item=>item.id===band.id)?.resolutionNote).toContain('Broader completed-age');expect(result.report.inputs.find(item=>item.id===band.id)?.resolutionNote).toContain('rounded');});
 it('blocks complete coverage for an unsupported open-ended band without fabricating a tail',()=>{const base=directPackage(),open=measure('measure.age-open','10',{kind:'completed-age-band',minimumAge:0,maximumAge:null});const pkg=directPackage({id:'calibration.synthetic-open-v1',measures:[base.measures[0],open],distributionMeasureIds:[open.id],ageConversion:{kind:'uniform-birthday-by-day'}});const result=compile(pkg);expect(result.coverage).toBe('partial');expect(result.report.unsupportedCategories).toEqual(['open-ended-age-band']);expect(result.report.completenessDenialReasons.join(' ')).toContain('Open-ended');});
 it('does not redistribute an unsupported open tail into supported closed cells',()=>{const base=directPackage(),open=measure('measure.age-open-mixed','6',{kind:'completed-age-band',minimumAge:0,maximumAge:null}),pkg=directPackage({id:'calibration.synthetic-open-mixed-v1',measures:[base.measures[0],base.measures[1],open],distributionMeasureIds:[base.measures[1].id,open.id],ageConversion:{kind:'uniform-birthday-by-day'}}),result=compile(pkg);expect(result.coverage).toBe('partial');expect(result.report.finalCohortSum).toBe(4);expect(result.cohorts).toHaveLength(1);expect(result.report.transformations).not.toContain('Scaled distribution to authoritative total using proportional largest remainder.');});
 it('reconciles within tolerance, reports rounded precision and rejects larger conflicts or universe mismatch',()=>{const base=directPackage(),rounded={...base.measures[1],value:'0.004',unit:'thousand-persons' as const,roundingNote:'Published to the nearest thousand.'},other={...base.measures[2],value:'5'};const within=directPackage({id:'calibration.synthetic-reconciled-v1',measures:[base.measures[0],rounded,other],reconciliation:{kind:'proportional-largest-remainder',maximumDiscrepancyBasisPoints:1100}});const result=compile(within);expect(result.report.absoluteDiscrepancy).toBe('1');expect(result.report.finalCohortSum).toBe(10);expect(result.report.precision.some(item=>item.resolution==='canonical-exact-from-rounded-source')).toBe(true);expect(()=>compile(directPackage({id:'calibration.synthetic-conflict-v1',measures:[base.measures[0],rounded,{...other,value:'1'}],reconciliation:{kind:'proportional-largest-remainder',maximumDiscrepancyBasisPoints:100}}))).toThrow('threshold');const otherUniverse={id:'universe.other-v1',description:'Other universe',exhaustive:true};expect(()=>compile(directPackage({id:'calibration.synthetic-universe-v1',universes:[universe,otherUniverse],measures:base.measures.map(item=>item.id==='measure.birth-2001'?{...item,universeId:otherUniverse.id}:item)}))).toThrow('universes differ');});
 it('supports exact percentage weights and rejects temporal substitution or unsafe totals',()=>{const base=directPackage(),shares=directPackage({id:'calibration.synthetic-shares-v1',measures:[base.measures[0],{...base.measures[1],semantic:'population-share',unit:'percent',value:'40'},{...base.measures[2],semantic:'population-share',unit:'percent',value:'60'}]});expect(compile(shares).cohorts.map(item=>item.count)).toEqual([4,6]);const wrongDate={...base.measures[1],referenceDate:{year:2029,month:12,day:31}},broadSource={...source,referencePeriod:{from:{year:2029,month:1,day:1},through:date}};expect(()=>compile(directPackage({id:'calibration.synthetic-wrong-date-v1',sources:[broadSource],measures:[base.measures[0],wrongDate,base.measures[2]]}))).toThrow('reference date');const unsafe={...base.measures[0],value:'9007199254740992'};expect(()=>compile(directPackage({id:'calibration.synthetic-overflow-v1',measures:[unsafe,...base.measures.slice(1)]}))).toThrow('safe integer');});
 it('enforces the completeness lineage rule while allowing disclosed within-total assumptions',()=>{
  const base=directPackage(),assumedTotal=directPackage({id:'calibration.synthetic-assumed-total-v1',measures:base.measures.map(item=>item.id==='measure.total'?{...item,classification:'assumed' as const}:item)});expect(compile(assumedTotal).coverage).toBe('partial');const projectedTotal=directPackage({id:'calibration.synthetic-projected-total-v1',measures:base.measures.map(item=>item.id==='measure.total'?{...item,classification:'projected' as const}:item)});expect(()=>compile(projectedTotal)).toThrow('Projected evidence');const projectedDistribution=directPackage({id:'calibration.synthetic-projected-distribution-v1',measures:base.measures.map(item=>item.id==='measure.birth-2000'?{...item,classification:'projected' as const}:item)});expect(()=>compile(projectedDistribution)).toThrow('Projected evidence');
  const assumedDistribution=directPackage({id:'calibration.synthetic-assumed-allocation-v1',measures:base.measures.map(item=>item.dimensions.kind==='total'?item:{...item,classification:'assumed' as const})});const allowed=compile(assumedDistribution);expect(allowed.coverage).toBe('complete');expect(allowed.report.assumptions).toEqual(['measure.birth-2000','measure.birth-2001']);
  const totalA=measure('measure.total-a','4',{kind:'total'},'observed'),totalB=measure('measure.total-b','6',{kind:'total'},'estimated'),derived=directPackage({id:'calibration.synthetic-derived-v1',measures:[totalA,totalB,...base.measures.slice(1)],derivedTotals:[{id:'derived.total',operation:'sum',inputIds:[totalA.id,totalB.id],universeId:universe.id}],authority:{kind:'derived',id:'derived.total'}});expect(compile(derived).coverage).toBe('complete');
 });
 it('separates demographic completeness from operational profile readiness while requiring structural bindings',()=>{const gap=directPackage({id:'calibration.synthetic-gap-v1',gaps:[{id:'gap.unknown-tail',description:'Unknown synthetic tail.',blocking:true}]});expect(compile(gap).coverage).toBe('partial');const unresolved=compilePopulationCalibration(directPackage(),{profileExists:()=>false});expect(unresolved.coverage).toBe('complete');expect(unresolved.generationReadiness).toBe('not-ready');expect(unresolved.cohorts).toHaveLength(2);expect(unresolved.report.generationReadinessDenialReasons).not.toHaveLength(0);const missing=directPackage({id:'calibration.synthetic-profile-gap-v1',generationProfileBindings:[{fromBirthYear:2000,throughBirthYear:2000,generationProfileId:'human.synthetic-v1'}]});expect(compile(missing).coverage).toBe('partial');const overlap=directPackage({id:'calibration.synthetic-profile-overlap-v1',generationProfileBindings:[{fromBirthYear:2000,throughBirthYear:2001,generationProfileId:'human.synthetic-v1'},{fromBirthYear:2001,throughBirthYear:2001,generationProfileId:'human.synthetic-v1'}]});expect(compile(overlap).coverage).toBe('partial');});
 it('renders one deterministic machine report without claiming source precision',()=>{const pkg=directPackage(),one=compile(pkg),two=compile(directPackage({measures:[...pkg.measures].reverse(),distributionMeasureIds:[...pkg.distributionMeasureIds].reverse()}));expect(one.report).toEqual(two.report);expect(renderPopulationCalibrationReport(one.report)).toBe(renderPopulationCalibrationReport(two.report));expect(renderPopulationCalibrationReport(one.report)).toContain('Direct single-birth-year evidence');});
 it('retains optional source provenance in the authoritative machine report',()=>{const pkg=directPackage({id:'calibration.synthetic-provenance-v1',sources:[{...source,bundledArtifact:'artifact.synthetic-v1',externalLocator:'https://example.invalid/synthetic',retrievedAt:date}]}),report=compile(pkg).report;expect(report.sources[0]).toMatchObject({bundledArtifact:'artifact.synthetic-v1',externalLocator:'https://example.invalid/synthetic',retrievedAt:date});});
 it('returns deeply immutable alias-safe packages and reports',()=>{const raw=directPackage(),result=compile(raw);expect(Object.isFrozen(raw.measures)).toBe(true);expect(Object.isFrozen(result.report.sources)).toBe(true);expect(Object.isFrozen(result.report.sources[0].referencePeriod)).toBe(true);expect(Object.isFrozen(result.report.gaps)).toBe(true);expect(()=>{(result.report.allocations as unknown as {count:number}[])[0].count=999;}).toThrow();expect(result.report.finalCohortSum).toBe(10);});
});

describe('frozen Population compatibility',()=>{
 it('reserves the player, initializes through Population v1, persists only package identity and round-trips a root-v3 game',()=>{
  const game=adultStart(createGame('Calibration Player','Woman','uk',19)) as Game,people=game.people!,startingPopulation=game.population!,now=game.clock!.date,birthYear=people.people[0].dateOfBirth.year,total=measure('measure.total','10',{kind:'total'}),cell=measure('measure.birth-player','10',{kind:'birth-year',birthYear});
  const pkg=directPackage({id:'calibration.synthetic-game-v1',countryId:'uk',effectiveDate:now,partition:{areaPartitionId:null,birthYearFrom:birthYear,birthYearThrough:birthYear},sources:[{...source,referencePeriod:{from:now,through:now}}],measures:[{...total,referenceDate:now,sourceId:source.id},{...cell,referenceDate:now,sourceId:source.id}],authority:{kind:'measure',id:total.id},distributionMeasureIds:[cell.id],generationProfileBindings:[{fromBirthYear:birthYear,throughBirthYear:birthYear,generationProfileId:'human.synthetic-v1'}]});
  const result=compile(pkg,[{birthYear,areaId:null,count:1}]),population=initializePopulationFromCalibration(startingPopulation,people,pkg,result,[{personId:people.playerId,birthYear,areaId:null}]);expect(validPopulationWithPeople(population,people)).toBe(true);expect(deriveCountryPopulation(population,people,'uk')).toEqual({knownLiving:10,complete:true});expect(population.coverage[0].source).toBe(pkg.id);expect(JSON.stringify(population)).not.toContain('transformations');const serialized=serializeGame({...game,population});expect(serialized.ok).toBe(true);if(serialized.ok)expect(JSON.parse(serialized.raw).population.coverage[0].source).toBe(pkg.id);
 });
 it('does not consume mutable RNG or mutate Clock while compiling',()=>{const randomness=createRandomness(42),before=structuredClone(randomness),clock=Object.freeze({version:2 as const,date:Object.freeze({...date}),cadence:'month' as const});compile(directPackage());expect(randomness).toEqual(before);expect(clock.date).toEqual(date);});
 it('keeps low-level People construction compatible',()=>{const people=createPeople({name:'Synthetic Person',dateOfBirth:{year:2000,month:1,day:1},genderLabel:'Person',lifeStatus:'living',traits:[],temperament:{},aptitudes:{}}),population=createPlayerPopulation(people,'synthetic');expect(validPopulationWithPeople(population,people)).toBe(true);});
});

describe('calibration dependency boundary',()=>{
 const sources=import.meta.glob<string>(['./arithmetic.ts','./compiler.ts','./integration.ts','./package.ts','./types.ts'],{eager:true,query:'?raw',import:'default'});
 it('has no React, UK, politics, host-randomness or wall-clock dependency',()=>{for(const [path,sourceText] of Object.entries(sources)){expect(sourceText,path).not.toMatch(/from\s+['"][^'"]*(?:react|politics|ukWorld|national|institutions)/);expect(sourceText,path).not.toMatch(/Math\.random|Date\.now/);}});
});
