import {addDays,addYears,compareDates,dateToOrdinal,isSimulationYear} from '../../core/clock';
import type {SimulationDate} from '../../core/model';
import {populationCohortId,type PopulationCohortInput} from '../population';
import {addRational,allocateLargestRemainder,compareRational,divideRational,multiplyRational,parseExactDecimal,rational,rationalToString,type ExactRational} from './arithmetic';
import {validatePopulationCalibrationPackage} from './package';
import type {CalibrationPrecision,CalibrationReport,CalibrationResult,EvidenceClassification,PopulationCalibrationPackageV1,PopulationMeasureV1} from './types';

export type CalibrationCompileOptions=Readonly<{
 profileExists:(id:string)=>boolean;
 areaExists?:(partitionId:string,areaId:string)=>boolean;
 livingMemberships?:readonly Readonly<{birthYear:number;areaId:string|null;count:number}>[];
}>;
const codePointCompare=(left:string,right:string)=>left<right?-1:left>right?1:0;
const dayCount=(from:SimulationDate,through:SimulationDate)=>Math.max(0,dateToOrdinal(through)-dateToOrdinal(from)+1);
const later=(a:SimulationDate,b:SimulationDate)=>compareDates(a,b)>=0?a:b;
const earlier=(a:SimulationDate,b:SimulationDate)=>compareDates(a,b)<=0?a:b;
const cellKey=(areaId:string|null,birthYear:number)=>`${areaId===null?'0:':`${areaId.length}:${areaId}`}|${birthYear}`;
const stableIdentifier=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=160&&value.includes('.')&&/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(value);
const safeSum=(values:readonly number[])=>values.reduce((sum,value)=>{const next=sum+value;if(!Number.isSafeInteger(next))throw Error('Calibration total exceeds safe integer range.');return next;},0);
const personsValue=(measure:PopulationMeasureV1)=>multiplyRational(parseExactDecimal(measure.value),rational(measure.unit==='thousand-persons'?1000n:1n));
function freezeDeep(value:unknown):void{if(!value||typeof value!=='object'||Object.isFrozen(value))return;for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor&&'value' in descriptor)freezeDeep(descriptor.value);}Object.freeze(value);}
function immutable<T>(value:T):T{const copy=structuredClone(value);freezeDeep(copy);return copy;}

function integer(value:ExactRational,label:string):number{
 if(value.denominator!==1n||value.numerator>BigInt(Number.MAX_SAFE_INTEGER))throw Error(`${label} must resolve to an exact safe integer person count.`);return Number(value.numerator);
}
function absoluteDifference(left:ExactRational,right:ExactRational):ExactRational{
 const numerator=left.numerator*right.denominator-right.numerator*left.denominator;return rational(numerator<0n?-numerator:numerator,left.denominator*right.denominator);
}
function profileFor(pkg:PopulationCalibrationPackageV1,birthYear:number):string|null{
 const matches=pkg.generationProfileBindings.filter(item=>birthYear>=item.fromBirthYear&&birthYear<=item.throughBirthYear);return matches.length===1?matches[0].generationProfileId:null;
}
function validCompileOptions(value:unknown):value is CalibrationCompileOptions{try{if(!value||typeof value!=='object'||Array.isArray(value)||(Object.getPrototypeOf(value)!==Object.prototype&&Object.getPrototypeOf(value)!==null))return false;const keys=Reflect.ownKeys(value);if(keys.some(key=>typeof key!=='string'||!['profileExists','areaExists','livingMemberships'].includes(key)))return false;for(const key of keys){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(!descriptor?.enumerable||!('value' in descriptor))return false;}const options=value as Record<string,unknown>;if(typeof options.profileExists!=='function'||options.areaExists!==undefined&&typeof options.areaExists!=='function')return false;if(options.livingMemberships===undefined)return true;if(!Array.isArray(options.livingMemberships)||options.livingMemberships.length>10000||Object.keys(options.livingMemberships).length!==options.livingMemberships.length||Reflect.ownKeys(options.livingMemberships).length!==options.livingMemberships.length+1)return false;for(let index=0;index<options.livingMemberships.length;index++){const descriptor=Object.getOwnPropertyDescriptor(options.livingMemberships,index);if(!descriptor?.enumerable||!('value' in descriptor))return false;const item=descriptor.value;if(!item||typeof item!=='object'||Array.isArray(item)||(Object.getPrototypeOf(item)!==Object.prototype&&Object.getPrototypeOf(item)!==null))return false;const itemKeys=Reflect.ownKeys(item);if(itemKeys.length!==3||!['birthYear','areaId','count'].every(key=>itemKeys.includes(key)))return false;for(const key of itemKeys){const field=Object.getOwnPropertyDescriptor(item,key);if(typeof key!=='string'||!['birthYear','areaId','count'].includes(key)||!field?.enumerable||!('value' in field))return false;}if(!isSimulationYear(item.birthYear)||item.areaId!==null&&!stableIdentifier(item.areaId)||!Number.isSafeInteger(item.count)||item.count<=0)return false;}return true;}catch{return false;}}

type Authority=Readonly<{value:ExactRational;universeId:string;qualifies:boolean;leafClassifications:readonly EvidenceClassification[];leafMeasureIds:readonly string[]}>;
function resolveAuthority(pkg:PopulationCalibrationPackageV1):Authority{
 const measures=new Map(pkg.measures.map(item=>[item.id,item])),derived=new Map(pkg.derivedTotals.map(item=>[item.id,item])),visiting=new Set<string>();
 const resolve=(kind:'measure'|'derived',id:string):Authority=>{
  if(kind==='measure'){
   const measure=measures.get(id);if(!measure||measure.semantic!=='population-count'||measure.dimensions.kind!=='total'||measure.unit==='percent')throw Error('Authoritative measure must be a population-count total.');
   return {value:personsValue(measure),universeId:measure.universeId,qualifies:measure.classification==='observed'||measure.classification==='estimated',leafClassifications:[measure.classification],leafMeasureIds:[measure.id]};
  }
  const item=derived.get(id);if(!item||visiting.has(id))throw Error('Invalid derived authoritative total lineage.');visiting.add(id);let value=rational(0n),qualifies=true;const leaves:EvidenceClassification[]=[],leafMeasureIds:string[]=[];
  for(const inputId of item.inputIds){const input=measures.has(inputId)?resolve('measure',inputId):resolve('derived',inputId);if(input.universeId!==item.universeId)throw Error('Derived total combines different population universes.');value=addRational(value,input.value);qualifies&&=input.qualifies;leaves.push(...input.leafClassifications);leafMeasureIds.push(...input.leafMeasureIds);}
  visiting.delete(id);return {value,universeId:item.universeId,qualifies,leafClassifications:leaves,leafMeasureIds};
 };
 return resolve(pkg.authority.kind,pkg.authority.id);
}

type WeightMeta={weight:ExactRational;touched:boolean;broad:boolean;rounded:boolean;measureIds:Set<string>};
function addWeight(map:Map<string,WeightMeta>,key:string,value:ExactRational,measure:PopulationMeasureV1,broad:boolean){const current=map.get(key)??{weight:rational(0n),touched:false,broad:false,rounded:false,measureIds:new Set<string>()};current.weight=addRational(current.weight,value);current.touched=true;current.broad||=broad;current.rounded||=measure.unit==='thousand-persons'||!!measure.roundingNote;current.measureIds.add(measure.id);map.set(key,current);}

export function compilePopulationCalibration(pkg:PopulationCalibrationPackageV1,options:CalibrationCompileOptions):CalibrationResult{
 if(!validatePopulationCalibrationPackage(pkg)||!validCompileOptions(options))throw Error('Invalid calibration compilation request.');
 const authority=resolveAuthority(pkg),authorityTotal=integer(authority.value,'Authoritative total'),universe=pkg.universes.find(item=>item.id===authority.universeId);if(!universe)throw Error('Unknown authoritative population universe.');if(authority.leafClassifications.includes('projected'))throw Error('Projected evidence cannot establish starting population cohorts.');for(const id of authority.leafMeasureIds){const measure=pkg.measures.find(item=>item.id===id)!;if(compareDates(measure.referenceDate,pkg.effectiveDate)!==0)throw Error('Contributing evidence reference date must equal the calibration effective date.');}
 const measureById=new Map(pkg.measures.map(item=>[item.id,item])),weights=new Map<string,WeightMeta>(),transformations:string[]=[];let unsupportedOpenBand=false,areaIncomplete=false,distributionSemantic:PopulationMeasureV1['semantic']|null=null;
 for(const id of [...pkg.distributionMeasureIds].sort(codePointCompare)){
  const measure=measureById.get(id)!;if(measure.classification==='projected')throw Error('Projected evidence cannot establish starting population cohorts.');if(measure.universeId!==authority.universeId)throw Error('Distribution and authority population universes differ.');if(compareDates(measure.referenceDate,pkg.effectiveDate)!==0)throw Error('Contributing evidence reference date must equal the calibration effective date.');if(distributionSemantic&&distributionSemantic!==measure.semantic)throw Error('Distribution evidence cannot mix counts and shares.');distributionSemantic=measure.semantic;
  const value=measure.semantic==='population-share'?parseExactDecimal(measure.value):personsValue(measure),dimensions=measure.dimensions;
  if(dimensions.kind==='total')throw Error('A total measure cannot be distribution evidence.');
  if(dimensions.areaId&&pkg.partition.areaPartitionId===null||dimensions.areaId&&pkg.partition.areaPartitionId&&(!options.areaExists||options.areaExists(pkg.partition.areaPartitionId,dimensions.areaId)!==true))throw Error('Distribution references an unresolved area.');
  const areaId=dimensions.areaId??null;if(pkg.partition.areaPartitionId!==null&&areaId===null)areaIncomplete=true;
  if(dimensions.kind==='birth-year'){
   if(dimensions.birthYear>=pkg.partition.birthYearFrom&&dimensions.birthYear<=pkg.partition.birthYearThrough)addWeight(weights,cellKey(areaId,dimensions.birthYear),value,measure,false);
   continue;
  }
  if(pkg.ageConversion.kind!=='uniform-birthday-by-day')throw Error('Completed-age evidence requires uniform-birthday-by-day calibration.');
  if(dimensions.maximumAge===null){unsupportedOpenBand=true;continue;}
  const from=addDays(addYears(pkg.effectiveDate,-(dimensions.maximumAge+1)),1),through=addYears(pkg.effectiveDate,-dimensions.minimumAge),totalDays=dayCount(from,through);if(totalDays<=0)throw Error('Invalid completed-age interval.');
  for(let year=pkg.partition.birthYearFrom;year<=pkg.partition.birthYearThrough;year++){
   const overlap=dayCount(later(from,{year,month:1,day:1}),earlier(through,{year,month:12,day:31}));if(overlap>0)addWeight(weights,cellKey(areaId,year),multiplyRational(value,rational(BigInt(overlap),BigInt(totalDays))),measure,true);
  }
  transformations.push(`Allocated ${measure.id} uniformly by Gregorian birth day across completed ages ${dimensions.minimumAge}-${dimensions.maximumAge}.`);
 }
 let distributionTotal=rational(0n);for(const item of weights.values())distributionTotal=addRational(distributionTotal,item.weight);const reconciliationTarget=distributionSemantic==='population-share'?rational(100n):authority.value,discrepancy=absoluteDifference(distributionTotal,reconciliationTarget);
 if(pkg.reconciliation.kind==='exact'&&compareRational(distributionTotal,reconciliationTarget)!==0&&!unsupportedOpenBand)throw Error('Distribution does not exactly reconcile to its required total.');
 const relative=reconciliationTarget.numerator===0n?(discrepancy.numerator===0n?rational(0n):rational(10000n)):multiplyRational(discrepancy,rational(10000n*reconciliationTarget.denominator,reconciliationTarget.numerator));
 if(pkg.reconciliation.kind==='proportional-largest-remainder'&&compareRational(relative,rational(BigInt(pkg.reconciliation.maximumDiscrepancyBasisPoints)))>0&&!unsupportedOpenBand)throw Error('Distribution discrepancy exceeds the configured threshold.');
 if(!unsupportedOpenBand){if(distributionSemantic==='population-share')transformations.push('Applied percentage shares to the authoritative population total.');else if(compareRational(distributionTotal,authority.value)!==0)transformations.push(`Scaled distribution to authoritative total using proportional largest remainder.`);}
 const allocationTarget=unsupportedOpenBand?(distributionSemantic==='population-count'&&distributionTotal.numerator>0n?integer(distributionTotal,'Supported distribution subtotal'):0):authorityTotal;
 const allocation=distributionTotal.numerator===0n||allocationTarget===0?{allocations:[] as readonly Readonly<{id:string;count:number}>[],residualAssignments:[] as readonly string[]}:allocateLargestRemainder(allocationTarget,[...weights].map(([id,item])=>({id,weight:item.weight}))),reservations=new Map<string,number>();
 for(const reservation of options.livingMemberships??[]){if(!Number.isSafeInteger(reservation.birthYear)||!Number.isSafeInteger(reservation.count)||reservation.count<0)throw Error('Invalid living membership reservation.');const key=cellKey(reservation.areaId,reservation.birthYear);reservations.set(key,safeSum([reservations.get(key)??0,reservation.count]));}
 const cohorts:PopulationCohortInput[]=[],precision:CalibrationReport['precision'][number][]=[],denials:string[]=[],generationDenials:string[]=[];let reservationTotal=0;
 for(const item of allocation.allocations){const separator=item.id.lastIndexOf('|'),areaPart=item.id.slice(0,separator),year=Number(item.id.slice(separator+1)),areaId=areaPart==='0:'?null:areaPart.slice(areaPart.indexOf(':')+1),reserved=reservations.get(item.id)??0;if(reserved>item.count)throw Error('Living membership reservations exceed their calibrated cohort.');reservationTotal=safeSum([reservationTotal,reserved]);
  const profile=profileFor(pkg,year);if(!profile){denials.push(`No unique generation-profile binding for birth year ${year}.`);continue;}if(options.profileExists(profile)!==true)generationDenials.push(`Generation profile ${profile} is unresolved for birth year ${year}.`);const count=item.count-reserved;if(count>0){const cohort={countryId:pkg.countryId,areaId,birthYear:year,generationProfileId:profile,count};cohorts.push(cohort);const meta=weights.get(item.id)!;let resolution:CalibrationPrecision,note:string;if(meta.broad&&meta.rounded){resolution='calibrated-from-broader-rounded-evidence';note='Exact integer cohort allocated from broader, rounded completed-age evidence.';}else if(meta.broad){resolution='calibrated-from-broader-evidence';note='Exact integer cohort allocated from broader completed-age evidence.';}else if(meta.rounded){resolution='canonical-exact-from-rounded-source';note='Exact integer cohort calibrated from rounded source evidence.';}else if(meta.measureIds.size>0&&[...meta.measureIds].every(id=>measureById.get(id)?.classification==='assumed')){resolution='calibrated-from-broader-evidence';note='Canonical exact cohort from an explicitly assumed and calibrated distribution; not a direct observation.';}else{resolution='direct-resolution';note='Direct single-birth-year evidence.';}precision.push({cohortId:populationCohortId(cohort),resolution,note});}}
 for(const reservationKey of reservations.keys())if(!allocation.allocations.some(item=>item.id===reservationKey))throw Error('Living membership reservation is outside calibrated output.');
 const touchedCells=new Set([...weights].filter(([,item])=>item.touched).map(([key])=>key)),areas:readonly (string|null)[]=pkg.partition.areaPartitionId===null?[null]:[...new Set(pkg.distributionMeasureIds.map(id=>measureById.get(id)!.dimensions).flatMap(item=>item.kind!=='total'&&typeof item.areaId==='string'?[item.areaId]:[]))].sort(codePointCompare);for(const areaId of areas)for(let year=pkg.partition.birthYearFrom;year<=pkg.partition.birthYearThrough;year++)if(!touchedCells.has(cellKey(areaId,year)))denials.push(`Distribution evidence does not cover ${areaId??'the country'} birth year ${year}.`);
 if(!universe.exhaustive)denials.push('Authoritative population universe is not declared exhaustive.');if(!authority.qualifies)denials.push('Authoritative total magnitude ultimately depends on assumed or projected evidence.');if(unsupportedOpenBand)denials.push('Open-ended age evidence has no supported tail allocation.');if(areaIncomplete)denials.push('A versioned area partition has distribution evidence without an area classification.');for(const gap of pkg.gaps)if(gap.blocking)denials.push(`Blocking gap: ${gap.id}.`);
 if(pkg.coverageIntent==='partial')denials.push('Package requested partial coverage.');
 const assumptions=[...pkg.measures.filter(item=>item.classification==='assumed').map(item=>item.id),...(pkg.ageConversion.kind==='uniform-birthday-by-day'?['assumption.uniform-birthday-by-day']:[])].sort(codePointCompare),uncertainty=pkg.measures.flatMap(item=>[item.uncertainty,item.roundingNote].filter((value):value is string=>!!value).map(value=>`${item.id}: ${value}`)).sort(codePointCompare);
 const sources=pkg.sources.map(source=>({id:source.id,organisation:source.organisation,datasetId:source.datasetId,releaseId:source.releaseId,title:source.title,referencePeriod:{from:{...source.referencePeriod.from},through:{...source.referencePeriod.through}},jurisdiction:source.jurisdiction,publicationStatus:source.publicationStatus,classifications:[...new Set(pkg.measures.filter(item=>item.sourceId===source.id).map(item=>item.classification))].sort(codePointCompare) as EvidenceClassification[],methodologyNote:source.methodologyNote,...(source.bundledArtifact===undefined?{}:{bundledArtifact:source.bundledArtifact}),...(source.externalLocator===undefined?{}:{externalLocator:source.externalLocator}),...(source.retrievedAt===undefined?{}:{retrievedAt:{...source.retrievedAt}})})).sort((a,b)=>codePointCompare(a.id,b.id));
 const granted=pkg.coverageIntent==='complete'&&denials.length===0?'complete':'partial',generationReadiness=generationDenials.length===0?'ready':'not-ready';const finalSum=safeSum(cohorts.map(item=>item.count));if(granted==='complete'&&safeSum([finalSum,reservationTotal])!==authorityTotal)throw Error('Complete calibration failed population conservation.');
 const inputs=pkg.measures.map(item=>{const notes=[item.dimensions.kind==='birth-year'?'Direct birth-year input.':item.dimensions.kind==='completed-age-band'?'Broader completed-age input requiring allocation.':'Population total input.'];if(item.unit==='thousand-persons'||item.roundingNote)notes.push(`Source resolution is rounded${item.roundingNote?`: ${item.roundingNote}`:'.'}`);return {id:item.id,sourceId:item.sourceId,classification:item.classification,semantic:item.semantic,unit:item.unit,value:item.value,referenceDate:{...item.referenceDate},universeId:item.universeId,resolutionNote:notes.join(' ')}}).sort((a,b)=>codePointCompare(a.id,b.id));
 const canonicalCohorts=cohorts.sort((a,b)=>codePointCompare(populationCohortId(a),populationCohortId(b))),membershipReservations=[...reservations].map(([key,count])=>{const separator=key.lastIndexOf('|'),areaPart=key.slice(0,separator);return {birthYear:Number(key.slice(separator+1)),areaId:areaPart==='0:'?null:areaPart.slice(areaPart.indexOf(':')+1),count};}).sort((a,b)=>(a.areaId===b.areaId?0:a.areaId===null?-1:b.areaId===null?1:codePointCompare(a.areaId,b.areaId))||a.birthYear-b.birthYear);
 const report:CalibrationReport={version:1,packageId:pkg.id,fingerprint:pkg.fingerprint,countryId:pkg.countryId,effectiveDate:{...pkg.effectiveDate},requestedCoverage:pkg.coverageIntent,grantedCoverage:granted,sources,universes:[...new Set(pkg.measures.map(item=>item.universeId))].sort(codePointCompare),inputs,authoritativeTotal:{id:pkg.authority.id,kind:pkg.authority.kind,value:authorityTotal,universeId:authority.universeId,exhaustiveUniverse:universe.exhaustive,qualifiesForCompleteness:authority.qualifies,role:universe.exhaustive&&authority.qualifies?'exhaustive-universe-total':'selected-reference-total'},distributionOriginalTotal:rationalToString(distributionTotal),absoluteDiscrepancy:rationalToString(discrepancy),relativeDiscrepancyBasisPoints:rationalToString(relative),thresholdBasisPoints:pkg.reconciliation.kind==='exact'?null:pkg.reconciliation.maximumDiscrepancyBasisPoints,scaleFactor:unsupportedOpenBand||distributionTotal.numerator===0n?null:rationalToString(divideRational(authority.value,distributionTotal)),transformations:[...new Set(transformations)].sort(codePointCompare),precision:precision.sort((a,b)=>codePointCompare(a.cohortId,b.cohortId)),allocations:canonicalCohorts.map(item=>({cohortId:populationCohortId(item),count:item.count})),membershipReservations,residualAssignments:allocation.residualAssignments,assumptions,uncertainty,unsupportedCategories:unsupportedOpenBand?['open-ended-age-band']:[],gaps:pkg.gaps.map(item=>({...item})).sort((a,b)=>codePointCompare(a.id,b.id)),profileBindings:pkg.generationProfileBindings.map(item=>({...item})).sort((a,b)=>a.fromBirthYear-b.fromBirthYear),completenessDenialReasons:[...new Set(denials)].sort(codePointCompare),generationReadiness,generationReadinessDenialReasons:[...new Set(generationDenials)].sort(codePointCompare),finalCohortCount:cohorts.length,finalCohortSum:finalSum,livingMembershipReservations:reservationTotal};
 return immutable({coverage:granted,generationReadiness,cohorts:canonicalCohorts,report});
}

export function renderPopulationCalibrationReport(report:CalibrationReport):string{
 const authorityLabel=report.authoritativeTotal.role==='exhaustive-universe-total'?'Authoritative exhaustive-universe total':'Selected reference total';const lines=[`Calibration ${report.packageId} (${report.fingerprint})`,`Country: ${report.countryId}; effective date: ${report.effectiveDate.year}-${String(report.effectiveDate.month).padStart(2,'0')}-${String(report.effectiveDate.day).padStart(2,'0')}`,`Coverage: requested ${report.requestedCoverage}; granted ${report.grantedCoverage}`,`Person-generation readiness: ${report.generationReadiness}${report.generationReadinessDenialReasons.length?`; ${report.generationReadinessDenialReasons.join('; ')}`:''}`,`${authorityLabel}: ${report.authoritativeTotal.value} in ${report.authoritativeTotal.universeId}; final anonymous cohorts: ${report.finalCohortSum}; reserved living memberships: ${report.livingMembershipReservations}`,`Distribution total before reconciliation: ${report.distributionOriginalTotal}; discrepancy: ${report.absoluteDiscrepancy} (${report.relativeDiscrepancyBasisPoints} bp); threshold: ${report.thresholdBasisPoints??'exact'}; scale: ${report.scaleFactor??'not applied'}`,`Sources: ${report.sources.map(item=>`${item.id}[${item.classifications.join(',')};${item.publicationStatus};${item.datasetId}/${item.releaseId}]`).join('; ')||'none'}`,`Inputs: ${report.inputs.map(item=>`${item.id}=${item.value} ${item.unit} (${item.classification}; ${item.resolutionNote})`).join('; ')||'none'}`,`Transformations: ${report.transformations.join('; ')||'none'}`,`Allocations: ${report.allocations.map(item=>`${item.cohortId}=${item.count}`).join('; ')||'none'}`,`Precision: ${report.precision.map(item=>`${item.cohortId}: ${item.note}`).join('; ')||'none'}`,`Residual assignments: ${report.residualAssignments.join(', ')||'none'}`,`Assumptions: ${report.assumptions.join(', ')||'none'}`,`Uncertainty: ${report.uncertainty.join('; ')||'none'}`,`Unsupported: ${report.unsupportedCategories.join(', ')||'none'}`,`Gaps: ${report.gaps.map(item=>item.id).join(', ')||'none'}`,`Completeness denials: ${report.completenessDenialReasons.join('; ')||'none'}`];return lines.join('\n');
}
