import {describe,it,expect} from 'vitest';
import {baselineBudget,nationalLaws} from '../data/national';
import {createNational,advanceNational,costBudget,distribution,incomeTax,employeeNI,nationalAction,nationalReason,validBudget} from './national';
import {validNational} from './nationalSave';
import {createGame} from './game';
import {adultStart,joinPolitics,choosePoliticalEvent,advancePoliticalMonth} from './politics';
import {isGame,saveGame,loadGame,SAVE_KEY,PRE_NATIONAL_SAVE_KEY} from './save';
import {lifeMonth} from './core/clock';
import {COMPATIBILITY_NATIONAL_STREAM,synchronizeCompatibilitySeed} from './core/rng';
function installNational(g:ReturnType<typeof createGame>,seed:number){g.ukWorld!.national=createNational(seed);synchronizeCompatibilitySeed(g.randomness!,COMPATIBILITY_NATIONAL_STREAM,g.ukWorld!.national.seed);}
function member(){let g=choosePoliticalEvent(joinPolitics(adultStart(createGame('Sam','Woman','uk',22)),'labour','socratic'),0);Object.assign(g.politics!,{role:'premier',seats:410,inGovernment:true,knowledge:90,caucus:90,integrity:90});g.actions=3;installNational(g,22);return g;}
function legacyWithoutWorld(g:ReturnType<typeof member>,includeNational=false){const old=structuredClone(g);if(includeNational)old.politics!.national=structuredClone(old.ukWorld!.national);delete old.ukWorld;return old;}
describe('national economics',()=>{
 it('uses marginal tax bands, the allowance taper and NI thresholds',()=>{expect(incomeTax(12570,baselineBudget)).toBe(0);expect(incomeTax(50270,baselineBudget)).toBeCloseTo(7540);expect(incomeTax(110000,baselineBudget)).toBeCloseTo(33432);expect(incomeTax(150000,baselineBudget)).toBeCloseTo(53703);expect(employeeNI(50270,baselineBudget)).toBeCloseTo(3016);expect(employeeNI(60270,baselineBudget)).toBeCloseTo(3216);});
 it('changes tax receipts and distribution without silently changing a live budget',()=>{const n=createNational(1),b={...n.budget,basic:22,vat:22};const base=costBudget(n,n.budget),changed=costBudget(n,b);expect(changed.revenue).toBeGreaterThan(base.revenue);expect(distribution(n,b)[0].realNet).toBeLessThan(distribution(n)[0].realNet);expect(n.budget).toEqual(baselineBudget);expect(validBudget({...b,basic:50})).toBe(false);});
 it('keeps fiscal flows, debt changes and creditor claims consistent across diverse histories',()=>{for(let seed=0;seed<12;seed++){let n=createNational(seed);for(let month=0;month<120;month++){const old=n;n=advanceNational(n,seed%2===0);expect(n).not.toBe(old);expect(n.debt-old.debt).toBeCloseTo(n.fiscal.spending-n.fiscal.revenue,3);expect(n.debt).toBe(n.bondAssets);expect(validNational(n,n.month),`seed ${seed}, month ${month}`).toBe(true);}}});
 it('reproduces a saved timeline while different seeds and policies diverge',()=>{let a=createNational(10),b=createNational(11),c=createNational(10);c.budget={...c.budget,basic:30,investment:30};for(let i=0;i<48;i++){a=advanceNational(a,true);b=advanceNational(b,true);c=advanceNational(c,true);}expect(a.realGDP).not.toBe(b.realGDP);expect(a.realGDP).not.toBe(c.realGDP);expect(a.news.map(x=>[x.month,x.id])).not.toEqual(b.news.map(x=>[x.month,x.id]));expect(advanceNational(a,true)).toEqual(advanceNational(JSON.parse(JSON.stringify(a)),true));});
 it('makes welfare respond to unemployment and reprices debt gradually',()=>{const n=createNational(4);n.unemployment=10;expect(costBudget(n,n.budget).spending).toBeGreaterThan(costBudget(createNational(4),n.budget).spending);n.yield=10;const next=advanceNational(n,true);expect(Math.abs(next.effectiveRate-n.effectiveRate)).toBeLessThan(.1);expect(next.bankRate).toBeGreaterThanOrEqual(0);});
 it('does not deliver infrastructure immediately or spend its cost twice',()=>{let n=createNational(5);n.enacted=[{id:'grid',month:0,due:12,intensity:1,delivered:false}];const f=costBudget(n,n.budget);expect(f.flows.find(x=>x.name==='Grid Connections and Storage Bill')!.amount).toBeCloseTo(1);for(let i=0;i<11;i++)n=advanceNational(n,true);expect(n.enacted[0].delivered).toBe(false);for(let i=0;i<12;i++)n=advanceNational(n,true);expect(n.enacted[0].delivered).toBe(true);expect(validNational(n,n.month)).toBe(true);});
 it('rejects corrupt stock/flow histories and invalid bills',()=>{const n=advanceNational(createNational(1),true);expect(validNational({...n,debt:n.debt+1},1)).toBe(false);expect(validNational({...n,history:[{...n.history[0],borrowing:0}]},1)).toBe(false);expect(validNational({...n,budget:{...n.budget,vat:100}},1)).toBe(false);expect(validNational({...n,proposal:{kind:'law',id:'fake'}},1)).toBe(false);});
 it('delays changes to capital delivery and handles a full legislative programme',()=>{let n=createNational(2);n.budget.investment=240;n=advanceNational(n,true);expect(n.productivity).toBe(1);expect(n.investmentPipeline.at(-1)!.amount).toBe(20);n.enacted=nationalLaws.map(l=>({id:l.id,month:1,due:1+l.delay,intensity:1,delivered:false}));for(let i=0;i<240;i++){n=advanceNational(n,true);expect(validNational(n,n.month)).toBe(true);}expect(n.enacted.every(l=>l.delivered)).toBe(true);});
});
describe('national decisions within the political life',()=>{
 it('keeps taxation out of an activist or housing minister’s unilateral powers',()=>{const g=member();g.politics!.role='activist';expect(nationalAction(g,'budget',undefined,{...baselineBudget,vat:22})).toBe(g);g.politics!.role='minister';expect(nationalReason(g,'budget')).toContain('Prime Minister');expect(nationalAction(g,'law','grid')).not.toBe(g);});
 it('freezes the submitted budget, gates stages and spends the shared activity',()=>{let g=member();const draft={...baselineBudget,vat:22};g=nationalAction(g,'budget',undefined,draft);draft.vat=25;expect(g.ukWorld!.national.proposal!.budget!.vat).toBe(22);expect(g.ukWorld!.national.budget.vat).toBe(20);expect(g.actions).toBe(2);expect(nationalAction(g,'advance')).toBe(g);expect(nationalAction(g,'law','grid')).toBe(g);});
 it('passes a negotiated budget through divisions before applying rates',()=>{let g=member();g=nationalAction(g,'budget',undefined,{...baselineBudget,basic:22});for(let i=0;i<8&&g.ukWorld!.national.proposal;i++){g.actions=3;g=nationalAction(g,'lobby');g=advancePoliticalMonth(g);if(g.politics!.pending)g=choosePoliticalEvent(g,0);g.actions=3;g=nationalAction(g,'advance');}expect(g.ukWorld!.national.budget.basic).toBe(22);expect(g.ukWorld!.national.divisions.length).toBe(3);expect(g.ukWorld!.national.divisions.every(x=>x.ayes+x.noes+x.abstain===650)).toBe(true);expect(isGame(g)).toBe(true);});
 it('can defeat a bill and changes nothing when a proposal is withdrawn',()=>{let defeats=0;for(let seed=0;seed<10;seed++){let g=member();Object.assign(g.politics!,{seats:40,inGovernment:false,caucus:10});installNational(g,seed);g=nationalAction(g,'law','bargaining');g=advancePoliticalMonth(g);g=choosePoliticalEvent(g,0);g=nationalAction(g,'advance');if(g.ukWorld!.national.divisions[0]?.passed===false)defeats++;}expect(defeats).toBeGreaterThan(0);let g=member();g=nationalAction(g,'law','grid');g=nationalAction(g,'withdraw');expect(g.ukWorld!.national.proposal).toBeNull();expect(g.ukWorld!.national.enacted).toHaveLength(0);});
 it('requires spending consent and reduces cost and benefit through compromise',()=>{let g=member();g.politics!.role='mp';g=nationalAction(g,'law','grid');expect(g.ukWorld!.national.proposal!.consent).toBe(false);g=nationalAction(g,'amend');expect(g.ukWorld!.national.proposal!.intensity).toBe(.5);g.actions=3;g.ukWorld!.national.proposal!.stage=1;g.ukWorld!.national.proposal!.lastMonth=-1;expect(nationalReason(g,'advance')).toContain('money resolution');});
 it('migrates old national state verbatim and initialises old careers without one prospectively',()=>{const original=member(),withNational=legacyWithoutWorld(original,true),data=new Map([[SAVE_KEY,JSON.stringify(withNational)]]),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};expect(loadGame(storage).game).toEqual({...original,version:4,residence:{version:1,nextSequence:1,residences:[],occupants:[],noFixedAbodePersonIds:[]}});const old=legacyWithoutWorld(original),raw=JSON.stringify(old);data.set(SAVE_KEY,raw);let g=loadGame(storage).game!;expect(g.ukWorld!.national.month).toBe(lifeMonth(g));const before=structuredClone(g);g=advancePoliticalMonth(g);expect(g.ukWorld!.national.introduced).toBe(before.ukWorld!.national.introduced);expect(g.politics!.months).toBe(before.politics!.months+1);expect(g.age).toBe(before.age);expect(saveGame(storage,g)).toBeNull();expect(data.get(PRE_NATIONAL_SAVE_KEY)).toBe(raw);expect(isGame(loadGame(storage).game)).toBe(true);});
 it('keeps the original career when its national recovery snapshot cannot be stored',()=>{const current=member(),old=legacyWithoutWorld(current),raw=JSON.stringify(old),data=new Map([[SAVE_KEY,raw]]);const storage={getItem:(k:string)=>k===SAVE_KEY?raw:data.get(k)??null,setItem:(k:string,v:string)=>{if(k===PRE_NATIONAL_SAVE_KEY)throw Error('Quota');data.set(k,v);}};expect(saveGame(storage,advancePoliticalMonth(loadGame(storage).game!))).toBeTruthy();expect(data.get(SAVE_KEY)).toBe(raw);});
 it('feeds national policy into constituency transfers and preserves cash counterparties',()=>{let g=member();g.ukWorld!.national.budget.basic=25;g.ukWorld!.national.budget.local=100;g=advancePoliticalMonth(g);const t=g.politics!.economy;expect(t.ledger.find(x=>x.reason==='Programme grant')!.amount).toBeCloseTo(110000*100/65,2);expect(t.ledger.some(x=>x.reason==='National tax change')).toBe(true);expect(g.politics!.lastIncome).toBeLessThan(78000/12);expect(isGame(g)).toBe(true);expect(nationalLaws).toHaveLength(72);});
});
