import { describe,it,expect } from 'vitest';
import { advanceTown,createTown,policyReason,townTotal,type Town } from './town';
import { readTown,writeTown,validTown,TOWN_SAVE_KEY } from './townSave';
import { SAVE_KEY, loadGame } from './save';
import legacyLife from './fixtures/life-v1.json';
import { ageUp } from './game';
import { townPolicies,type PolicyId } from '../data/town';
function run(policy:PolicyId,seed=7){let t=createTown(seed);for(let i=0;i<24;i++)t=advanceTown(t,policyReason(t,policy)?'hold':policy);return t;}
describe('Mereford monthly economy',()=>{
  it('preserves immutable, deterministic transitions',()=>{const t=createTown(2);const before=structuredClone(t);const a=advanceTown(t,'relief');expect(t).toEqual(before);expect(a).toEqual(advanceTown(createTown(2),'relief'));expect(a.month).toBe(1);});
  it('preserves every account and a balanced total through all policy strategies',()=>{for(const p of townPolicies){const t=run(p.id);expect(validTown(t)).toBe(true);expect(townTotal(t)).toBe(t.initialTotal);expect(t.households.every(h=>h.cash>=0&&h.wellbeing>=0&&h.wellbeing<=100)).toBe(true);expect(t.employers.every(f=>f.jobs>=0&&f.jobs<=f.capacity&&f.cash>=0)).toBe(true);expect(t.history).toHaveLength(24);expect(advanceTown(t,'hold')).toBe(t);}});
  it('records grants, service costs and relief exactly once',()=>{const t=advanceTown(createTown(),'relief');expect(t.fund).toBe(285000);expect(t.ledger.filter(x=>x.reason==='Household relief').reduce((s,x)=>s+x.amount,0)).toBe(45000);expect(t.ledger.filter(x=>x.reason==='Programme grant')).toHaveLength(1);expect(t.ledger.filter(x=>x.reason==='Baseline service provision')).toHaveLength(1);});
  it('does not spend unaffordable reserves',()=>{const t=createTown();t.outside+=t.fund-100;t.fund=100;expect(policyReason(t,'relief')).toBeTruthy();expect(advanceTown(t,'relief')).toBe(t);expect(advanceTown(t,'hold').fund).toBe(30100);});
  it('delays investment savings three months and caps five projects',()=>{let t=advanceTown(createTown(),'retrofit');expect(t.projects).toEqual([{due:4}]);expect(t.insulation).toBe(0);t=advanceTown(advanceTown(t,'hold'),'hold');expect(t.insulation).toBe(0);t=advanceTown(t,'hold');expect(t.insulation).toBe(.06);expect(t.projects).toHaveLength(0);const complete=run('retrofit');expect(complete.insulation).toBe(.3);expect(policyReason({...complete,month:23},'retrofit')).toContain('five');});
  it('energy shock raises both household and employer bills',()=>{let t=createTown(3);for(let i=0;i<4;i++)t=advanceTown(t,'hold');const bills=(month:number,reason:string)=>t.ledger.filter(x=>x.month===month&&x.reason===reason).reduce((s,x)=>s+x.amount,0);expect(bills(4,'Household energy')).toBeGreaterThan(bills(3,'Household energy'));expect(bills(4,'Business energy')).toBeGreaterThan(bills(3,'Business energy'));});
  it('relief and insulation produce different household and fiscal outcomes',()=>{const hold=run('hold'),relief=run('relief'),retrofit=run('retrofit');expect(relief.households[2].cash).toBeGreaterThan(hold.households[2].cash);expect(retrofit.ledger.filter(x=>x.reason==='Household energy').reduce((s,x)=>s+x.amount,0)).toBeLessThan(hold.ledger.filter(x=>x.reason==='Household energy').reduce((s,x)=>s+x.amount,0));expect(relief.fund).toBeLessThan(hold.fund);});
  it('changing an analytical lens does not change the economy',()=>{const a=advanceTown(createTown(9),'hold');const b=advanceTown({...createTown(9),lens:'marx'},'hold');expect({...a,lens:'marx'}).toEqual(b);});
  it('survives 40 mixed policy experiments, checking every monthly save',()=>{for(let seed=0;seed<40;seed++){let t=createTown(seed);for(let month=0;month<24;month++){const p=townPolicies[(seed+month)%4].id;t=advanceTown(t,policyReason(t,p)?'hold':p);expect(validTown(t),`seed ${seed} month ${month}`).toBe(true);}}});
});
describe('town save isolation and recovery',()=>{
  it('continues a fixed pre-politics life save after a complete town experiment',()=>{const original=JSON.stringify(legacyLife);const data=new Map([[SAVE_KEY,original]]);const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};writeTown(storage,run('retrofit'));const life=loadGame(storage).game;expect(life).toEqual(legacyLife);expect(ageUp(life!).age).toBe(26);expect(data.get(SAVE_KEY)).toBe(original);});
  it('never reads or writes the original life save',()=>{const data=new Map([[SAVE_KEY,'original-life-save']]);const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};const t=run('hold');expect(writeTown(storage,t)).toBeNull();expect(readTown(storage).town).toEqual(t);expect(data.get(SAVE_KEY)).toBe('original-life-save');expect(data.has(TOWN_SAVE_KEY)).toBe(true);});
  it('rejects corruption, wrong versions, tampered cash and invalid history',()=>{const valid=advanceTown(createTown(),'hold');for(const candidate of [null,{}, {...valid,version:2},{...valid,fund:valid.fund+1},{...valid,history:[]},{...valid,ledger:[{month:1,from:'unknown',to:'fund',amount:3,reason:'x'}]},{...valid,projects:[{due:0}]}])expect(validTown(candidate)).toBe(false);});
  it('preserves invalid saves and reports storage failures',()=>{let raw='broken';const storage={getItem:()=>raw,setItem:(_k:string,v:string)=>{raw=v;}};expect(readTown(storage).error).toBeTruthy();expect(raw).toBe('broken');const denied={getItem:()=>{throw Error();},setItem:()=>{throw Error();}};expect(writeTown(denied,createTown())).toBeTruthy();expect(readTown(denied).error).toBeTruthy();});
  it('preserves future outcomes after save restoration',()=>{const original=advanceTown(createTown(),'retrofit');let raw='';const storage={getItem:()=>raw,setItem:(_k:string,v:string)=>{raw=v;}};writeTown(storage,original);const loaded=readTown(storage).town as Town;expect(advanceTown(loaded,'business')).toEqual(advanceTown(original,'business'));});
});
