import {describe,it,expect} from 'vitest';
import {adultStart,ageUp,advanceMonth,createGame,choose} from './simulation';
import {joinPolitics,choosePoliticalEvent,advancePoliticalMonth,leavePolitics} from './politics';
import {isGame,loadGame,migrateGame,saveGame,SAVE_KEY,PRE_UK_WORLD_SAVE_KEY} from './save';
import {validLife} from './core/validation';
import {events} from '../data/events';
import {nationalAction} from './national';
import {baselineBudget} from '../data/national';
import lifeV1 from './fixtures/life-v1.json';
import type {Game} from './types';
import {lifeMonth} from './core/clock';

function settle(g:Game){if(!g.pending)return g;const event=events.find(x=>x.id===g.pending),index=event?.choices.findIndex(c=>(c.effects.money??0)>=-Math.max(0,g.money))??-1;return choose(g,index<0?0:index);}
function advanceYears(g:Game,years:number){for(let i=0;i<years;i++)g=settle(ageUp(g));return g;}
function advanceWorldMonths(g:Game,months:number){const target=g.ukWorld!.national.month+months;while(g.ukWorld!.national.month<target){g=settle(g);if(!g.pending)g=advanceMonth(g);}return g;}
function oldSave(g:Game,keepNational=false){const old=structuredClone(g);if(keepNational&&old.politics)old.politics.national=structuredClone(old.ukWorld!.national);delete old.ukWorld;return old;}

describe('independent UK world',()=>{
 it('creates and advances a UK world for a non-political character',()=>{let g=createGame('Jamie','Woman','uk',91);expect(g.politics).toBeUndefined();expect(g.ukWorld?.national.month).toBe(0);g=advanceYears(g,1);expect(g.ukWorld!.national.month).toBe(12);expect(g.politics).toBeUndefined();});
 it('advances national indicators, banking, services and national incidents without UKPolitics',()=>{let g=createGame('Morgan','Man','uk',31);const before=structuredClone(g.ukWorld!.national);g=advanceWorldMonths(g,24);const n=g.ukWorld!.national;expect(n.month).toBe(24);expect(n.history).toHaveLength(24);expect(n.realGDP).not.toBe(before.realGDP);expect(n.institutions!.bankLog).toHaveLength(72);expect(n.institutions!.banks).not.toEqual(before.institutions!.banks);expect(n.institutions!.regions).not.toEqual(before.institutions!.regions);expect(n.news.length).toBeGreaterThan(0);expect(g.politics).toBeUndefined();});
 it('attaches a later political career to the exact existing world and starts Mereford as separate local state',()=>{let g=adultStart(createGame('Taylor','Non-binary','uk',11));g=settle(advanceWorldMonths(g,24));const prior=structuredClone(g.ukWorld);g=joinPolitics(g,'labour','socratic');expect(g.ukWorld).toEqual(prior);expect(g.ukWorld!.national.month).toBe(24);expect(g.politics!.months).toBe(0);expect(g.politics!.economy.month).toBe(0);g=choosePoliticalEvent(g,0);g=advancePoliticalMonth(g);expect(g.ukWorld!.national.month).toBe(25);expect(g.politics!.months).toBe(1);expect(g.politics!.economy.month).toBe(1);});
 it('advances the UK world once for a political month, not once per active system',()=>{let g=joinPolitics(adultStart(createGame('Robin','Man','uk',7)),'labour','marx');g=choosePoliticalEvent(g,0);const world=g.ukWorld!.national.month,tenure=g.politics!.months;g=advancePoliticalMonth(g);expect(g.ukWorld!.national.month-world).toBe(1);expect(g.politics!.months-tenure).toBe(1);});
 it('continues national progression immediately after deactivating politics while tenure and local state freeze',()=>{let g=joinPolitics(adultStart(createGame('Casey','Woman','uk',6)),'green','smith');g=choosePoliticalEvent(g,0);g=leavePolitics(g);const record=structuredClone(g.politics),month=g.ukWorld!.national.month;g=advanceMonth(g);expect(g.ukWorld!.national.month).toBe(month+1);expect(g.politics).toEqual({...record,active:false});expect(g.politics!.months).toBe(record!.months);expect(g.politics!.economy).toEqual(record!.economy);expect(isGame(g)).toBe(true);g=advanceWorldMonths(g,12);expect(g.ukWorld!.national.month).toBe(month+13);expect(g.politics!.months).toBe(record!.months);expect(isGame(g)).toBe(true);});
 it('migrates old politics.national once without rewriting national or Mereford state',()=>{let g=joinPolitics(adultStart(createGame('Alex','Man','uk',20)),'labour','marx');g=choosePoliticalEvent(g,0);g=advancePoliticalMonth(g);g.politics!.economy.lens='marx';const canonical=structuredClone(g),legacy=oldSave(g,true),legacyTown=structuredClone(legacy.politics!.economy),legacyNation=structuredClone(legacy.politics!.national);const migrated=migrateGame(legacy)!;expect(migrated).toEqual(canonical);expect(migrateGame(migrated)).toEqual(migrated);expect(migrated.ukWorld!.national).toEqual(legacyNation);expect(migrated.politics!.economy).toEqual(legacyTown);expect(legacy.politics!.national).toEqual(canonical.ukWorld!.national);});
 it('uses life elapsed time rather than political tenure in a legacy action fallback',()=>{let g=joinPolitics(adultStart(createGame('Drew','Man','uk',15)),'labour','smith');g=choosePoliticalEvent(g,0);Object.assign(g.politics!,{role:'premier',seats:410,inGovernment:true});g.actions=3;delete g.ukWorld;expect(g.politics!.months).toBe(0);g=nationalAction(g,'budget',undefined,{...baselineBudget,vat:21});expect(g.ukWorld!.national.introduced).toBe(216);expect(g.ukWorld!.national.month).toBe(216);expect(g.politics!.months).toBe(0);});
 it('initialises old politics saves without national state prospectively and keeps a recovery copy',()=>{const live=joinPolitics(adultStart(createGame('Sam','Woman','uk',8)),'labour','socratic'),legacy=oldSave(live),raw=JSON.stringify(legacy),data=new Map([[SAVE_KEY,raw]]),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};const migrated=loadGame(storage).game!;expect(migrated.ukWorld!.national.month).toBe(lifeMonth(migrated));expect(migrated.ukWorld!.national.introduced).toBe(migrated.ukWorld!.national.month);expect(saveGame(storage,migrated)).toBeNull();expect(data.get(PRE_UK_WORLD_SAVE_KEY)).toBe(raw);});
 it('initialises non-political legacy UK saves prospectively while leaving other countries alone',()=>{const legacy=oldSave(createGame('Jordan','Man','uk',13)),migrated=migrateGame(legacy)!;expect(migrated.ukWorld!.national.month).toBe(migrated.age*12);expect(migrated.politics).toBeUndefined();const canada=migrateGame(oldSave(createGame('Jordan','Man','ca',13)))!;expect(canada.ukWorld).toBeUndefined();});
 it('validates migrated saves and the untouched v1 life fixture',()=>{expect(isGame(migrateGame(oldSave(createGame('A','Woman','uk',1))))).toBe(true);expect(validLife(lifeV1)).toBe(true);expect(migrateGame({...createGame('A','Woman','uk',1),ukWorld:{version:9}})).toBeNull();});
});
