// Human approval report rendered from the authoritative research specification.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('../..',import.meta.url)));
const filename='UK-INITIAL-RESIDENCE-PLACEMENT-NUMERICAL-APPROVAL.json';
const bytes=fs.readFileSync(path.join(root,filename)),a=JSON.parse(bytes),sha=crypto.createHash('sha256').update(bytes).digest('hex');
const f=x=>`${x.numerator}/${x.denominator}`;
const percent=x=>`${(100*x.numerator/x.denominator).toFixed(6)}% (diagnostic)`;
const esc=x=>String(x).replaceAll('|','\\|').replaceAll('\n',' ');
const table=(headers,rows)=>['| '+headers.join(' | ')+' |','| '+headers.map(()=> '---').join(' | ')+' |',...rows.map(r=>'| '+r.map(esc).join(' | ')+' |')].join('\n');
const section=(n,title,body)=>`## ${n}. ${title}\n\n${body}\n\n`;
const byName=n=>a.areas.find(r=>r.displayName===n);
const massKinds=r=>Object.entries(r.candidates.filter(c=>!c.principalRole).reduce((m,c)=>{const k=c.kindId||'administrative';(m[k]??=[]).push(c.weight);return m;},{})).sort(([x],[y])=>x<y?-1:x>y?1:0).map(([k,ws])=>`${ws.length} × ${ws[0]} (${k})`).join('; ');
const principalRows=a.areas.filter(r=>r.principalRoles);
const fullPrincipalTable=table(['Area / exact Place ID','Principal Settlement IDs → final mass (share)','Residual final masses','Total'],principalRows.map(r=>[`${r.displayName} / ${r.placeId}`,r.candidates.filter(c=>c.principalRole).map(c=>`${c.settlementId} → ${c.weight} (${f(c.share)})`).join('; '),massKinds(r),r.totalMass]));
const principalDetail=n=>{const r=byName(n);return table(['Destination','Kind','Final integer mass','Share'],r.candidates.map(c=>[c.settlementId,c.kindId,c.weight,f(c.share)]))+`\n\nScope total **${r.totalMass}**. Exact principal budget **3/4**; residual **1/4**. ${massKinds(r)}. All destinations are positive, retained, and individually enumerated above.`;};
const rural=(names)=>table(['Area / Place','Candidate count','Total mass','Largest share','Smallest share','Disposition'],names.map(n=>{const r=byName(n);return [n+' / '+r.placeId,r.candidateCount,r.totalMass,f(r.largestShare),f(r.minimumShare),'Approve kind-only; no guessed principal or population claim.'];}));
const city=key=>{const c=a.scottishStress.cities.find(c=>c.key===key),r=byName(c.council.displayName);return `Council **${r.displayName} / ${r.placeId}**. Main Locality **${c.majorLocality.settlementId}** mass **${c.majorLocality.populationInCouncil} / ${r.totalMass}**, ${percent(c.majorLocality.shareOfCouncil)}. Other Localities **${c.otherLocalityPopulation}**; outside-locality administrative mass **${c.council.outsideLocalityPopulation}**.\n\n`+table(['Destination','Exact mass','Share'],r.candidates.map(x=>[x.settlementId||'Administrative-area only',x.weight,f(x.share)]))+`\n\nApprove raw counts. Uniform choice among the ${c.council.fragments.length} Locality fragments would give the major place 1/${c.council.fragments.length}; that content distortion is removed without inventing or rounding a new city share.`;};
const island=code=>{const c=a.scottishStress.islands.find(c=>c.councilCode===code),r=a.areas.find(r=>r.placeId===c.placeId);return `**${r.displayName} / ${r.placeId}**: ${c.insideLocalityPopulation} locality mass + **${c.outsideLocalityPopulation}** administrative mass = **${r.totalMass}**. Outside share **${f(c.outsideLocalityShare)}**, ${percent(c.outsideLocalityShare)}.\n\n`+table(['Exact destination','Mass','Share'],r.candidates.map(x=>[x.settlementId||'Administrative-area only',x.weight,f(x.share)]))+`\n\nApprove existing Localities plus measured outside-locality residual; no new island weighting, fine-place claim, geometry or crosswalk.`;};
const stress=['Bradford','Leeds','Swansea','Cornwall','North Yorkshire','Powys','Ceredigion','Fermanagh and Omagh','Mid Ulster'];
let out='# UK initial Residence placement content numerical approval v1\n\n';
out+='**APPROVED FOR IMPLEMENTATION. Approved specification only — NOT IMPLEMENTED, NOT PRODUCTION REGISTERED, NOT a frozen production artifact.** No Residence is established by this analysis. Frozen generic placement, Residence, Game root-v4, persistence, Population, Geography, Settlement, Country Start and New Game remain unchanged.\n\n';
out+=`Machine authority: [${filename}](${filename}), **${bytes.length} UTF-8 bytes**, SHA-256 **${sha}**. It contains all **361 scopes / 2,768 destinations**, literal weights, exact qualified references, lineage, sensitivity variants, flags and diagnostic witnesses. Its embedded canonical proposed policy uses the intended production ID solely for reproducibility analysis; no registry or application imports it. The proof fingerprint **${a.proposedCanonicalPolicy.fingerprint}** is not a released production manifest.\n\n`;
out+='This completes the previous numerical review rather than rewriting its historical analysis. The earlier Scottish four-city/28-coarse proposal is superseded by exact Census-derived masses for all 32 councils. Earlier documentation marked NOT APPROVED is historical evidence; this report and the newest PROJECT-STATE entry are the current content approval.\n\n';
out+=section(1,'Approval status','**APPROVED FOR IMPLEMENTATION**. Every numerical and precision decision is closed. Approval is for a separate immutable UK content implementation, not production registration in this task.');
out+=section(2,'Exact policy ID',`**${a.policyId}**. Repository namespaced version convention; no existing production registration was found in src. The identity becomes immutable when implemented/reviewed/frozen. No latest alias.`);
out+=section(3,'Effective date','**2024-06-30** is the compatible world/content date. Scottish evidence refers to **2022-03-20**, released with label **May 2024** (exact release day unasserted); publication landing page **2024-11-04** and access **2026-10-02** are separate metadata. England/Wales/NI masses have no empirical observation date.');
out+=section(4,'Pinned dependencies',table(['Contract','Exact identity / integrity'],[
 ['Geography',`${a.dependencies.geographyPartitions[0].id} / ${a.dependencies.geographyPartitions[0].fingerprint}`],
 ['Settlement',`${a.dependencies.settlementPackages[0].id} / ${a.dependencies.settlementPackages[0].fingerprint}; SHA-256 ${a.sourceManifest.productionDependencyPins.settlementArtifactSha256}; 3,269,891 bytes`],
 ['Frozen evaluator',a.algorithmId],['Authored methodology',a.authoredMethodologyId],
 ['NRS OA source',`${a.sourceManifest.source.sourceId}; 678,338 bytes; ${a.sourceManifest.source.sha256}`],
 ['Pinned Census index',`${a.sourceManifest.index.sourceId}; 2,922,015 bytes; ${a.sourceManifest.index.sha256}`],
 ['Future orchestration compatibility',`${a.orchestrationCompatibility.populationPackageId} / ${a.orchestrationCompatibility.populationFingerprint}; ${a.orchestrationCompatibility.populationArtifactSha256}`]
 ])+'\n\nPopulation is not a new dependency of the generic evaluator. Frozen Human content/profile and current Country Start remain unchanged. Exact index-member hashes, licences, paths and notices remain in sourceManifest.');
out+=section(5,'Country methodology split',table(['Country','Scopes','Settlement candidates','Administrative candidates','Mass classification'],Object.entries(a.summary.countrySummary).map(([c,s])=>[c,s.scopes,s.settlementCandidates,s.administrativeCandidates,c==='scotland'?'Derived from official published Census-2022 cells, adopted as an initialization prior':'Reviewed authored gameplay abstraction']))+'\n\nNo cross-country symmetry is imposed. Weights are relative within one scope, not a second Population authority or empirical probabilities of individual homes.');
out+=section(6,'England/Wales/NI kind table',table(['Existing opaque production kind ID','Exact base mass','Rationale'],Object.entries(a.kindMass).map(([k,v])=>[k,v,v===16?'City/town equality; 4× village, no legal-city population claim.':v===4?'4× hamlet; rural diversity remains positive.':'Small-place content remains reachable.']))+'\n\n`settlement.uk.nrs.census-locality` is **override-only raw count**, not base mass 1 or 16. All actual candidate kinds are covered. No universal real/synthetic multiplier.');
out+=section(7,'Principal-budget rule','Approve **3/4 principal, 1/4 residual**, explicit role units only. Let R be residual base-mass sum, P be principal role-unit sum, budget p/q=3/4. Raw principal candidate mass = p × role × R. Raw residual candidate mass = (q−p) × base × P. Divide the WHOLE group by its common GCD, once at build time. BigInt intermediates; narrow only after positive safe-integer validation. This produces the literal masses in the JSON; runtime evaluates integers, never percentages. A singleton is mass 1. Do not subsequently rescale literal masses because fingerprints/decisions depend on them.');
out+=section(8,'Complete principal inventory',fullPrincipalTable+'\n\n**16 overrides: England 8, Wales 4, NI 4, Scotland 0.** Every row has a 3/4 principal group and 1/4 positive residual. Bradford alone uses 4:2:1:1 internal roles; every other principal role is 1. There are no hidden overrides outside this table. Broad-authority anchors listed under the dilution audit retain kind-only; reviewed identity alone is insufficient to assert dominance.');
out+=section(9,'Bradford exact result',principalDetail('Bradford')+'\n\nApproved Bradford 1,476/3,936 = 3/8; Keighley 738/3,936 = 3/16; Shipley and Ilkley each 369/3,936 = 3/32. Residual 984/3,936 = 1/4. Role numbers are authored, never measured population ratios.');
out+=section(10,'Leeds exact result',principalDetail('Leeds')+'\n\nLeeds 591/788 = 3/4. All 32 residual destinations survive: seven town masses 16, twenty village masses 4, five hamlet masses 1. No Leeds district-to-city equivalence is claimed.');
out+=section(11,'Swansea exact result',principalDetail('Swansea')+'\n\nSwansea 345/460 = 3/4. All 13 residual destinations survive: six town masses 16, four village masses 4, three hamlet masses 1.');
out+=section(12,'Compact-singleton inventory',table(['Exact Place / area','Exact Settlement ID','Mass'],a.compactSingletonInventory.map(r=>[r.placeId+' / '+r.displayName,r.settlementId,r.weight]))+'\n\n**53 exact Settlement singletons**: England 51 (including London 33), Wales 1, NI 1. These are approved content precision choices within the frozen inventory, not proof of empirical habitation exhaustion. No artificial administrative residual.');
out+=section(13,'London result','All **33** `place.uk.local-admin.e09000001` through `e09000033` retain the exact frozen `intersects` mapping to **settlement.uk.reviewed.london**, mass **1**, share **1/1**. The borough/cell remains the administrative reference. There is no global London administrative Place, area reassignment or inferred Presence.');
out+=section(14,'City of London','**place.uk.local-admin.e09000001 → settlement.uk.reviewed.london**, mass **1**, share **1/1**. Exact City of London scope remains distinct from the other 32 scoped London destinations.');
out+=section(15,'Cardiff','**place.uk.local-admin.w06000015 → settlement.uk.reviewed.cardiff**, mass **1**, share **1/1**. One reviewed Cardiff and zero synthetic Settlement candidates; no invented residual.');
out+=section(16,'Belfast','**place.uk.local-admin.n09000003 → settlement.uk.reviewed.belfast**, mass **1**, share **1/1**. One reviewed Belfast and zero synthetic Settlement candidates; no invented residual.');
out+=section(17,'Isles of Scilly','Approve **B: administrative-only**, `place.uk.local-admin.e06000053`, mass **1**, share **1/1**. The frozen Hugh Town identity remains available Settlement content but is deliberately not an initial destination here; its exact ID is retained in areas[].excludedSettlementCandidates. Assuming it exhausts inhabited Scilly would overstate precision. No new England OA evidence route or arbitrary split.');
out+=section(18,'Rural England',rural(['Cornwall','North Yorkshire','Rutland','Maldon','North Warwickshire'])+'\n\nCornwall has four towns ×16, fourteen villages ×4, five hamlets ×1 =125. North Yorkshire has four towns ×16, seventeen villages ×4, four hamlets ×1 =136. Collective rural mass may exceed one town because it spans many destinations; no principal city is asserted. Rutland 16:4 (80%) and Maldon/North Warwickshire 16:4:1 (16/21 largest) are deliberately sparse positive kind mixes, reviewed rather than silently capped.');
out+=section(19,'Rural Wales',rural(['Powys','Ceredigion','Gwynedd'])+'\n\nPowys: one town16, five villages4, two hamlets1 =38. Ceredigion: reviewed Aberystwyth16, three villages4, one hamlet1 =29; no 75% dominance assertion over the county. Gwynedd retains broad-area kind-only. Swansea/Wrexham/Newport/Merthyr are the only explicit Welsh principal overrides.');
out+=section(20,'Rural Northern Ireland',rural(['Fermanagh and Omagh','Mid Ulster','Armagh City, Banbridge and Craigavon','Causeway Coast and Glens','Mid and East Antrim'])+'\n\nFermanagh/Omagh: Enniskillen16, Omagh16, two authored towns16, one village4, two hamlets1 =70. Both reviewed towns get 8/35; no single principal is inferred. Mid Ulster uses three towns16, four villages4, two hamlets1 =66. Distinct named anchors do not force guessed LGD population weights.');
out+=section(21,'Scotland mass-source decision','Use only the verified official NRS **Output Area 2022 Total Population** CSV joined exactly to OA2022/CA2019/CLOC2022 in the pinned index, through the existing frozen code continuity mappings. No new population series, geometry, crosswalk or fuzzy matching. Every contributing OA is counted once. Official published Census cells → exact aggregation → adoption as placement prior are distinct epistemic steps. NRS has not endorsed Turning Pages placement.');
out+=section(22,'Scottish exact-count decision',`Approve **A: exact aggregated counts**, no GCD reduction, compression, rounded shares or aesthetic transformation. Largest candidate **${a.summary.scotland.maximumCandidateMass}**, largest scope **${a.summary.scotland.maximumScopeMass}**, all positive safe integers. Exact source ratios survive unchanged; the generic weight field is not renamed population. The official cells are 2022 evidence, not 2024 Locality estimates or individual Residence truth. Published-cell sum **5,440,284** is not represented as a separately acquired headline total; this CSV's exact disclosure-control treatment remains unasserted.`);
out+=section(23,'Scottish locality candidate count','**662** Council × Locality fragments representing **656** continuing NRS Locality Settlement identities. Every one mechanically resolves to the exact Settlement package, council Place, country and frozen contained-by/intersects relation. Exact names are display only, never join keys.');
out+=section(24,'Scottish admin-only candidate count','**32**, each positive. **Zero councils have zero outside-locality residual.** If a future source has zero, omit that candidate; no zero weight is persisted. These are explicit evidence-supported administrative precision, not errors, emergency fallback or guessed rural settlements.');
out+=section(25,'Scottish total candidate count','**694 =662 Locality fragments +32 administrative residuals**. All 32 council scopes now have precise complete candidate sets; remove every prior Scottish authored principal override and 28 admin-only-only proposals.');
out+=section(26,'Scottish total mass','**5,440,284 =4,957,121 locality-covered +483,163 outside-locality**. Census reference **2022-03-20**. This mass is never reconciled to the frozen mid-2024 Scottish population 5,546,900, never changes Population and is never compared with an English scope mass.');
out+=section(27,'Scottish conservation',table(['Council / Place','Locality mass','Outside/admin mass','Exact scope total'],a.areas.filter(r=>r.constituentCountry==='scotland').map(r=>[r.displayName+' / '+r.placeId,r.candidates.filter(c=>c.settlementId).reduce((n,c)=>n+c.weight,0),r.candidates.find(c=>!c.settlementId).weight,r.totalMass]))+'\n\nAll 32 per-council equalities and the aggregate equality pass. All 46,363 OAs match, 42,379 inside and 3,984 outside. There is no unexplained loss or double counting.');
out+=section(28,'Glasgow result',city('glasgow'));
out+=section(29,'Edinburgh result',city('edinburgh'));
out+=section(30,'Aberdeen result',city('aberdeen'));
out+=section(31,'Dundee result',city('dundee'));
out+=section(32,'Orkney result',island('S12000023'));
out+=section(33,'Shetland result',island('S12000027'));
out+=section(34,'Na h-Eileanan Siar result',island('S12000013'));
out+=section(35,'Cross-boundary result',table(['Locality / exact Settlement','Qualified fragments: exact Place → mass','Conserved total'],a.crossBoundaryScottishLocalities.map(l=>[l.productionDisplayName+' / '+l.settlementId,l.councilFragments.map(x=>x.placeId+' → '+x.population).join('; '),l.population]))+'\n\nAll six conserve exactly. The same durable Settlement remains distinct destinations in its two scoped councils; neither whole Locality population nor display name is substituted for fragment mass.');
out+=section(36,'UK administrative-only inventory',table(['Exact Place / area','Mass','Within-scope share','Provenance'],a.administrativeInventory.map(r=>[r.placeId+' / '+r.displayName,r.weight,f(r.share),r.provenanceClass]))+'\n\n**33 total**: Scotland32 residuals; Scilly1 authored precision choice. No other non-Scottish administrative-only candidate.');
out+=section(37,'Country-only result','**Zero**. Each valid UK initial request already has one exact Population allocation area. No unknown-country/area inference or country-level fallback.');
out+=section(38,'Childhood/adult result','Approve the same geographic policy for age0 and age18. Age and mode do not occur in evaluator keys. If Population selects different areas, each uses its corresponding group; this does not assert identical geographic outcomes across different scopes.');
out+=section(39,'One-Residence result','Approve exactly one geographic Residence decision and, in later explicit orchestration, one frozen establishResidence transaction for the eligible living instantiated Person. The evaluator alone establishes nothing. No multiple homes, Dwelling, tenure, Household or institutional placement.');
out+=section(40,'No-fixed-abode result','Not used by UK initial placement v1. Existing Residence eligibility/no-fixed-abode checks remain external; do not clear or replace markers implicitly.');
out+=section(41,'Presentation-override result','Name and genderLabel overrides have **no effect** on placement. Neither is accepted by the frozen request schema or included in derivation keys. No demographic or biological inference.');
out+=section(42,'Entropy result','**No additional platform entropy** or mutable RNG consumption. Explicit existing uint32 rootSeed feeds the frozen keyed evaluator. No Date.now, Math.random, UUID, mutable stream or new Clock change.');
out+=section(43,'Request-key result','Exact request: `{version:1, policyId, personId, rootSeed, scope:{version:1,partitionId,placeId}}`. Key material includes frozen algorithm/policy fingerprint, Person and exact scope; rootSeed is a separate derivation input. No name, gender, age, scenario/UI order. The key is not a globally unique receipt across worlds. No new ledger; external Residence orchestration must check existing state and commit atomically.');
out+=section(44,'History result','**No initial ordinary player-facing History event**. Initial authored state is not a recorded historical move or evidence of the real Person home. Build provenance stays external.');
out+=section(45,'Domain Event result','**No bootstrap residence-established Domain Event**, no Causality or Scheduler work. Future runtime moves are separate unimplemented semantics.');
out+=section(46,'Policy-ID persistence result','**No placementPolicyId root field**. Once explicit placement commits, the existing ResidenceLocationRef is state authority. Policy/build evidence remains immutable external content. No schema, migration, recovery or storage changes.');
out+=section(47,'Old-save result','Old/migrated Games keep empty Residence. Never retroactively apply the policy on load, upgrade or query. Loading existing Residence requires exact referenced Geography/Settlement content, not re-running placement.');
out+=section(48,'NPC reuse result','Later explicit NPC materialization MAY invoke the same policy with canonical Population area context. Household/family orchestration may instead join an existing Residence. No query-triggered placement, automatic generation or NPC behaviour now.');
out+=section(49,'Exact UK candidate count','**2,768 =2,735 eligible Settlement destinations +33 administrative candidates**. Available frozen qualified Settlement destinations=2,736. Exclude Hugh Town1; add Scottish outside-locality32 and Scilly administrative1: 2,736−1+32+1=2,768. Scotland694, England1,811, Wales166, NI97. Duplicate durable IDs across legitimate exact scopes are qualified destinations, not duplicate selection opportunities.');
out+=section(50,'361-scope audit',table(['Area / exact Place','Candidates','Rule','Total mass','Largest share','Second share','Reviewed flags'],a.areas.map(r=>[r.displayName+' / '+r.placeId,r.candidateCount,r.rule,r.totalMass,f(r.largestShare),f(r.secondLargestShare),r.flags.map(f=>f.id).join('; ')||'None']))+'\n\nThe JSON contains every exact destination, mass, source/decision lineage, provenance class, principal role and implied rational share. Canonical groups and candidates use frozen code-point tuple ordering; no data is hidden behind defaults or unresolved formulas.');
out+=section(51,'Dominance audit',table(['Area / Place','Flag','Decision / rationale'],a.dominanceAudit.flagInventory.map(r=>[r.displayName+' / '+r.placeId,r.id,r.decision+': '+r.reason]))+'\n\n54 intentional single destinations (53 compact +Scilly), 7 largest-above75% flags (3 sparse authored mixes +4 evidence-backed major cities), 8 low-anchor flags and 3 sub-per-thousand flags. Every flag reviewed; unresolved=0. Renfrewshire Glasgow fragment176, Perth/Kinross Kelty147 and GlasgowCity Stepps507 are genuine small qualified evidence fragments, not accidental dilution. All receive diagnostic witnesses. Broad-authority anchor weights are not promoted from identity alone; Bath, Chester, Bournemouth, Carlisle, Armagh/Craigavon, Coleraine, Enniskillen/Omagh and Ballymena retain explicit kind-only decisions.');
out+=section(52,'Principal sensitivity',table(['Area','Budget','Exact principal masses','Total mass'],a.principalSensitivity.map(s=>[s.displayName,f(s.principalBudget),s.candidates.filter(c=>Object.hasOwn(a.principalOverrides[s.placeId.split('.').at(-1)],c.settlementId)).map(c=>`${c.settlementId} → ${c.weight} (${f(c.share)})`).join('; '),s.totalMass]))+'\n\n65%,70%,75%,80% all remain exact and positive. Bradford shares for its principal roles are respectively (32.5,16.25,8.125,8.125), (35,17.5,8.75,8.75), (37.5,18.75,9.375,9.375), (40,20,10,10) percent. Residual budgets are35%,30%,25%,20%. Choose75% as the simple 3:1 authored compromise: protects explicit principal roles while retaining a substantial1/4 peripheral budget; 65/70 dilute principal intent,80 further suppresses the intentionally playable residual. None is an empirical optimum; do not tune to samples. All alternative literal candidate masses are in the JSON.');
out+=section(53,'Kind sensitivity',table(['Area','Variant','Scope mass','Largest share','Smallest share'],a.kindSensitivity.flatMap(s=>s.areas.filter(r=>stress.includes(r.displayName)).map(r=>[r.displayName,s.id,r.totalMass,f(r.largestShare),f(r.minimumShare)])))+'\n\nApprove16/4/1 over modest16/5/1 and12/4/1 alternatives. Raising village mass or lowering town mass increases collective small-place dilution without new evidence; fixed principal budgets correctly remain unchanged. The geometric4× steps are simpler to explain, preserve rural reachability and give authored towns appropriate qualitative emphasis. This is a reviewed modelling choice, not statistical model fitting. All328 eligible non-Scottish scope variants are retained in JSON; Scilly has no kind weights.');
out+=section(54,'Diagnostic simulation',`**${a.diagnostics.baseEvaluations.toLocaleString('en-GB')}** pure selections =361 ×4,096; seeds0,1,42,2024 and person:1..1024 per scope. **All2,768 destinations hit at least once**, zero base misses, zero supplemental draws, zero diagnostic standardized-difference warnings above absolute6. Exact expected-count fractions and deterministic witnesses are recorded per candidate. Every decision keeps its exact administrative area; pinned retries match. Positive cumulative intervals also establish theoretical ticket support independently of finite sampling. Diagnostic floating percentages/z-scores never participate in mass construction, selection, acceptance or policy semantics. Samples are software/content diagnostics, not proof of real Residence distribution.`);
out+=section(55,'Reverse-order determinism','Reversed and deterministically interleaved/shuffled groups AND candidate records normalize to byte-identical canonical proposed policy and identical fingerprint. Four pinned requests per scope produce identical decisions in original/reversed/shuffled runtimes; repeated requests are identical. Independently rerun the research generator in --verify mode for full report byte equality. Existing Scottish OA aggregation independently verifies population/index reversal.');
out+=section(56,'Canonical policy validation',`Frozen withResidencePlacementPolicyFingerprint +validateResidencePlacementPolicy +createResidencePlacementRuntime PASS for361 unique scopes, all2,768 positive safe weights, no duplicate destinations, all exact pins/country/relation references, no wrong-area candidate and no unsafe scope sum. Proposed proof fingerprint **${a.proposedCanonicalPolicy.fingerprint}**. Runtime Maps are disposable closure-private derivatives; no mutable index is attached to the canonical policy or approval report. Authored scope masses range1..3,936; Scottish scope masses21,977..620,870. Scope-local selection makes magnitude differences irrelevant.`);
out+=section(57,'Provenance result','Finite mass classes: authored-kind-base; authored-principal-override (including its residual allocation); authored-compact-singleton; authored-admin-only-precision; census-2022-locality-fragment; census-2022-outside-locality-admin. Every candidate has one. Real/synthetic Settlement lineage does not introduce a universal multiplier. Preserve official source identity separately from Turning Pages mapping, aggregation and authored adoption. No false2024 precision, individual-home evidence or NRS endorsement.');
out+=section(58,'Future integrity assertions','Immutable build assertions: exact source byte lengths/SHA-256 and index-member hashes; exact46363 unique OA match,656 Localities,32 councils,662 fragments; inside4,957,121, outside483,163, sum5,440,284; every council and six cross-boundary sums; all expected361 exact cells; all2735 qualified Settlement candidates and33 admin candidates; all weights positive/safe; all kinds mapped; exact16 principal overrides/roles/budgets/final literal masses; exact53 singleton/Scilly decisions; exact dependencies/relations; no duplicates, empty group, unused pin or unreviewed override; canonical rebuild/source-order equality. Source counts/conservation are acceptance invariants. Samples, implied percentages, z-scores and timings are diagnostic only, not fitted or brittle acceptance thresholds.');
out+=section(59,'Future artifact plan','Separate implementation files, following country-content conventions: `src/data/residence/uk/initial-mid-2024/{policy-input.json,area-role-review.json,source-manifest.json,compiled-policy.json,policy-manifest.json,build-report.json,stress-report.json,adapter.ts,adapter.test.ts}`; `scripts/build-uk-initial-residence-placement.mjs`, `scripts/verify-uk-initial-residence-placement.mjs`. Reuse the pinned source bytes rather than download a different release. Runtime adapter only loads/verifies immutable compiled generic policy and manifest, never parses OA evidence or invents weights. Keep provenance/dates/checksums external; no generic schema extension. Development/candidate manifests do not register the production ID until ALL implementation integrity/review gates pass. No orchestration in this content phase.');
out+=section(60,'Versioning rule','After freeze, any weight, candidate, role, precision, dependency, evidence checksum or methodology correction requires a NEW policy ID/version and reviewed manifest. No in-place numerical correction. Frozen FNV covers exact generic semantics including policyID and literal weights, not external metadata; separate SHA-256/manifests bind source bytes and methodology to the immutable production identity. Even a changed source checksum that happens to yield equal weights must trigger new content identity through release policy. FNV is accidental integrity, not cryptographic security; artifact SHA-256 is distinct. Future implementation computes/freezes artifact SHA and reproduces the analysis semantics fingerprint; no production release is claimed now.');
out+=section(61,'Country Start boundary','Country Start v3 **NOT IMPLEMENTED**. After content implementation and separate freeze, future v3 may pin Populationv3, current Geography, Settlementv2, placementv1, Human content and the existing world/date. It will translate canonical membership area, check living Person and existing Residence/status, evaluate, establish through frozen Residence, validate candidate root and commit atomically. It must neither modify memberships nor create new demographic counts. Current v1/v2 constructors remain unchanged and create empty Residence.');
out+=section(62,'New Game boundary','**UNCHANGED**. Still country-start.uk.mid-2024-v2 / uk.population.mid-2024.v3 with empty Residence. A routing change requires placement implementation/freeze, Country Startv3 implementation/freeze, then separate routing review. No UI field, seed, routing, persistence or compatibility change here.');
out+=section(63,'Research artifacts created','This Markdown report; complete numerical approval JSON; reproducible research-only `research/uk-residence-numerical-approval/analyse.mjs` and `render.mjs`. They are not production builders/adapters/registries. Only PROJECT-STATE receives a new current-status entry. Earlier review/evidence files and frozen source bytes remain intact. No production policy file is added.');
out+=section(64,'Content-integrity result','Fresh PASS: Scottish evidence generator --verify reconstructs its exact754,648-byte report/SHA; all four production content gates pass (Human, Geography, geographic Populationv3, hybrid Settlementv2); **35 frozen placement tests /3files pass**. Frozen src paths/bytes aggregateSHA-256 remains **5a2c406a6b9d88902e3c8a407062ea07bf08bd71fef2cfd6cdee3daf66beb989**. No production registration match exists in src. Full Vitest, TypeScript/build, browsers and heavy simulation gates are NOT newly rerun or claimed for this content-only design task; preceding freeze evidence remains historical. Initial local test-launch PATH/config sandbox obstacles were resolved by directly running the existing test runner with authorized local access, without source/config changes.');
out+=section(65,'Remaining unresolved numerical issues','**None**. Authoring uncertainty and2022-vs2024 limitations are disclosed choices, not unspecified numbers. Remaining work is implementation/integrity/freeze and subsequent orchestration, not another evidence acquisition or numerical research loop. Known sparse real-anchor inventory and authored world depth remain frozen content limitations. Household, Housing, Presence, Travel, dynamic demography, addresses and individual-home inference remain deferred.');
const answers=[
 ['A','Exact policy ID',a.policyId],['B','Exact date','2024-06-30 (compatibility, not all-source observation date)'],['C','Geography',a.dependencies.geographyPartitions[0].id+' / '+a.dependencies.geographyPartitions[0].fingerprint],['D','Settlement',a.dependencies.settlementPackages[0].id+' / '+a.dependencies.settlementPackages[0].fingerprint],['E','Population area invariant','APPROVED: initial administrative reference exactly equals membership area; never cross scopes'],['F','Base weights','Exact five-kind table in section6: city/reviewed-town/authored-town16; village4; hamlet1'],['G','Bradford','1476,738,369,369 principals; residual5×128,10×32,3×8; total3936'],['H','Leeds','591; residual7×16,20×4,5×1; total788'],['I','Swansea','345; residual6×16,4×4,3×1; total460'],['J','Other principals','13 additional exact overrides in section8; total16, none hidden'],['K','London','33 exact scoped intersects destinations, London mass1 per group'],['L','Cardiff','One exact Settlement, mass1'],['M','Belfast','One exact Settlement, mass1'],['N','Scilly','Administrative-only mass1; Hugh Town not selected'],['O','Scotland counts','Exact raw published-cell aggregates; NO transformation/reduction'],['P','Scottish admin rule','Positive outside-locality council count → explicit admin-only weight; omit zero'],['Q','Scottish candidates','694 =662+32'],['R','Scottish mass','5,440,284'],['S','Cross-boundary','Six Localities retained as separately weighted exact council-qualified fragments'],['T','Islands','Raw Locality fragments +positive outside admin counts; no authored island weights'],['U','Non-Scottish admin','Scilly ONLY'],['V','Country-only','ZERO'],['W','Childhood/adult','Same policy; age/mode absent from keys'],['X','One initial Residence','YES, later explicit orchestration; evaluator creates no state'],['Y','No-fixed-abode used','NO'],['Z','History','NONE'],['AA','Domain Events','NONE'],['AB','Policy ID in Game','NO'],['AC','Retroactive old-save placement','NO'],['AD','NPC reuse','YES, explicit later invocation; household join may supersede; no query placement'],['AE','Extra entropy','NONE'],['AF','All361 numerically specified','YES; all2768 destination masses literal and canonical'],['AG','Generic schema change','NONE'],['AH','Further research','NONE REQUIRED'],['AI','Numerical model approved','YES — APPROVED FOR IMPLEMENTATION'],['AJ','Next task','IMPLEMENT IMMUTABLE UK RESIDENCE PLACEMENT CONTENT v1; no Country Startv3/routing yet']
];
out+=section(66,'Explicit answers A–AJ',table(['Answer','Question','Final decision'],answers));
out+=section(67,'Final numerical approval decision','**APPROVED FOR IMPLEMENTATION.** Exact identity/date/pins, authored methodology/table/principals, all Scottish raw fragments/residuals, all33 admin candidates, all361 scopes and all2768 positive safe masses are closed and verified using frozen APIs. No unresolved precision, generic schema change or further acquisition is required. This approval is NOT a production package freeze/registration and does not enable placement.');
out+=section(68,'Exact next task','**IMPLEMENT IMMUTABLE UK RESIDENCE PLACEMENT CONTENT v1** from this approved specification: strict source-byte gates, exact generated compiled generic policy, external provenance/review manifest, immutable content adapter/registry, all-scope integrity and deterministic build tests, followed by a separate final freeze review. Do NOT implement Country Startv3, alter New Game or establish actual Residence as part of that content task.');
out+='\nThe approval JSON is the complete proposed numerical source of truth. Human tables and report sections are rendered from it; independent text logic never selects different candidates, weights or outcomes. Research verification commands: `node research/scotland-residence-2022/check-evidence.mjs --verify`; `node research/uk-residence-numerical-approval/analyse.mjs --verify`; `node research/uk-residence-numerical-approval/render.mjs --verify`.\n';
const destination=path.join(root,'UK-INITIAL-RESIDENCE-PLACEMENT-NUMERICAL-APPROVAL.md');
if(process.argv.includes('--verify')){if(fs.readFileSync(destination,'utf8')!==out)throw Error('Human approval report differs');}else fs.writeFileSync(destination,out);
console.log(JSON.stringify({reportBytes:Buffer.byteLength(out),numberedSections:68,answers:answers.length,sha256:crypto.createHash('sha256').update(out).digest('hex')}));
