import {afterEach,describe,expect,it} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {createGame} from '../engine/simulation';
import {deletePersistenceDatabase,IndexedDbSaveRepository,PersistenceRepositoryError,type IndexedDbFaults} from './indexedDb';
import {prepareCanonicalRecord,recordFromRaw,verifyRecord} from './payload';
import {PREVIOUS_SLOT,PRIMARY_SLOT} from './record';

let sequence=0;const created:{factory:IDBFactory;name:string;repo?:IndexedDbSaveRepository}[]=[];
async function repository(faults?:IndexedDbFaults){const factory=new IDBFactory(),name=`test-${++sequence}`,repo=await IndexedDbSaveRepository.open(factory,name,faults);created.push({factory,name,repo});return repo;}
afterEach(async()=>{for(const item of created.splice(0)){item.repo?.close();await deletePersistenceDatabase(item.factory,item.name).catch(()=>{});}});

describe('IndexedDbSaveRepository',()=>{
  it('creates, closes and reopens its database',async()=>{const factory=new IDBFactory(),name=`reopen-${++sequence}`,first=await IndexedDbSaveRepository.open(factory,name),record=(await prepareCanonicalRecord(createGame('Reopen','Any','ca',1),PRIMARY_SLOT,'primary',1)).record;await first.commitSave(record,null);first.close();const second=await IndexedDbSaveRepository.open(factory,name);created.push({factory,name,repo:second});expect((await verifyRecord(await second.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Reopen');});
  it('atomically rotates primary to a correctly labelled previous record',async()=>{const repo=await repository(),first=(await prepareCanonicalRecord(createGame('One','Any','ca',2),PRIMARY_SLOT,'primary',1)).record,second=(await prepareCanonicalRecord(createGame('Two','Any','ca',3),PRIMARY_SLOT,'primary',2)).record;expect(await repo.commitSave(first,null)).toBe(1);expect(await repo.commitSave(second,1)).toBe(2);const previous=await verifyRecord(await repo.getRecord(PREVIOUS_SLOT),PREVIOUS_SLOT);expect(previous.record).toMatchObject({slotId:'previous',role:'previous',revision:1});expect(previous.result.game?.name).toBe('One');expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Two');});
  it('round-trips ArrayBuffer bytes without exposing IndexedDB authority through read aliases',async()=>{const repo=await repository(),record=(await prepareCanonicalRecord(createGame('Owned bytes','Any','ca',22),PRIMARY_SLOT,'primary',1)).record;await repo.commitSave(record,null);const first=await repo.getRecord(PRIMARY_SLOT) as {payload:ArrayBuffer},expected=[...new Uint8Array(first.payload)];new Uint8Array(first.payload).fill(0);const reread=await repo.getRecord(PRIMARY_SLOT) as {payload:ArrayBuffer};expect([...new Uint8Array(reread.payload)]).toEqual(expected);expect((await verifyRecord(reread,PRIMARY_SLOT)).result.game?.name).toBe('Owned bytes');});
  it('snapshots prepared bytes before asynchronous commit and rejects pre-commit mutation',async()=>{const repo=await repository(),record=(await prepareCanonicalRecord(createGame('Snapshot','Any','ca',23),PRIMARY_SLOT,'primary',1)).record,pending=repo.commitSave(record,null);new Uint8Array(record.payload).fill(0);await pending;expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Snapshot');const damaged=(await prepareCanonicalRecord(createGame('Damaged','Any','ca',24),PRIMARY_SLOT,'primary',2)).record;new Uint8Array(damaged.payload)[0]^=1;await expect(repo.commitSave(damaged,1)).rejects.toMatchObject({reason:'invalid-record'});expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Snapshot');});
  it('rejects revision conflicts without changing either current slot',async()=>{const repo=await repository(),first=(await prepareCanonicalRecord(createGame('Authority','Any','ca',4),PRIMARY_SLOT,'primary',1)).record;await repo.commitSave(first,null);const conflict=(await prepareCanonicalRecord(createGame('Stale','Any','ca',5),PRIMARY_SLOT,'primary',1)).record;await expect(repo.commitSave(conflict,null)).rejects.toMatchObject({reason:'conflict'});expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Authority');expect(await repo.getRecord(PREVIOUS_SLOT)).toBeUndefined();});
  it('aborts all writes on injected failure and preserves write-once recovery',async()=>{let abort=false;const repo=await repository({afterWrites:tx=>{if(abort)tx.abort();}}),first=(await prepareCanonicalRecord(createGame('Kept','Any','ca',6),PRIMARY_SLOT,'primary',1)).record;await repo.commitSave(first,null);abort=true;const second=(await prepareCanonicalRecord(createGame('Lost','Any','ca',7),PRIMARY_SLOT,'primary',2)).record,recovery=await recordFromRaw('recovery:test','recovery',null,'legacy-exact-bytes',JSON.stringify(createGame('Recovery','Any','ca',8)));await expect(repo.commitSave(second,1,[recovery])).rejects.toBeInstanceOf(PersistenceRepositoryError);expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Kept');expect(await repo.getRecord(PREVIOUS_SLOT)).toBeUndefined();expect(await repo.getRecord('recovery:test')).toBeUndefined();});
  it('reports quota failures without replacing the primary',async()=>{let quota=false;const repo=await repository({beforeWrites:()=>{if(quota)throw new DOMException('quota','QuotaExceededError');}}),first=(await prepareCanonicalRecord(createGame('Kept','Any','ca',9),PRIMARY_SLOT,'primary',1)).record;await repo.commitSave(first,null);quota=true;const second=(await prepareCanonicalRecord(createGame('No room','Any','ca',10),PRIMARY_SLOT,'primary',2)).record;await expect(repo.commitSave(second,1)).rejects.toMatchObject({reason:'quota'});expect((await verifyRecord(await repo.getRecord(PRIMARY_SLOT),PRIMARY_SLOT)).result.game?.name).toBe('Kept');});
  it('does not overwrite an existing recovery slot',async()=>{const repo=await repository(),first=(await prepareCanonicalRecord(createGame('One','Any','ca',11),PRIMARY_SLOT,'primary',1)).record,old=await recordFromRaw('recovery:test','recovery',null,'legacy-exact-bytes',JSON.stringify(createGame('Old recovery','Any','ca',12)));await repo.commitSave(first,null,[old]);const second=(await prepareCanonicalRecord(createGame('Two','Any','ca',13),PRIMARY_SLOT,'primary',2)).record,replacement=await recordFromRaw('recovery:test','recovery',null,'legacy-exact-bytes',JSON.stringify(createGame('Replacement','Any','ca',14)));await repo.commitSave(second,1,[replacement]);expect((await verifyRecord(await repo.getRecord('recovery:test'),'recovery:test')).result.game?.name).toBe('Old recovery');});
});
