import {describe,expect,it} from 'vitest';
import {createGame} from '../engine/simulation';
import {asPreviousRecord,isStoredSaveRecordV1,PREVIOUS_SLOT,PRIMARY_SLOT} from './record';
import {exactOwnedArrayBuffer,prepareCanonicalRecord,recordFromRaw,sha256Bytes,sha256Text,verifyRecord} from './payload';

describe('StoredSaveRecordV1',()=>{
  it('prepares and verifies canonical UTF-8 ArrayBuffer bytes with SHA-256',async()=>{const prepared=await prepareCanonicalRecord(createGame('Canonical','Any','ca',1),PRIMARY_SLOT,'primary',1);expect(isStoredSaveRecordV1(prepared.record,PRIMARY_SLOT)).toBe(true);expect(prepared.record.payload).toBeInstanceOf(ArrayBuffer);expect(prepared.record.byteLength).toBe(new TextEncoder().encode(prepared.raw).byteLength);expect(prepared.record.sha256).toMatch(/^sha256:[0-9a-f]{64}$/);expect((await verifyRecord(prepared.record,PRIMARY_SLOT)).result.game).toEqual(prepared.game);});
  it('copies the exact byte view and does not retain source aliases',async()=>{const backing=new Uint8Array([99,10,20,30,88]),view=backing.subarray(1,4),owned=exactOwnedArrayBuffer(view);expect([...new Uint8Array(owned)]).toEqual([10,20,30]);backing.fill(0);expect([...new Uint8Array(owned)]).toEqual([10,20,30]);expect(await sha256Bytes(new Uint8Array(owned))).toBe(await sha256Bytes(new Uint8Array([10,20,30])));const text='same canonical bytes';expect(await sha256Bytes(new Uint8Array(exactOwnedArrayBuffer(new TextEncoder().encode(text))))).toBe(await sha256Text(text));});
  it('rotates primary metadata while preserving exact payload identity',async()=>{const primary=(await prepareCanonicalRecord(createGame('Previous','Any','ca',2),PRIMARY_SLOT,'primary',7)).record,previous=asPreviousRecord(primary);expect(previous).toMatchObject({slotId:PREVIOUS_SLOT,role:'previous',revision:7,sha256:primary.sha256,byteLength:primary.byteLength});expect(previous.payload).toBe(primary.payload);expect(isStoredSaveRecordV1(previous,PREVIOUS_SLOT)).toBe(true);});
  it('rejects mismatched key, slot and role combinations',async()=>{const primary=(await prepareCanonicalRecord(createGame('Mismatch','Any','ca',3),PRIMARY_SLOT,'primary',1)).record;expect(isStoredSaveRecordV1({...primary,role:'previous'},PRIMARY_SLOT)).toBe(false);expect(isStoredSaveRecordV1({...primary,slotId:PREVIOUS_SLOT},PREVIOUS_SLOT)).toBe(false);expect(isStoredSaveRecordV1({...primary,slotId:'recovery:x',role:'recovery',revision:1},'recovery:x')).toBe(false);expect(isStoredSaveRecordV1(primary,PREVIOUS_SLOT)).toBe(false);});
  it('detects length and checksum corruption and unsupported metadata',async()=>{const prepared=await prepareCanonicalRecord(createGame('Integrity','Any','ca',4),PRIMARY_SLOT,'primary',1),record=prepared.record;await expect(verifyRecord({...record,byteLength:record.byteLength+1},PRIMARY_SLOT)).rejects.toMatchObject({reason:'byte-length-mismatch'});await expect(verifyRecord({...record,sha256:`sha256:${'0'.repeat(64)}`},PRIMARY_SLOT)).rejects.toMatchObject({reason:'checksum-mismatch'});await expect(verifyRecord({...record,persistenceVersion:2},PRIMARY_SLOT)).rejects.toMatchObject({reason:'unsupported-persistence-version'});await expect(verifyRecord({...record,encoding:'future'},PRIMARY_SLOT)).rejects.toMatchObject({reason:'unsupported-encoding'});});
  it('rejects Blob, File, typed-array, SharedArrayBuffer, detached buffers and unsupported ArrayBuffer prototypes',async()=>{const record=(await prepareCanonicalRecord(createGame('Binary type','Any','ca',41),PRIMARY_SLOT,'primary',1)).record,detached=new ArrayBuffer(1);structuredClone(detached,{transfer:[detached]});for(const payload of [new Blob(['x']),typeof File==='undefined'?{}:new File(['x'],'x'),new Uint8Array(1),typeof SharedArrayBuffer==='undefined'?{}:new SharedArrayBuffer(1),detached,Object.setPrototypeOf(new ArrayBuffer(record.byteLength),null)])expect(isStoredSaveRecordV1({...record,payload},PRIMARY_SLOT)).toBe(false);});
  it('preserves exact legacy bytes without requiring canonical equality',async()=>{const raw=` ${JSON.stringify(createGame('Legacy bytes','Any','ca',5),null,2)} `,record=await recordFromRaw('recovery:test','recovery',null,'legacy-exact-bytes',raw),verified=await verifyRecord(record,'recovery:test');expect(verified.raw).toBe(raw);expect(verified.result.game?.name).toBe('Legacy bytes');});
});
