import {describe,expect,it} from 'vitest';
import {createGame} from '../engine/simulation';
import {SaveCoordinator} from './saveCoordinator';

const deferred=<T>()=>{let resolve!:(value:T)=>void,reject!:(reason?:unknown)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
describe('SaveCoordinator',()=>{
  it('keeps one active and only the newest pending Game',async()=>{const calls:string[]=[],first=deferred<number>(),saver=(game:ReturnType<typeof createGame>)=>{calls.push(game.name);return calls.length===1?first.promise:Promise.resolve(2);},coordinator=new SaveCoordinator(saver,0);coordinator.request(createGame('First','Any','ca',1));coordinator.request(createGame('Skipped','Any','ca',2));const latest=coordinator.persist(createGame('Latest','Any','ca',3));expect(calls).toEqual(['First']);first.resolve(1);await latest;expect(calls).toEqual(['First','Latest']);expect(coordinator.snapshot).toMatchObject({state:'saved',revision:2,dirty:false});});
  it('leaves the newest state dirty after failure and retry saves it',async()=>{let fail=true;const calls:string[]=[],coordinator=new SaveCoordinator(async game=>{calls.push(game.name);if(fail)throw Error('offline');return 1;},null),game=createGame('Dirty','Any','ca',4);await expect(coordinator.persist(game)).rejects.toThrow('offline');expect(coordinator.snapshot).toMatchObject({state:'failed',dirty:true});fail=false;await coordinator.retry();expect(calls).toEqual(['Dirty','Dirty']);expect(coordinator.snapshot).toMatchObject({state:'saved',dirty:false,revision:1});});
  it('rejects critical persistence immediately while paused and retains the newest Game for retry',async()=>{let fail=true;const calls:string[]=[],coordinator=new SaveCoordinator(async game=>{calls.push(game.name);if(fail)throw Error('quota');return 2;},1),first=createGame('First','Any','ca',5),latest=createGame('Latest','Any','ca',6);await expect(coordinator.persist(first)).rejects.toThrow('quota');await expect(coordinator.persist(latest)).rejects.toThrow('quota');expect(calls).toEqual(['First']);expect(coordinator.snapshot).toMatchObject({state:'failed',dirty:true,revision:1});fail=false;await coordinator.retry();expect(calls).toEqual(['First','Latest']);expect(coordinator.snapshot).toMatchObject({state:'saved',dirty:false,revision:2});});
});
