import {afterEach,describe,expect,it} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {createGame} from '../engine/simulation';
import {PRE_HISTORY_SAVE_KEY,PRE_POPULATION_SAVE_KEY,SAVE_KEY,serializeGame} from '../engine/save';
import {deletePersistenceDatabase,IndexedDbSaveRepository} from './indexedDb';
import {verifyRecord} from './payload';
import {INDEXEDDB_AUTHORITY_MARKER_KEY,GamePersistence,exportCanonicalGame,importCanonicalGame,type LegacyStorage} from './service';
import {LEGACY_PRIMARY_RECOVERY_SLOT,PRIMARY_SLOT} from './record';

const memoryStorage=(entries:Record<string,string>={}):LegacyStorage&{data:Map<string,string>}=>{const data=new Map(Object.entries(entries));return {data,getItem:key=>data.get(key)??null,setItem:(key,value)=>{data.set(key,value);}};};
let sequence=0;const cleanup:{factory:IDBFactory;name:string;services:GamePersistence[]}[]=[];
async function service(storage:LegacyStorage,factory=new IDBFactory(),name=`service-${++sequence}`){const value=await GamePersistence.open(storage,factory,name);let item=cleanup.find(entry=>entry.factory===factory&&entry.name===name);if(!item){item={factory,name,services:[]};cleanup.push(item);}item.services.push(value);return {value,factory,name};}
afterEach(async()=>{for(const item of cleanup.splice(0)){item.services.forEach(value=>value.close());await deletePersistenceDatabase(item.factory,item.name).catch(()=>{});}});

describe('GamePersistence legacy authority and recovery',()=>{
  it('returns no-save without legacy input',async()=>{const {value}=await service(memoryStorage());expect(await value.initialize()).toMatchObject({status:'no-save',game:null,revision:null,staleLegacy:null});});
  it('migrates once, preserves exact bytes and writes the consumed hash marker only after verification',async()=>{const game=createGame('Migrated','Any','ca',1),raw=`${JSON.stringify(game,null,2)}\n`,history=JSON.stringify(createGame('History recovery','Any','ca',2)),legacy=memoryStorage({[SAVE_KEY]:raw,[PRE_HISTORY_SAVE_KEY]:history}),{value}=await service(legacy),started=await value.initialize();expect(started).toMatchObject({status:'loaded',revision:1});expect(started.game?.name).toBe('Migrated');expect(legacy.data.get(SAVE_KEY)).toBe(raw);expect(JSON.parse(legacy.data.get(INDEXEDDB_AUTHORITY_MARKER_KEY)!)).toMatchObject({version:1,consumedLegacySha256:expect.stringMatching(/^sha256:/)});expect((await verifyRecord(await value.repository.getRecord(LEGACY_PRIMARY_RECOVERY_SLOT),LEGACY_PRIMARY_RECOVERY_SLOT)).raw).toBe(raw);expect((await verifyRecord(await value.repository.getRecord(`recovery:${PRE_HISTORY_SAVE_KEY}`),`recovery:${PRE_HISTORY_SAVE_KEY}`)).raw).toBe(history);});
  it('creates required named recovery records from exact pre-migration root bytes',async()=>{const old=structuredClone(createGame('Root v2','Any','ca',12)) as unknown as Record<string,unknown>;old.version=2;delete old.population;const raw=JSON.stringify(old),{value}=await service(memoryStorage({[SAVE_KEY]:raw})),started=await value.initialize(),slot=`recovery:${PRE_POPULATION_SAVE_KEY}`;expect(started.game?.version).toBe(4);expect((await verifyRecord(await value.repository.getRecord(slot),slot)).raw).toBe(raw);});
  it('uses IndexedDB authority when the unchanged legacy primary also remains',async()=>{const legacyGame=createGame('Legacy','Any','ca',3),legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(legacyGame)}),factory=new IDBFactory(),name=`authority-${++sequence}`,first=await service(legacy,factory,name);await first.value.initialize();await first.value.save(createGame('Current IndexedDB','Any','ca',4),1);first.value.close();const second=await service(legacy,factory,name),started=await second.value.initialize();expect(started.game?.name).toBe('Current IndexedDB');expect(started.revision).toBe(2);});
  it('does not resurrect consumed legacy bytes after simulated IndexedDB loss',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('Stale','Any','ca',5))}),factory=new IDBFactory(),name=`lost-${++sequence}`,first=await service(legacy,factory,name);await first.value.initialize();first.value.close();await deletePersistenceDatabase(factory,name);const second=await service(legacy,factory,name),started=await second.value.initialize();expect(started).toMatchObject({status:'recovery-required',game:null,revision:null,staleLegacy:{kind:'consumed',game:{name:'Stale'}}});expect(await second.value.repository.getRecord(PRIMARY_SLOT)).toBeUndefined();});
  it('treats changed legacy bytes after consumption as explicit recovery, not automatic current authority',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('Original','Any','ca',6))}),factory=new IDBFactory(),name=`changed-${++sequence}`,first=await service(legacy,factory,name);await first.value.initialize();first.value.close();await deletePersistenceDatabase(factory,name);legacy.setItem(SAVE_KEY,JSON.stringify(createGame('Changed','Any','ca',7)));const second=await service(legacy,factory,name),started=await second.value.initialize();expect(started).toMatchObject({status:'recovery-required',game:null,staleLegacy:{kind:'changed',game:{name:'Changed'}}});expect(await second.value.repository.getRecord(PRIMARY_SLOT)).toBeUndefined();});
  it('never treats a malformed consumed-authority marker as permission to remigrate',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('Protected','Any','ca',71)),[INDEXEDDB_AUTHORITY_MARKER_KEY]:'{"version":1,"consumedLegacySha256":"bad"}'}),{value}=await service(legacy),started=await value.initialize();expect(started).toMatchObject({status:'recovery-required',game:null,staleLegacy:{kind:'changed',game:{name:'Protected'}}});expect(await value.repository.getRecord(PRIMARY_SLOT)).toBeUndefined();});
  it('is idempotent across startup after successful migration',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('Once','Any','ca',8))}),factory=new IDBFactory(),name=`repeat-${++sequence}`,first=await service(legacy,factory,name),a=await first.value.initialize();first.value.close();const second=await service(legacy,factory,name),b=await second.value.initialize();expect(a.game).toEqual(b.game);expect(b.revision).toBe(1);expect((await second.value.repository.listRecordKeys()).filter(key=>key===LEGACY_PRIMARY_RECOVERY_SLOT)).toHaveLength(1);});
  it('aborts migration atomically on quota failure and never marks legacy consumed',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('Quota','Any','ca',9))}),factory=new IDBFactory(),name=`quota-${++sequence}`,repository=await IndexedDbSaveRepository.open(factory,name,{beforeWrites:()=>{throw new DOMException('quota','QuotaExceededError');}}),value=new (GamePersistence as unknown as {new(repository:IndexedDbSaveRepository,legacy:LegacyStorage):GamePersistence})(repository,legacy);cleanup.push({factory,name,services:[value]});await expect(value.initialize()).rejects.toMatchObject({reason:'quota'});expect(legacy.getItem(INDEXEDDB_AUTHORITY_MARKER_KEY)).toBeNull();expect(await repository.getRecord(PRIMARY_SLOT)).toBeUndefined();expect(legacy.getItem(SAVE_KEY)).not.toBeNull();});
  it('restores through normal revisioned save and retains the selected recovery',async()=>{const legacy=memoryStorage({[SAVE_KEY]:JSON.stringify(createGame('First','Any','ca',10))}),{value}=await service(legacy),started=await value.initialize(),restored=await value.restore(LEGACY_PRIMARY_RECOVERY_SLOT,started.revision);expect(restored.game.name).toBe('First');expect(restored.revision).toBe(2);expect(await value.repository.getRecord(LEGACY_PRIMARY_RECOVERY_SLOT)).toBeDefined();});
  it('exports only canonical Game JSON and validates imports through the Game codec',()=>{const game=createGame('Portable','Any','ca',11),raw=exportCanonicalGame(game),imported=importCanonicalGame(raw),serialized=serializeGame(game);expect(serialized.ok).toBe(true);expect(raw).toBe(serialized.ok?serialized.raw:'');expect(imported).toEqual(serialized.ok?serialized.game:null);expect(raw).not.toContain('persistenceVersion');});
});
