import {afterEach,describe,expect,it} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {isGame,migrateGame,serializeGame} from '../engine/save';
import {deletePersistenceDatabase} from './indexedDb';
import {PRIMARY_SLOT,PREVIOUS_SLOT} from './record';
import {GamePersistence,type LegacyStorage} from './service';
import {continueV3PersistenceProbe,createV3PersistenceProbeGame,V3_PERSISTENCE_IDENTITY} from './testing/v3Gate';
import {sha256Bytes,verifyRecord} from './payload';

const legacy:LegacyStorage={getItem:()=>null,setItem:()=>{}};let cleanup:(()=>Promise<void>)[]=[];afterEach(async()=>{for(const value of cleanup.splice(0))await value();});
describe('uk.population.mid-2024.v3 IndexedDB acceptance probe',()=>{
  it('saves, closes, reopens, verifies and deterministically continues the exact unregistered candidate',async()=>{
    const factory=new IDBFactory(),name='v3-persistence-gate',game=createV3PersistenceProbeGame(),validationStart=performance.now();expect(isGame(game)).toBe(true);const gameValidationMs=performance.now()-validationStart,stringifyStart=performance.now(),stringified=JSON.stringify(game),jsonStringifyMs=performance.now()-stringifyStart,canonicalStart=performance.now(),canonical=serializeGame(game);expect(canonical.ok).toBe(true);if(!canonical.ok)return;expect(stringified).toBe(canonical.raw);const canonicalMs=performance.now()-canonicalStart,encodingStart=performance.now(),encoded=new TextEncoder().encode(canonical.raw),utf8EncodingMs=performance.now()-encodingStart,bytes=encoded.byteLength;expect(bytes).toBe(9_595_304);const hashStart=performance.now();await sha256Bytes(encoded);const sha256Ms=performance.now()-hashStart;
    const first=await GamePersistence.open(legacy,factory,name),writeStart=performance.now(),revision=await first.save(game,null),writeMs=performance.now()-writeStart;expect(revision).toBe(1);first.close();
    const reopenStart=performance.now(),second=await GamePersistence.open(legacy,factory,name),started=await second.initialize(),loadMs=performance.now()-reopenStart;cleanup.push(async()=>{second.close();await deletePersistenceDatabase(factory,name);});expect(started.game).toEqual(canonical.game);expect(started.revision).toBe(1);continueV3PersistenceProbe(started.game!);
    const secondWriteStart=performance.now();await second.save(started.game!,1);const secondWriteMs=performance.now()-secondWriteStart,readStart=performance.now(),primaryStored=await second.repository.getRecord(PRIMARY_SLOT),indexedDbReadMs=performance.now()-readStart,primaryRecord=primaryStored as {payload:ArrayBuffer},decodeStart=performance.now(),decoded=new TextDecoder('utf-8',{fatal:true}).decode(new Uint8Array(primaryRecord.payload)),arrayBufferDecodeMs=performance.now()-decodeStart,parseStart=performance.now(),parsed:unknown=JSON.parse(decoded),jsonParseMs=performance.now()-parseStart,migrationStart=performance.now(),migrated=migrateGame(parsed),migrationMs=performance.now()-migrationStart,loadedValidationStart=performance.now();expect(isGame(migrated)).toBe(true);const loadedValidationMs=performance.now()-loadedValidationStart,primary=await verifyRecord(primaryStored,PRIMARY_SLOT),previous=await verifyRecord(await second.repository.getRecord(PREVIOUS_SLOT),PREVIOUS_SLOT);expect(primary.record.byteLength).toBe(bytes);expect(previous.record.byteLength).toBe(bytes);expect(primary.record.revision).toBe(2);expect(previous.record.revision).toBe(1);expect(V3_PERSISTENCE_IDENTITY).toEqual({id:'uk.population.mid-2024.v3',fingerprint:'fnv1a64-v1:2894f4c1b1fdd274',artifactSha256:'c4b13eb67a1b7e231da1250b27f8e596c6535e7f260013d8a8638bda2b81188a',total:69_281_437});
    console.log(JSON.stringify({gate:'persistence-vnext-v3',...V3_PERSISTENCE_IDENTITY,primaryBytes:primary.record.byteLength,previousBytes:previous.record.byteLength,recoveryBytes:0,gameValidationMs:+gameValidationMs.toFixed(3),jsonStringifyMs:+jsonStringifyMs.toFixed(3),utf8EncodingMs:+utf8EncodingMs.toFixed(3),sha256Ms:+sha256Ms.toFixed(3),canonicalMs:+canonicalMs.toFixed(3),indexedDbWriteMs:+writeMs.toFixed(3),secondWriteMs:+secondWriteMs.toFixed(3),indexedDbReadMs:+indexedDbReadMs.toFixed(3),arrayBufferDecodeMs:+arrayBufferDecodeMs.toFixed(3),jsonParseMs:+jsonParseMs.toFixed(3),migrationMs:+migrationMs.toFixed(3),loadedValidationMs:+loadedValidationMs.toFixed(3),completeValidatedLoadMs:+loadMs.toFixed(3),continuationPersonId:'person:2'}));
  },30_000);
});
