import {describe,expect,it} from 'vitest';
import {createGeographyRegistry,fingerprintPlaceIdentity,withGeographyPartitionFingerprint} from '../geography/package';
import {createGeographyRuntime} from '../geography/runtime';
import {createSettlementRegistry,fingerprintSettlementIdentity,withSettlementPackageFingerprint} from '../geography/settlements/package';
import {createSettlementRuntime} from '../geography/settlements/runtime';
import type {SettlementAdministrativeRelationV1,SettlementIdentityV1,SettlementMappingDecisionV1,SettlementPackageV1,SettlementV1} from '../geography/settlements/types';
import type {GeographyPartitionNodeV1,GeographyPartitionPackageV1,PlaceIdentityV1} from '../geography/types';
import {allocatePerson,createPeople,createPerson,replacePerson,type PeopleState,type PersonInput} from '../human/person';
import {clearNoFixedAbode,createEmptyResidenceState,establishResidence,joinResidence,leaveResidence,recordNoFixedAbode,relocateResidence,removePersonFromResidences} from './state';
import {createResidenceRuntime} from './runtime';
import type {ResidenceLocationRefV1,ResidenceStateV1} from './types';
import {validResidenceContent,validResidenceLocation,validResidenceLocationContent,validResidenceState,validResidenceWithContext,validResidenceWithPeople,type ResidenceValidationContext} from './validation';

const date={year:2024,month:6,day:30} as const;
const personInput=(name:string):PersonInput=>({name,dateOfBirth:{year:1990,month:1,day:1},genderLabel:'Unspecified',lifeStatus:'living',traits:[],temperament:{},aptitudes:{}});
function people(count=4):PeopleState{let state=createPeople(personInput('Person 1'));for(let index=2;index<=count;index++)state=allocatePerson(state,personInput(`Person ${index}`)).state;return state;}

const geographySource={version:1 as const,id:'geography.source.synthetic-residence-v1',producer:'Synthetic producer',datasetId:'synthetic-residence',releaseId:'v1',title:'Synthetic Residence geography',jurisdiction:'aa',referenceDate:date,classification:'authored-gameplay-abstraction' as const,methodology:'Synthetic structural fixture.',licence:'Synthetic test fixture.'};
const node=(placeId:string,parentPlaceId:string|null):GeographyPartitionNodeV1=>({placeId,displayName:placeId,kindId:'geo.synthetic-residence',parentPlaceId,populationAllocationCell:parentPlaceId!==null,sourceIds:[geographySource.id]});
const aaNodes=[node('place.synthetic.aa.alpha','place.synthetic.aa.root'),node('place.synthetic.aa.beta','place.synthetic.aa.root'),node('place.synthetic.aa.rural','place.synthetic.aa.root'),node('place.synthetic.aa.root',null)];
const bbNodes=[node('place.synthetic.bb.cell','place.synthetic.bb.root'),node('place.synthetic.bb.root',null)];
const geographyPackage=(partitionId:string,countryId:string,nodes:readonly GeographyPartitionNodeV1[]):GeographyPartitionPackageV1=>withGeographyPartitionFingerprint({version:1,partitionId,countryId,effectiveDate:date,sources:[geographySource],nodes,limitations:['Synthetic only.']});
function geography(){const packages=[geographyPackage('geography.synthetic-aa-v1','aa',aaNodes),geographyPackage('geography.synthetic-bb-v1','bb',bbNodes)],places:PlaceIdentityV1[]=[...aaNodes.map(item=>({placeId:item.placeId,countryId:'aa'})),...bbNodes.map(item=>({placeId:item.placeId,countryId:'bb'}))];return createGeographyRuntime(createGeographyRegistry(places,packages,packages.map(item=>({partitionId:item.partitionId,fingerprint:item.fingerprint})),places.map(item=>({placeId:item.placeId,fingerprint:fingerprintPlaceIdentity(item)}))));}

const settlementSource={...geographySource,id:'geography.source.synthetic-residence-settlements-v1',datasetId:'synthetic-residence-settlements',title:'Synthetic Residence Settlements'};
const decision:SettlementMappingDecisionV1={id:'settlement-decision.synthetic-residence.mapping-v1',classification:'reviewed-mapping',description:'Synthetic exact-area mapping.',sourceIds:[settlementSource.id]};
const settlement=(id:string):SettlementV1=>({settlementId:`settlement.synthetic.aa.${id}`,kindId:'settlement-kind.synthetic.named-place',names:[{nameId:`settlement-name.synthetic.aa.${id}.display`,text:id,languageTag:'en',role:'display',sourceIds:[settlementSource.id]}],sourceIds:[settlementSource.id],decisionIds:[]});
const relation=(id:string,placeId:string):SettlementAdministrativeRelationV1=>({settlementId:`settlement.synthetic.aa.${id}`,partitionId:'geography.synthetic-aa-v1',placeId,relation:id==='cross'?'intersects':'contained-by',basis:'reviewed-mapping',sourceIds:[settlementSource.id],decisionIds:[decision.id]});
function settlementPackage(packageId='settlements.synthetic-residence-2024-v1'):SettlementPackageV1{return withSettlementPackageFingerprint({version:1,packageId,countryId:'aa',effectiveDate:date,sources:[settlementSource],settlements:[settlement('authored'),settlement('cross'),settlement('village')],administrativeRelations:[relation('authored','place.synthetic.aa.alpha'),relation('cross','place.synthetic.aa.alpha'),relation('cross','place.synthetic.aa.beta'),relation('village','place.synthetic.aa.alpha')],decisions:[decision],gaps:[],limitations:['Synthetic only.']});}
function context(peopleState=people(),pkg=settlementPackage()):ResidenceValidationContext{const geo=geography(),identities:SettlementIdentityV1[]=pkg.settlements.map(item=>({settlementId:item.settlementId,countryId:'aa'})),registry=createSettlementRegistry(identities,[pkg],[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}],identities.map(item=>({settlementId:item.settlementId,fingerprint:fingerprintSettlementIdentity(item)})),geo);return {people:peopleState,geography:geo,settlements:createSettlementRuntime(registry,geo)};}

const country:ResidenceLocationRefV1={kind:'country',countryId:'aa'};
const admin=(placeId='place.synthetic.aa.alpha'):ResidenceLocationRefV1=>({kind:'administrative-area',administrativeArea:{version:1,partitionId:'geography.synthetic-aa-v1',placeId}});
const settlementArea=(settlementId='settlement.synthetic.aa.village',placeId='place.synthetic.aa.alpha',packageId='settlements.synthetic-residence-2024-v1'):ResidenceLocationRefV1=>({kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-aa-v1',placeId},settlement:{version:1,packageId,settlementId}});

describe('Residence Foundation v1',()=>{
 it('creates an empty deeply immutable canonical state',()=>{const state=createEmptyResidenceState();expect(state).toEqual({version:1,nextSequence:1,residences:[],occupants:[],noFixedAbodePersonIds:[]});expect(validResidenceState(state)).toBe(true);expect(Object.isFrozen(state)).toBe(true);expect(Object.isFrozen(state.residences)).toBe(true);});

 it('supports country, administrative-area, rural, and exact settlement-area precision',()=>{const c=context();let state=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state;state=establishResidence(state,['person:2'],admin('place.synthetic.aa.rural'),c).state;state=establishResidence(state,['person:3'],settlementArea(),c).state;expect(validResidenceWithContext(state,c)).toBe(true);expect(state.residences.map(item=>item.location.kind)).toEqual(['country','administrative-area','settlement-area']);expect((state.residences[1].location as {administrativeArea:{placeId:string}}).administrativeArea.placeId).toBe('place.synthetic.aa.rural');});

 it('allocates monotonic world-scoped IDs and rejects exhausted allocation atomically',()=>{const c=context(),first=establishResidence(createEmptyResidenceState(),['person:1'],country,c),second=establishResidence(first.state,['person:2'],country,c);expect(first.residence).toMatchObject({id:'residence:1',sequence:1});expect(second.residence).toMatchObject({id:'residence:2',sequence:2});expect(second.state.nextSequence).toBe(3);const exhausted={...first.state,nextSequence:Number.MAX_SAFE_INTEGER} as ResidenceStateV1,before=structuredClone(exhausted);expect(validResidenceState(exhausted)).toBe(true);expect(()=>establishResidence(exhausted,['person:2'],country,c)).toThrow('exhausted');expect(exhausted).toEqual(before);});

 it('shares one Residence between four unrelated Persons and canonicalizes occupant input order',()=>{const c=context(),left=establishResidence(createEmptyResidenceState(),['person:4','person:2','person:1','person:3'],settlementArea(),c).state,right=establishResidence(createEmptyResidenceState(),['person:1','person:2','person:3','person:4'],settlementArea(),c).state;expect(left).toEqual(right);expect(left.residences).toHaveLength(1);expect(left.occupants.map(item=>item.personId)).toEqual(['person:1','person:2','person:3','person:4']);expect(createResidenceRuntime(left).getOccupantsForResidence('residence:1')).toEqual(['person:1','person:2','person:3','person:4']);});

 it('allows one Person to occupy multiple current Residences without a primary field',()=>{const c=context();let state=establishResidence(createEmptyResidenceState(),['person:1'],admin(),c).state;state=establishResidence(state,['person:2'],settlementArea(),c).state;state=joinResidence(state,'person:1','residence:2',c);const homes=createResidenceRuntime(state).getResidencesForPerson('person:1');expect(homes.map(item=>item.id)).toEqual(['residence:1','residence:2']);expect(homes.every(item=>!('primary' in item))).toBe(true);expect(()=>joinResidence(state,'person:1','residence:2',c)).toThrow();});

 it('leaves only the requested home, removes the empty record, and never reuses its ID',()=>{const c=context();let state=establishResidence(createEmptyResidenceState(),['person:1','person:2'],admin(),c).state;state=establishResidence(state,['person:1'],country,c).state;const one=leaveResidence(state,'person:1','residence:1',c);expect(one.residences).toHaveLength(2);expect(createResidenceRuntime(one).getResidencesForPerson('person:1').map(item=>item.id)).toEqual(['residence:2']);const empty=leaveResidence(one,'person:2','residence:1',c);expect(empty.residences.map(item=>item.id)).toEqual(['residence:2']);expect(empty.occupants).toEqual([{personId:'person:1',residenceId:'residence:2'}]);expect(empty.nextSequence).toBe(3);const later=establishResidence(empty,['person:2'],country,c);expect(later.residence.id).toBe('residence:3');});

 it('relocates one shared arrangement once without changing identity or occupants',()=>{const c=context();const initial=establishResidence(createEmptyResidenceState(),['person:1','person:2'],admin(),c).state,next=relocateResidence(initial,'residence:1',settlementArea('settlement.synthetic.aa.cross','place.synthetic.aa.beta'),c);expect(next.residences[0]).toMatchObject({id:'residence:1',sequence:1,location:{kind:'settlement-area',administrativeArea:{placeId:'place.synthetic.aa.beta'}}});expect(next.occupants).toEqual(initial.occupants);expect(next.nextSequence).toBe(initial.nextSequence);expect(initial.residences[0].location).toEqual(admin());});

 it('requires explicit no-fixed-abode clearing before establishment or join',()=>{const c=context();let state=recordNoFixedAbode(createEmptyResidenceState(),'person:1',c);expect(state.noFixedAbodePersonIds).toEqual(['person:1']);expect(createResidenceRuntime(state).hasNoFixedAbode('person:1')).toBe(true);expect(()=>establishResidence(state,['person:1'],country,c)).toThrow();const other=establishResidence(state,['person:2'],country,c).state;expect(()=>joinResidence(other,'person:1','residence:1',c)).toThrow();state=clearNoFixedAbode(other,'person:1',c);state=joinResidence(state,'person:1','residence:1',c);expect(state.noFixedAbodePersonIds).toEqual([]);expect(()=>clearNoFixedAbode(state,'person:1',c)).toThrow();});

 it('validates both exact sides of a cross-boundary Settlement without a global owner',()=>{const c=context(),a=settlementArea('settlement.synthetic.aa.cross','place.synthetic.aa.alpha'),b=settlementArea('settlement.synthetic.aa.cross','place.synthetic.aa.beta'),unrelated=settlementArea('settlement.synthetic.aa.cross','place.synthetic.aa.rural');expect(establishResidence(createEmptyResidenceState(),['person:1'],a,c).state.residences[0].location).toEqual(a);expect(establishResidence(createEmptyResidenceState(),['person:1'],b,c).state.residences[0].location).toEqual(b);expect(()=>establishResidence(createEmptyResidenceState(),['person:1'],unrelated,c)).toThrow('location');});

 it('separates structural validation from exact package-qualified content resolution',()=>{const c=context(),valid=establishResidence(createEmptyResidenceState(),['person:1'],settlementArea(),c).state,missing={...valid,residences:[{...valid.residences[0],location:settlementArea('settlement.synthetic.aa.village','place.synthetic.aa.alpha','settlements.synthetic-residence-2025-v1')}]} as ResidenceStateV1;expect(validResidenceState(missing)).toBe(true);expect(validResidenceContent(missing,c.geography,c.settlements)).toBe(false);expect(validResidenceContent(valid,c.geography,c.settlements)).toBe(true);});

 it('resolves overlapping durable Settlement IDs against the exact immutable package',()=>{const packageOne=settlementPackage(),packageTwo=settlementPackage('settlements.synthetic-residence-2025-v1'),one=context(people(),packageOne),two=context(people(),packageTwo),locationOne=settlementArea(),locationTwo=settlementArea('settlement.synthetic.aa.village','place.synthetic.aa.alpha',packageTwo.packageId);expect(validResidenceLocationContent(locationOne,one.geography,one.settlements)).toBe(true);expect(validResidenceLocationContent(locationOne,two.geography,two.settlements)).toBe(false);expect(validResidenceLocationContent(locationTwo,two.geography,two.settlements)).toBe(true);expect(validResidenceLocationContent(locationTwo,one.geography,one.settlements)).toBe(false);});

 it('rejects unknown external Geography and Settlement references predictably',()=>{const c=context(),locations=[admin('place.synthetic.aa.unknown'),{kind:'administrative-area',administrativeArea:{version:1,partitionId:'geography.synthetic-missing-v1',placeId:'place.synthetic.aa.alpha'}},{kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-aa-v1',placeId:'place.synthetic.aa.alpha'},settlement:{version:1,packageId:'settlements.synthetic-residence-2024-v1',settlementId:'settlement.synthetic.aa.missing'}}] as const;for(const location of locations){expect(validResidenceLocation(location)).toBe(true);expect(validResidenceLocationContent(location,c.geography,c.settlements)).toBe(false);expect(()=>establishResidence(createEmptyResidenceState(),['person:1'],location,c)).toThrow('location');}});

 it('rejects settlement/admin and cross-country mismatches',()=>{const c=context();expect(()=>establishResidence(createEmptyResidenceState(),['person:1'],settlementArea('settlement.synthetic.aa.village','place.synthetic.aa.beta'),c)).toThrow();const foreign:ResidenceLocationRefV1={kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-bb-v1',placeId:'place.synthetic.bb.cell'},settlement:{version:1,packageId:'settlements.synthetic-residence-2024-v1',settlementId:'settlement.synthetic.aa.village'}};expect(validResidenceLocation(foreign)).toBe(true);expect(()=>establishResidence(createEmptyResidenceState(),['person:1'],foreign,c)).toThrow();});

 it('rejects dead occupants and lets external lifecycle coordination remove only Residence facts',()=>{const living=people(3),c=context(living);let state=establishResidence(createEmptyResidenceState(),['person:1','person:2'],country,c).state;state=establishResidence(state,['person:1'],admin(),c).state;const dead=createPerson(1,{...personInput('Person 1'),lifeStatus:'deceased',diedAt:{year:2024,month:6,day:30}}),deadPeople=replacePerson(living,dead),deadContext=context(deadPeople),beforePeople=structuredClone(deadPeople);expect(validResidenceWithPeople(state,deadPeople)).toBe(false);expect(()=>joinResidence(state,'person:1','residence:1',deadContext)).toThrow();expect(()=>establishResidence(createEmptyResidenceState(),['person:1'],country,deadContext)).toThrow();const cleaned=removePersonFromResidences(state,'person:1',deadContext);expect(cleaned.residences).toEqual([{id:'residence:1',sequence:1,location:country}]);expect(cleaned.occupants).toEqual([{personId:'person:2',residenceId:'residence:1'}]);expect(cleaned.nextSequence).toBe(3);expect(deadContext.people).toEqual(beforePeople);expect(validResidenceWithContext(cleaned,deadContext)).toBe(true);});

 it('leaves original authority unchanged after representative failures',()=>{const c=context(),state=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,before=structuredClone(state),failures=[()=>joinResidence(state,'person:99','residence:1',c),()=>joinResidence(state,'person:2','residence:99',c),()=>joinResidence(state,'person:1','residence:1',c),()=>leaveResidence(state,'person:2','residence:1',c),()=>relocateResidence(state,'residence:99',country,c),()=>recordNoFixedAbode(state,'person:1',c),()=>establishResidence(state,['person:2','person:2'],country,c)];for(const failure of failures){expect(failure).toThrow();expect(state).toEqual(before);}});

 it('rejects every malformed or unresolved location atomically',()=>{const c=context(),state=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,before=structuredClone(state),invalid=[{kind:'country',countryId:'UK'},admin('place.synthetic.aa.unknown'),{kind:'administrative-area',administrativeArea:{version:1,partitionId:'geography.synthetic-missing-v1',placeId:'place.synthetic.aa.alpha'}},settlementArea('settlement.synthetic.aa.missing'),settlementArea('settlement.synthetic.aa.village','place.synthetic.aa.beta'),settlementArea('settlement.synthetic.aa.village','place.synthetic.aa.alpha','settlements.synthetic-residence-2025-v1'),{kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-bb-v1',placeId:'place.synthetic.bb.cell'},settlement:{version:1,packageId:'settlements.synthetic-residence-2024-v1',settlementId:'settlement.synthetic.aa.village'}}] as readonly ResidenceLocationRefV1[];for(const location of invalid){expect(()=>relocateResidence(state,'residence:1',location,c)).toThrow();expect(state).toEqual(before);}});

 it('does not retain caller aliases and freezes every returned layer',()=>{const c=context(),location={kind:'administrative-area' as const,administrativeArea:{version:1 as const,partitionId:'geography.synthetic-aa-v1',placeId:'place.synthetic.aa.alpha'}},ids=['person:1'],result=establishResidence(createEmptyResidenceState(),ids,location,c);location.administrativeArea.placeId='place.synthetic.aa.rural';ids[0]='person:2';expect(result.residence.location).toEqual(admin());expect(Object.isFrozen(result.state)).toBe(true);expect(Object.isFrozen(result.state.residences)).toBe(true);expect(Object.isFrozen(result.state.residences[0].location)).toBe(true);expect(()=>((result.state.residences as unknown as unknown[])[0]=null)).toThrow();});

 it('copies mutable candidate arrays instead of retaining state aliases',()=>{const c=context(),first=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,source=structuredClone(first),next=establishResidence(source,['person:2'],admin(),c).state;(source.residences as unknown as unknown[]).splice(0);(source.occupants as unknown as unknown[]).splice(0);(source.noFixedAbodePersonIds as unknown as string[]).push('person:3');(source as {nextSequence:number}).nextSequence=99;expect(next.residences.map(item=>item.id)).toEqual(['residence:1','residence:2']);expect(next.occupants).toEqual([{personId:'person:1',residenceId:'residence:1'},{personId:'person:2',residenceId:'residence:2'}]);expect(next.noFixedAbodePersonIds).toEqual([]);expect(next.nextSequence).toBe(3);});

 it('rejects hostile and noncanonical structural inputs without invoking accessors',()=>{const c=context(),canonical=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,sparse=[...canonical.occupants];delete sparse[0];const duplicateResidence={...canonical,residences:[canonical.residences[0],canonical.residences[0]]},duplicateSequence={...canonical,residences:[canonical.residences[0],{...canonical.residences[0],id:'residence:2'}]},badId={...canonical,residences:[{...canonical.residences[0],id:'residence:2'}]},duplicateOccupant={...canonical,occupants:[canonical.occupants[0],canonical.occupants[0]]},conflict={...canonical,noFixedAbodePersonIds:['person:1']};for(const invalid of [{...canonical,version:2},duplicateResidence,duplicateSequence,badId,duplicateOccupant,conflict,{...canonical,occupants:sparse},{...canonical,nextSequence:0},{...canonical,nextSequence:1},{...canonical,[Symbol('extra')]:true},Object.assign(Object.create({bad:true}),canonical)])expect(validResidenceState(invalid)).toBe(false);let accessed=false;const accessor={...canonical};Object.defineProperty(accessor,'version',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validResidenceState(accessor)).toBe(false);expect(accessed).toBe(false);const hidden={...canonical};Object.defineProperty(hidden,'extra',{value:true});expect(validResidenceState(hidden)).toBe(false);const revoked=Proxy.revocable(canonical,{});revoked.revoke();expect(validResidenceState(revoked.proxy)).toBe(false);expect(validResidenceWithContext(canonical,c)).toBe(true);});

 it('rejects functions, Map, Set, Date, and unsafe integer corruption classes',()=>{const c=context(),canonical=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,corruptions=[{...canonical,nextSequence:Number.MAX_SAFE_INTEGER+1},{...canonical,residences:[{...canonical.residences[0],sequence:Number.MAX_SAFE_INTEGER+1}]},{...canonical,residences:new Map()},{...canonical,occupants:new Set()},{...canonical,noFixedAbodePersonIds:new Date()},{...canonical,residences:[{...canonical.residences[0],location:{kind:'country',countryId:()=>"aa"}}]}];for(const corruption of corruptions)expect(validResidenceState(corruption)).toBe(false);});

 it('rejects custom Array prototypes in canonical state and command inputs',()=>{const c=context(),canonical=establishResidence(createEmptyResidenceState(),['person:1'],country,c).state,hostileOccupants=[...canonical.occupants],hostilePeople=['person:2'];Object.setPrototypeOf(hostileOccupants,{toJSON(){throw Error('must not run');}});Object.setPrototypeOf(hostilePeople,{toJSON(){throw Error('must not run');}});expect(validResidenceState({...canonical,occupants:hostileOccupants})).toBe(false);expect(()=>establishResidence(canonical,hostilePeople,country,c)).toThrow('occupants');});

 it('rejects duplicate no-fixed-abode IDs, unknown Persons, and noncanonical marker order',()=>{const c=context(),marked=recordNoFixedAbode(recordNoFixedAbode(createEmptyResidenceState(),'person:2',c),'person:1',c);expect(marked.noFixedAbodePersonIds).toEqual(['person:1','person:2']);expect(validResidenceState({...marked,noFixedAbodePersonIds:['person:1','person:1']})).toBe(false);expect(validResidenceState({...marked,noFixedAbodePersonIds:['person:2','person:1']})).toBe(false);expect(validResidenceWithPeople({...marked,noFixedAbodePersonIds:['person:1','person:99']},c.people)).toBe(false);expect(()=>recordNoFixedAbode(marked,'person:99',c)).toThrow();});

 it('rejects malformed exact location unions and identifier shapes',()=>{const cases=[{}, {kind:'country'}, {kind:'country',countryId:''}, {kind:'country',countryId:'aa',extra:true}, {kind:'administrative-area',administrativeArea:{version:1,partitionId:'bad',placeId:'place.synthetic.aa.alpha'}}, {kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-aa-v1',placeId:'place.synthetic.aa.alpha'}}, {kind:'settlement-area',administrativeArea:{version:1,partitionId:'geography.synthetic-aa-v1',placeId:'place.synthetic.aa.alpha'},settlement:{version:2,packageId:'settlements.synthetic-residence-2024-v1',settlementId:'settlement.synthetic.aa.village'}}];for(const value of cases)expect(validResidenceLocation(value)).toBe(false);});

 it('builds disposable indexed queries without decorating or mutating canonical state',()=>{const c=context();let state=establishResidence(createEmptyResidenceState(),['person:1','person:2'],admin(),c).state;state=establishResidence(state,['person:1'],country,c).state;const before=structuredClone(state),runtime=createResidenceRuntime(state);expect(runtime.getResidence('residence:1')?.id).toBe('residence:1');expect(runtime.getResidence('residence:99')).toBeUndefined();expect(runtime.getResidencesForPerson('person:1').map(item=>item.id)).toEqual(['residence:1','residence:2']);expect(runtime.getOccupantsForResidence('residence:1')).toEqual(['person:1','person:2']);expect(runtime.listResidences()).toHaveLength(2);expect(runtime.state).toEqual(before);expect(state).toEqual(before);expect(Reflect.ownKeys(runtime.state).some(key=>typeof key==='string'&&/map|cache|index/i.test(key))).toBe(false);});

 it('returns canonically identical state for repeated identical operations',()=>{const c=context(),state=createEmptyResidenceState(),left=establishResidence(state,['person:2','person:1'],settlementArea(),c).state,right=establishResidence(state,['person:2','person:1'],settlementArea(),c).state;expect(left).toEqual(right);expect(JSON.stringify(left)).toBe(JSON.stringify(right));expect(state).toEqual(createEmptyResidenceState());});

 it('validates and indexes ten thousand synthetic current Residences linearly by structure',()=>{const count=10_000,peopleState:PeopleState={version:1,nextSequence:count+1,playerId:'person:1',people:Array.from({length:count},(_,index)=>({id:`person:${index+1}`,sequence:index+1,name:`Person ${index+1}`,dateOfBirth:date,genderLabel:'Unspecified',lifeStatus:'living' as const,traits:[],temperament:{},aptitudes:{}}))},state:ResidenceStateV1={version:1,nextSequence:count+1,residences:Array.from({length:count},(_,index)=>({id:`residence:${index+1}`,sequence:index+1,location:country})),occupants:Array.from({length:count},(_,index)=>({personId:`person:${index+1}`,residenceId:`residence:${index+1}`})).sort((a,b)=>a.personId<b.personId?-1:a.personId>b.personId?1:Number(a.residenceId.slice(10))-Number(b.residenceId.slice(10))),noFixedAbodePersonIds:[]},c=context(peopleState);expect(validResidenceWithContext(state,c)).toBe(true);const runtime=createResidenceRuntime(state);expect(runtime.getResidence('residence:9999')?.sequence).toBe(9999);expect(runtime.getResidencesForPerson('person:10000')[0]?.id).toBe('residence:10000');},20_000);

 it('keeps the inward domain dependency boundary and host randomness out of Residence',()=>{const residenceModules=import.meta.glob<string>(['./*.ts','!./*.test.ts'],{eager:true,query:'?raw',import:'default'}),lowerOwners=import.meta.glob<string>(['../core/**/*.ts','../human/**/*.ts','../geography/**/*.ts','../../data/uk/**/*.ts'],{eager:true,query:'?raw',import:'default'});for(const [path,source] of Object.entries(residenceModules)){expect(source,path).not.toMatch(/from\s+['"][^'"]*(?:population|politics|persistence|save|countryStart|newGame|data\/uk|ui|react|household|presence|travel|housing)/i);expect(source,path).not.toMatch(/Math\.random|Date\.now|new Date|randomUUID|getRandomValues/);}for(const [path,source] of Object.entries(lowerOwners))expect(source,path).not.toMatch(/(?:from\s+|import\s*)['"][^'"]*residence/i);});
});
