import {isSimulationDate} from '../../core/clock';
import {isJsonValue} from '../../core/json';
import type {SimulationDate} from '../../core/model';
import type {GeographyRuntime} from '../runtime';
import type {GeographySourceDescriptorV1} from '../types';
import type {SettlementAdministrativeRelationV1,SettlementGapV1,SettlementIdentityManifestEntry,SettlementIdentityV1,SettlementMappingDecisionV1,SettlementNameV1,SettlementPackageManifestEntry,SettlementPackageV1,SettlementRegistryV1,SettlementV1} from './types';

const codePointCompare=(left:string,right:string)=>left<right?-1:left>right?1:0;
const stableIdentifier=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=160&&value.includes('.')&&/^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$/.test(value);
const versionedIdentifier=(value:unknown):value is string=>stableIdentifier(value)&&/(?:^|[._-])v[1-9]\d*$/.test(value);
const contextIdentifier=(value:unknown):value is string=>typeof value==='string'&&value.length>0&&value.length<=100&&/^[a-z][a-z0-9-]*$/.test(value);
const text=(value:unknown,max=3000):value is string=>typeof value==='string'&&value.trim().length>0&&value.length<=max;
const fingerprint=(value:unknown):value is string=>typeof value==='string'&&/^fnv1a64-v1:[0-9a-f]{16}$/.test(value);
const languageTag=(value:unknown):value is string|null=>value===null||typeof value==='string'&&/^[a-z]{2,8}(?:-[a-z0-9]{1,8})*$/.test(value);
const record=(value:unknown):value is Record<string,unknown>=>{try{return !!value&&typeof value==='object'&&!Array.isArray(value)&&(Object.getPrototypeOf(value)===Object.prototype||Object.getPrototypeOf(value)===null);}catch{return false;}};
const fields=(value:Record<string,unknown>,required:readonly string[],optional:readonly string[]=[])=>{try{const allowed=new Set([...required,...optional]),keys=Reflect.ownKeys(value);return required.every(key=>keys.includes(key))&&keys.every(key=>typeof key==='string'&&allowed.has(key)&&!!Object.getOwnPropertyDescriptor(value,key)?.enumerable&&'value' in Object.getOwnPropertyDescriptor(value,key)!);}catch{return false;}};
const dense=(value:unknown):value is readonly unknown[]=>{try{if(!Array.isArray(value)||Object.keys(value).length!==value.length||Reflect.ownKeys(value).length!==value.length+1)return false;for(let index=0;index<value.length;index++){const descriptor=Object.getOwnPropertyDescriptor(value,index);if(!descriptor?.enumerable||!('value' in descriptor))return false;}return true;}catch{return false;}};
const unique=(items:readonly string[])=>new Set(items).size===items.length;
const sorted=(items:readonly string[])=>items.every((item,index)=>index===0||codePointCompare(items[index-1],item)<0);
const exactDate=(value:unknown):value is SimulationDate=>record(value)&&fields(value,['year','month','day'])&&isSimulationDate(value);
const stringArray=(value:unknown,allowEmpty=true):value is readonly string[]=>dense(value)&&(allowEmpty||value.length>0)&&value.every(item=>text(item))&&unique(value)&&sorted(value);
function freezeDeep(value:unknown):void{if(!value||typeof value!=='object'||Object.isFrozen(value))return;for(const key of Reflect.ownKeys(value)){const descriptor=Object.getOwnPropertyDescriptor(value,key);if(descriptor&&'value' in descriptor)freezeDeep(descriptor.value);}Object.freeze(value);}
function immutable<T>(value:T):T{const copy=structuredClone(value);freezeDeep(copy);return copy;}

function validSource(value:unknown):value is GeographySourceDescriptorV1{
 if(!record(value)||!fields(value,['version','id','producer','datasetId','releaseId','title','jurisdiction','referenceDate','classification','methodology','licence'],['bundledArtifact','externalLocator'])||value.version!==1||!stableIdentifier(value.id)||!text(value.producer,300)||!text(value.datasetId,300)||!text(value.releaseId,300)||!text(value.title,500)||!contextIdentifier(value.jurisdiction)||!exactDate(value.referenceDate)||!text(value.methodology)||!text(value.licence,1000))return false;
 if(typeof value.classification!=='string'||!['statutory-institutional','observed-statistical-data','estimated','authored-gameplay-abstraction'].includes(value.classification))return false;
 if(value.bundledArtifact!==undefined&&(!record(value.bundledArtifact)||!fields(value.bundledArtifact,['id','sha256'])||!stableIdentifier(value.bundledArtifact.id)||typeof value.bundledArtifact.sha256!=='string'||!/^sha256:[0-9a-f]{64}$/.test(value.bundledArtifact.sha256)))return false;
 return value.externalLocator===undefined||text(value.externalLocator,1000);
}
function validIdentity(value:unknown):value is SettlementIdentityV1{return record(value)&&fields(value,['settlementId','countryId'])&&stableIdentifier(value.settlementId)&&contextIdentifier(value.countryId);}
function validIdentityManifest(value:unknown):value is SettlementIdentityManifestEntry{return record(value)&&fields(value,['settlementId','fingerprint'])&&stableIdentifier(value.settlementId)&&fingerprint(value.fingerprint);}
function validPackageManifest(value:unknown):value is SettlementPackageManifestEntry{return record(value)&&fields(value,['packageId','fingerprint'])&&versionedIdentifier(value.packageId)&&fingerprint(value.fingerprint);}
function validName(value:unknown):value is SettlementNameV1{return record(value)&&fields(value,['nameId','text','languageTag','role','sourceIds'])&&stableIdentifier(value.nameId)&&text(value.text,500)&&languageTag(value.languageTag)&&(value.role==='display'||value.role==='alternate')&&stringArray(value.sourceIds,false)&&value.sourceIds.every(stableIdentifier);}
function validSettlement(value:unknown):value is SettlementV1{return record(value)&&fields(value,['settlementId','kindId','names','sourceIds','decisionIds'])&&stableIdentifier(value.settlementId)&&stableIdentifier(value.kindId)&&dense(value.names)&&value.names.length>0&&value.names.every(validName)&&stringArray(value.sourceIds,false)&&value.sourceIds.every(stableIdentifier)&&stringArray(value.decisionIds)&&value.decisionIds.every(stableIdentifier);}
function validRelation(value:unknown):value is SettlementAdministrativeRelationV1{return record(value)&&fields(value,['settlementId','partitionId','placeId','relation','basis','sourceIds','decisionIds'])&&stableIdentifier(value.settlementId)&&versionedIdentifier(value.partitionId)&&stableIdentifier(value.placeId)&&(value.relation==='contained-by'||value.relation==='intersects')&&(value.basis==='official-source'||value.basis==='derived-spatial'||value.basis==='reviewed-mapping')&&stringArray(value.sourceIds,false)&&value.sourceIds.every(stableIdentifier)&&stringArray(value.decisionIds)&&value.decisionIds.every(stableIdentifier);}
function validDecision(value:unknown):value is SettlementMappingDecisionV1{return record(value)&&fields(value,['id','classification','description','sourceIds'])&&stableIdentifier(value.id)&&typeof value.classification==='string'&&['derived-transformation','reviewed-mapping','manual-continuity','authored-presentation'].includes(value.classification)&&text(value.description)&&stringArray(value.sourceIds,false)&&value.sourceIds.every(stableIdentifier);}
function validGap(value:unknown):value is SettlementGapV1{return record(value)&&fields(value,['id','description','blocking','sourceIds'])&&stableIdentifier(value.id)&&text(value.description)&&typeof value.blocking==='boolean'&&stringArray(value.sourceIds)&&value.sourceIds.every(stableIdentifier);}

const packageFields=['version','packageId','fingerprint','countryId','effectiveDate','sources','settlements','administrativeRelations','decisions','gaps','limitations'] as const;
const relationKey=(value:SettlementAdministrativeRelationV1)=>`${value.settlementId}\u0000${value.partitionId}\u0000${value.placeId}`;
function structurallyValidPackage(value:unknown):value is SettlementPackageV1{
 try{
  if(!record(value)||!fields(value,packageFields)||!isJsonValue(value)||value.version!==1||!versionedIdentifier(value.packageId)||!fingerprint(value.fingerprint)||!contextIdentifier(value.countryId)||!exactDate(value.effectiveDate)||!dense(value.sources)||value.sources.length===0||!value.sources.every(validSource)||!dense(value.settlements)||!value.settlements.every(validSettlement)||!dense(value.administrativeRelations)||!value.administrativeRelations.every(validRelation)||!dense(value.decisions)||!value.decisions.every(validDecision)||!dense(value.gaps)||!value.gaps.every(validGap)||!stringArray(value.limitations))return false;
  const sources=value.sources as unknown as readonly GeographySourceDescriptorV1[],settlements=value.settlements as unknown as readonly SettlementV1[],relations=value.administrativeRelations as unknown as readonly SettlementAdministrativeRelationV1[],decisions=value.decisions as unknown as readonly SettlementMappingDecisionV1[],gaps=value.gaps as unknown as readonly SettlementGapV1[];
  if(!unique(sources.map(item=>item.id))||!sorted(sources.map(item=>item.id))||!unique(settlements.map(item=>item.settlementId))||!sorted(settlements.map(item=>item.settlementId))||!unique(decisions.map(item=>item.id))||!sorted(decisions.map(item=>item.id))||!unique(gaps.map(item=>item.id))||!sorted(gaps.map(item=>item.id)))return false;
  const sourceIds=new Set(sources.map(item=>item.id)),decisionById=new Map(decisions.map(item=>[item.id,item])),settlementIds=new Set(settlements.map(item=>item.settlementId));
  for(const settlement of settlements){if(!unique(settlement.names.map(item=>item.nameId))||!sorted(settlement.names.map(item=>item.nameId))||settlement.names.filter(item=>item.role==='display').length!==1||settlement.sourceIds.some(id=>!sourceIds.has(id))||settlement.decisionIds.some(id=>!decisionById.has(id)))return false;for(const name of settlement.names)if(name.sourceIds.some(id=>!sourceIds.has(id)))return false;}
  if(!unique(relations.map(relationKey))||!sorted(relations.map(relationKey)))return false;
  for(const relation of relations){if(!settlementIds.has(relation.settlementId)||relation.sourceIds.some(id=>!sourceIds.has(id))||relation.decisionIds.some(id=>!decisionById.has(id)))return false;const classifications=relation.decisionIds.map(id=>decisionById.get(id)!.classification);if(relation.basis==='derived-spatial'&&!classifications.includes('derived-transformation')||relation.basis==='reviewed-mapping'&&!classifications.includes('reviewed-mapping'))return false;}
  for(const decision of decisions)if(decision.sourceIds.some(id=>!sourceIds.has(id)))return false;
  for(const gap of gaps)if(gap.sourceIds.some(id=>!sourceIds.has(id)))return false;
  return true;
 }catch{return false;}
}

function canonicalSource(source:GeographySourceDescriptorV1):GeographySourceDescriptorV1{return {version:1,id:source.id,producer:source.producer,datasetId:source.datasetId,releaseId:source.releaseId,title:source.title,jurisdiction:source.jurisdiction,referenceDate:{...source.referenceDate},classification:source.classification,methodology:source.methodology,licence:source.licence,...(source.bundledArtifact===undefined?{}:{bundledArtifact:{...source.bundledArtifact}}),...(source.externalLocator===undefined?{}:{externalLocator:source.externalLocator})};}
function canonicalName(value:SettlementNameV1):SettlementNameV1{return {...value,languageTag:value.languageTag?.toLowerCase()??null,sourceIds:[...value.sourceIds].sort(codePointCompare)};}
function canonicalSettlement(value:SettlementV1):SettlementV1{return {...value,names:value.names.map(canonicalName).sort((a,b)=>codePointCompare(a.nameId,b.nameId)),sourceIds:[...value.sourceIds].sort(codePointCompare),decisionIds:[...value.decisionIds].sort(codePointCompare)};}
function canonicalRelation(value:SettlementAdministrativeRelationV1):SettlementAdministrativeRelationV1{return {...value,sourceIds:[...value.sourceIds].sort(codePointCompare),decisionIds:[...value.decisionIds].sort(codePointCompare)};}
function canonicalDecision(value:SettlementMappingDecisionV1):SettlementMappingDecisionV1{return {...value,sourceIds:[...value.sourceIds].sort(codePointCompare)};}
function canonicalGap(value:SettlementGapV1):SettlementGapV1{return {...value,sourceIds:[...value.sourceIds].sort(codePointCompare)};}
function canonicalPackage(value:SettlementPackageV1):SettlementPackageV1{return {version:1,packageId:value.packageId,fingerprint:value.fingerprint,countryId:value.countryId,effectiveDate:{...value.effectiveDate},sources:value.sources.map(canonicalSource).sort((a,b)=>codePointCompare(a.id,b.id)),settlements:value.settlements.map(canonicalSettlement).sort((a,b)=>codePointCompare(a.settlementId,b.settlementId)),administrativeRelations:value.administrativeRelations.map(canonicalRelation).sort((a,b)=>codePointCompare(relationKey(a),relationKey(b))),decisions:value.decisions.map(canonicalDecision).sort((a,b)=>codePointCompare(a.id,b.id)),gaps:value.gaps.map(canonicalGap).sort((a,b)=>codePointCompare(a.id,b.id)),limitations:[...value.limitations].sort(codePointCompare)};}
const canonicalStringify=(value:unknown):string=>JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>codePointCompare(a,b))):item);
/** FNV-1a detects accidental semantic mutation; it is not a cryptographic authenticity primitive. */
function fnv1a64(value:string):string{let hash=0xcbf29ce484222325n;for(const byte of new TextEncoder().encode(value)){hash^=BigInt(byte);hash=BigInt.asUintN(64,hash*0x100000001b3n);}return hash.toString(16).padStart(16,'0');}
function semanticProjection(value:SettlementPackageV1):unknown{const canonical=canonicalPackage(value);return {...canonical,packageId:undefined,fingerprint:undefined};}

export function fingerprintSettlementIdentity(value:SettlementIdentityV1):string{if(!validIdentity(value))throw Error('Cannot fingerprint an invalid Settlement identity.');return `fnv1a64-v1:${fnv1a64(canonicalStringify({version:1,settlementId:value.settlementId,countryId:value.countryId}))}`;}
export function fingerprintSettlementPackage(value:SettlementPackageV1):string{const canonical=canonicalPackage(value);if(!structurallyValidPackage(canonical))throw Error('Cannot fingerprint an invalid Settlement package.');return `fnv1a64-v1:${fnv1a64(canonicalStringify(semanticProjection(canonical)))}`;}
export function validateSettlementPackage(value:unknown):value is SettlementPackageV1{try{if(!structurallyValidPackage(value))return false;const pkg=value as SettlementPackageV1;return canonicalStringify(pkg)===canonicalStringify(canonicalPackage(pkg))&&fingerprintSettlementPackage(pkg)===pkg.fingerprint;}catch{return false;}}
export function withSettlementPackageFingerprint(value:Omit<SettlementPackageV1,'fingerprint'>):SettlementPackageV1{try{if(!record(value)||!fields(value,packageFields.filter(key=>key!=='fingerprint')))throw Error();const candidate=canonicalPackage({...structuredClone(value),fingerprint:'fnv1a64-v1:0000000000000000'} as SettlementPackageV1),result=canonicalPackage({...candidate,fingerprint:fingerprintSettlementPackage(candidate)});if(!validateSettlementPackage(result))throw Error();return immutable(result);}catch{throw Error('Invalid Settlement package.');}}

export function validateSettlementRegistry(value:unknown,geography:GeographyRuntime):value is SettlementRegistryV1{
 try{
  if(!record(value)||!fields(value,['version','identities','identityManifest','packages','packageManifest'])||value.version!==1||!dense(value.identities)||!dense(value.identityManifest)||!dense(value.packages)||!dense(value.packageManifest)||!value.identities.every(validIdentity)||!value.identityManifest.every(validIdentityManifest)||!value.packages.every(validateSettlementPackage)||!value.packageManifest.every(validPackageManifest))return false;
  const identities=value.identities as readonly SettlementIdentityV1[],identityManifest=value.identityManifest as readonly SettlementIdentityManifestEntry[],packages=value.packages as readonly SettlementPackageV1[],packageManifest=value.packageManifest as readonly SettlementPackageManifestEntry[];
  if(!unique(identities.map(item=>item.settlementId))||!sorted(identities.map(item=>item.settlementId))||identityManifest.length!==identities.length||!unique(identityManifest.map(item=>item.settlementId))||!sorted(identityManifest.map(item=>item.settlementId))||!unique(packages.map(item=>item.packageId))||!sorted(packages.map(item=>item.packageId))||packageManifest.length!==packages.length||!unique(packageManifest.map(item=>item.packageId))||!sorted(packageManifest.map(item=>item.packageId)))return false;
  const identityById=new Map(identities.map(item=>[item.settlementId,item])),identityFingerprintById=new Map(identityManifest.map(item=>[item.settlementId,item.fingerprint])),packageFingerprintById=new Map(packageManifest.map(item=>[item.packageId,item.fingerprint])),occurrences=new Map<string,Array<{pkg:SettlementPackageV1;settlement:SettlementV1}>>();
  for(const identity of identities)if(identityFingerprintById.get(identity.settlementId)!==fingerprintSettlementIdentity(identity))return false;
  for(const pkg of packages){if(packageFingerprintById.get(pkg.packageId)!==pkg.fingerprint)return false;for(const settlement of pkg.settlements){const identity=identityById.get(settlement.settlementId);if(identity?.countryId!==pkg.countryId)return false;const list=occurrences.get(settlement.settlementId)??[];list.push({pkg,settlement});occurrences.set(settlement.settlementId,list);}for(const relation of pkg.administrativeRelations){const identity=identityById.get(relation.settlementId),resolved=geography.resolvePlace(relation.partitionId,relation.placeId);if(!identity||!resolved||identity.countryId!==pkg.countryId||resolved.identity.countryId!==pkg.countryId)return false;}}
  for(const entries of occurrences.values()){entries.sort((left,right)=>{const a=left.pkg.effectiveDate,b=right.pkg.effectiveDate;return a.year-b.year||a.month-b.month||a.day-b.day||codePointCompare(left.pkg.packageId,right.pkg.packageId);});for(let index=1;index<entries.length;index++){const current=entries[index],decisions=new Map(current.pkg.decisions.map(item=>[item.id,item]));if(!current.settlement.decisionIds.some(id=>decisions.get(id)?.classification==='manual-continuity'))return false;}}
  return true;
 }catch{return false;}
}

export function createSettlementRegistry(identities:readonly SettlementIdentityV1[],packages:readonly SettlementPackageV1[],packageManifest:readonly SettlementPackageManifestEntry[],identityManifest:readonly SettlementIdentityManifestEntry[],geography:GeographyRuntime):SettlementRegistryV1{
 try{const candidate={version:1 as const,identities:[...structuredClone(identities)].sort((a,b)=>codePointCompare(a.settlementId,b.settlementId)),identityManifest:[...structuredClone(identityManifest)].sort((a,b)=>codePointCompare(a.settlementId,b.settlementId)),packages:[...structuredClone(packages)].sort((a,b)=>codePointCompare(a.packageId,b.packageId)),packageManifest:[...structuredClone(packageManifest)].sort((a,b)=>codePointCompare(a.packageId,b.packageId))};if(!validateSettlementRegistry(candidate,geography))throw Error();return immutable(candidate);}catch{throw Error('Invalid Settlement registry.');}
}
