import {describe,expect,it} from 'vitest';
import type {SimulationDate} from '../../core/model';
import {createGeographyRegistry,fingerprintGeographyPartition,fingerprintPlaceIdentity,withGeographyPartitionFingerprint} from '../package';
import {createGeographyRuntime} from '../runtime';
import type {GeographyPartitionNodeV1,GeographyPartitionPackageV1,PlaceIdentityV1} from '../types';
import {createSettlementRegistry,fingerprintSettlementIdentity,fingerprintSettlementPackage,validateSettlementPackage,validateSettlementRegistry,withSettlementPackageFingerprint} from './package';
import {createSettlementRuntime} from './runtime';
import type {SettlementAdministrativeRelationV1,SettlementIdentityV1,SettlementMappingDecisionV1,SettlementNameV1,SettlementPackageV1,SettlementV1} from './types';

const date={year:2024,month:6,day:30} as const;
const sourceA={version:1 as const,id:'geography.source.synthetic-settlements-a-v1',producer:'Synthetic producer',datasetId:'synthetic-settlements-a',releaseId:'v1',title:'Synthetic Settlement evidence A',jurisdiction:'aa',referenceDate:date,classification:'authored-gameplay-abstraction' as const,methodology:'Synthetic structural evidence only.',licence:'Synthetic test fixture.'};
const sourceB={...sourceA,id:'geography.source.synthetic-settlements-b-v1',datasetId:'synthetic-settlements-b',title:'Synthetic Settlement evidence B'};
const geographySource={...sourceA,id:'geography.source.synthetic-admin-v1',datasetId:'synthetic-admin',title:'Synthetic administrative evidence'};
const node=(placeId:string,parentPlaceId:string|null):GeographyPartitionNodeV1=>({placeId,displayName:placeId,kindId:'geo.synthetic-admin',parentPlaceId,populationAllocationCell:parentPlaceId!==null,sourceIds:[geographySource.id]});
const aaNodes=[node('place.synthetic.aa.alpha','place.synthetic.aa.root'),node('place.synthetic.aa.beta','place.synthetic.aa.root'),node('place.synthetic.aa.root',null),node('place.synthetic.aa.rural','place.synthetic.aa.root')];
const bbNodes=[node('place.synthetic.bb.cell','place.synthetic.bb.root'),node('place.synthetic.bb.root',null)];
const geographyPackage=(partitionId:string,countryId:string,nodes:readonly GeographyPartitionNodeV1[]):GeographyPartitionPackageV1=>withGeographyPartitionFingerprint({version:1,partitionId,countryId,effectiveDate:date,sources:[geographySource],nodes,limitations:['Synthetic administrative content only.']});
const geography=()=>{const packages=[geographyPackage('geography.synthetic-aa-v1','aa',aaNodes),geographyPackage('geography.synthetic-bb-v1','bb',bbNodes)],places:PlaceIdentityV1[]=[...aaNodes.map(item=>({placeId:item.placeId,countryId:'aa'})),...bbNodes.map(item=>({placeId:item.placeId,countryId:'bb'}))];return createGeographyRuntime(createGeographyRegistry(places,packages,packages.map(item=>({partitionId:item.partitionId,fingerprint:item.fingerprint})),places.map(item=>({placeId:item.placeId,fingerprint:fingerprintPlaceIdentity(item)}))));};

const mappingDecision:SettlementMappingDecisionV1={id:'settlement-decision.synthetic.mapping-v1',classification:'reviewed-mapping',description:'Synthetic reviewed cross-boundary mapping.',sourceIds:[sourceA.id]};
const continuityDecision:SettlementMappingDecisionV1={id:'settlement-decision.synthetic.continuity-v1',classification:'manual-continuity',description:'Synthetic continuity review retains the durable identity.',sourceIds:[sourceA.id,sourceB.id]};
const displayName=(id:string,text:string,sourceIds:readonly string[]=[sourceA.id]):SettlementNameV1=>({nameId:`settlement-name.synthetic.${id}.display`,text,languageTag:'en',role:'display',sourceIds});
const alternateName=(id:string,text:string):SettlementNameV1=>({nameId:`settlement-name.synthetic.${id}.alternate`,text,languageTag:'cy',role:'alternate',sourceIds:[sourceB.id]});
const settlement=(id:string,names:readonly SettlementNameV1[],decisionIds:readonly string[]=[]):SettlementV1=>({settlementId:`settlement.synthetic.aa.${id}`,kindId:'settlement-kind.synthetic.named-place',names,sourceIds:[sourceA.id],decisionIds});
const relation=(id:string,placeId:string,relationKind:'contained-by'|'intersects'='contained-by',basis:'official-source'|'reviewed-mapping'='official-source'):SettlementAdministrativeRelationV1=>({settlementId:`settlement.synthetic.aa.${id}`,partitionId:'geography.synthetic-aa-v1',placeId,relation:relationKind,basis,sourceIds:[sourceA.id],decisionIds:basis==='reviewed-mapping'?[mappingDecision.id]:[]});

function rawPackage(packageId='settlements.synthetic-aa-2024-v1',effectiveDate:Readonly<SimulationDate>=date,overrides:Partial<Omit<SettlementPackageV1,'fingerprint'>>={}):Omit<SettlementPackageV1,'fingerprint'>{
 const settlements=[settlement('cross',[displayName('cross','Crossing')]),settlement('testville',[alternateName('testville','Tref Brawf'),displayName('testville','Testville')]),settlement('twin',[displayName('twin','Twin Town')])];
 const administrativeRelations=[relation('cross','place.synthetic.aa.alpha','intersects','reviewed-mapping'),relation('cross','place.synthetic.aa.beta','intersects','reviewed-mapping'),relation('testville','place.synthetic.aa.alpha'),relation('twin','place.synthetic.aa.alpha')];
 return {version:1,packageId,countryId:'aa',effectiveDate,sources:[sourceA,sourceB],settlements,administrativeRelations,decisions:[mappingDecision],gaps:[{id:'settlement-gap.synthetic.rural-v1',description:'Synthetic rural territory has no asserted Settlement.',blocking:false,sourceIds:[sourceA.id]}],limitations:['Synthetic content only.'],...overrides};
}
const packageV1=()=>withSettlementPackageFingerprint(rawPackage());
const packageV2=()=>withSettlementPackageFingerprint(rawPackage('settlements.synthetic-aa-2025-v1',{year:2025,month:6,day:30},{settlements:[settlement('cross',[displayName('cross','Crossing')],[continuityDecision.id]),settlement('testville',[alternateName('testville','Tref Brawf'),displayName('testville','New Testville')],[continuityDecision.id]),settlement('twin',[displayName('twin','Twin Town')],[continuityDecision.id])],decisions:[continuityDecision,mappingDecision]}));
const identities=():SettlementIdentityV1[]=>['cross','testville','twin'].map(id=>({settlementId:`settlement.synthetic.aa.${id}`,countryId:'aa'}));
const identityManifest=(items:readonly SettlementIdentityV1[])=>items.map(item=>({settlementId:item.settlementId,fingerprint:fingerprintSettlementIdentity(item)}));
const registry=()=>{const packages=[packageV1(),packageV2()],ids=identities();return createSettlementRegistry(ids,packages,packages.map(item=>({packageId:item.packageId,fingerprint:item.fingerprint})),identityManifest(ids),geography());};

describe('Settlement Geography Foundation v1',()=>{
 it('constructs immutable canonical packages and normalizes semantically unordered input',()=>{const canonical=packageV1(),raw=rawPackage();const reversed=withSettlementPackageFingerprint({...raw,sources:[...raw.sources].reverse(),settlements:[...raw.settlements].reverse().map(item=>({...item,names:[...item.names].reverse(),sourceIds:[...item.sourceIds].reverse(),decisionIds:[...item.decisionIds].reverse()})),administrativeRelations:[...raw.administrativeRelations].reverse(),decisions:[...raw.decisions].reverse(),gaps:[...raw.gaps].reverse(),limitations:[...raw.limitations].reverse()}),changed=withSettlementPackageFingerprint({...raw,limitations:['Changed material limitation.']});expect(reversed).toEqual(canonical);expect(fingerprintSettlementPackage(canonical)).toBe(canonical.fingerprint);expect(changed.fingerprint).not.toBe(canonical.fingerprint);expect(Object.isFrozen(canonical)).toBe(true);expect(Object.isFrozen(canonical.settlements[0].names)).toBe(true);});
 it('separates durable identity from evidence-vintage names and kinds',()=>{const runtime=createSettlementRuntime(registry(),geography()),older=runtime.getSettlement('settlements.synthetic-aa-2024-v1','settlement.synthetic.aa.testville')!,newer=runtime.getSettlement('settlements.synthetic-aa-2025-v1','settlement.synthetic.aa.testville')!;expect(older.names.find(item=>item.role==='display')?.text).toBe('Testville');expect(newer.names.find(item=>item.role==='display')?.text).toBe('New Testville');expect(runtime.registry.identities.find(item=>item.settlementId===older.settlementId)).toBe(runtime.registry.identities.find(item=>item.settlementId===newer.settlementId));});
 it('requires reviewed manual continuity for every durable identity reused by a later package',()=>{const first=packageV1(),unreviewed=withSettlementPackageFingerprint(rawPackage('settlements.synthetic-aa-2025-v1',{year:2025,month:6,day:30})),ids=identities();expect(()=>createSettlementRegistry(ids,[first,unreviewed],[{packageId:first.packageId,fingerprint:first.fingerprint},{packageId:unreviewed.packageId,fingerprint:unreviewed.fingerprint}],identityManifest(ids),geography())).toThrow('Invalid Settlement registry');expect(createSettlementRuntime(registry(),geography()).getSettlement('settlements.synthetic-aa-2025-v1','settlement.synthetic.aa.testville')).toBeDefined();});
 it('binds identity and package semantics through immutable manifests',()=>{const pkg=packageV1(),ids=identities();expect(()=>createSettlementRegistry(ids,[pkg],[{packageId:pkg.packageId,fingerprint:'fnv1a64-v1:0000000000000000'}],identityManifest(ids),geography())).toThrow();const changed=withSettlementPackageFingerprint(rawPackage(pkg.packageId,date,{limitations:['Changed semantics.']}));expect(()=>createSettlementRegistry(ids,[changed],[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}],identityManifest(ids),geography())).toThrow();const wrong=ids.map(item=>item.settlementId.endsWith('.testville')?{...item,countryId:'bb'}:item);expect(()=>createSettlementRegistry(wrong,[pkg],[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}],identityManifest(wrong),geography())).toThrow();});
 it('rejects missing durable identities and corrupted identity-manifest contracts',()=>{const pkg=packageV1(),ids=identities(),manifest=identityManifest(ids),packageManifest=[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}];expect(()=>createSettlementRegistry(ids.slice(1),[pkg],packageManifest,identityManifest(ids.slice(1)),geography())).toThrow('Invalid Settlement registry');expect(()=>createSettlementRegistry(ids,[pkg],packageManifest,manifest.map(item=>item.settlementId.endsWith('.testville')?{...item,fingerprint:'fnv1a64-v1:0000000000000000'}:item),geography())).toThrow('Invalid Settlement registry');});
 it('supports one contained Settlement and multiple Settlements in one administrative Place',()=>{const runtime=createSettlementRuntime(registry(),geography()),items=runtime.getSettlementsForAdministrativeArea('settlements.synthetic-aa-2024-v1','geography.synthetic-aa-v1','place.synthetic.aa.alpha');expect(items.map(item=>item.settlementId)).toEqual(['settlement.synthetic.aa.cross','settlement.synthetic.aa.testville','settlement.synthetic.aa.twin']);expect(runtime.getSettlementAdministrativeRelations('settlements.synthetic-aa-2024-v1','settlement.synthetic.aa.testville')).toContainEqual(expect.objectContaining({relation:'contained-by',placeId:'place.synthetic.aa.alpha'}));});
 it('supports a cross-boundary Settlement without a Settlement hierarchy',()=>{const runtime=createSettlementRuntime(registry(),geography()),relations=runtime.getSettlementAdministrativeRelations('settlements.synthetic-aa-2024-v1','settlement.synthetic.aa.cross');expect(relations.map(item=>[item.relation,item.placeId])).toEqual([['intersects','place.synthetic.aa.alpha'],['intersects','place.synthetic.aa.beta']]);expect(runtime.getSettlement('settlements.synthetic-aa-2024-v1','settlement.synthetic.aa.cross')).not.toHaveProperty('parentSettlementId');});
 it('keeps exact-area queries exact and permits rural territory without a Settlement',()=>{const runtime=createSettlementRuntime(registry(),geography());expect(runtime.getSettlementsForAdministrativeArea('settlements.synthetic-aa-2024-v1','geography.synthetic-aa-v1','place.synthetic.aa.root')).toEqual([]);expect(runtime.getSettlementsForAdministrativeArea('settlements.synthetic-aa-2024-v1','geography.synthetic-aa-v1','place.synthetic.aa.rural')).toEqual([]);expect(runtime.package('settlements.synthetic-aa-2024-v1')?.gaps[0].blocking).toBe(false);});
 it('preserves alternate-language names without transliteration',()=>{const found=createSettlementRuntime(registry(),geography()).getSettlement('settlements.synthetic-aa-2024-v1','settlement.synthetic.aa.testville')!;expect(found.names).toContainEqual(expect.objectContaining({text:'Tref Brawf',languageTag:'cy',role:'alternate'}));expect(found.names).toContainEqual(expect.objectContaining({text:'Testville',languageTag:'en',role:'display'}));});
 it('requires exactly one display name and valid canonical language tags',()=>{const invalidCases=[[alternateName('testville','Tref Brawf')],[displayName('testville','One'),{...displayName('testville2','Two'),nameId:'settlement-name.synthetic.testville.second'}],[{...displayName('testville','Testville'),languageTag:'not_a_tag'}]];for(const names of invalidCases)expect(()=>withSettlementPackageFingerprint(rawPackage('settlements.synthetic-invalid-v1',date,{settlements:[settlement('testville',names as SettlementNameV1[])]}))).toThrow('Invalid Settlement package');});
 it('rejects unknown, duplicate, and contradictory administrative relations',()=>{const raw=rawPackage(),duplicate=[raw.administrativeRelations[0],{...raw.administrativeRelations[0],relation:'contained-by' as const}];expect(()=>withSettlementPackageFingerprint({...raw,administrativeRelations:duplicate})).toThrow();const unknown=withSettlementPackageFingerprint({...raw,administrativeRelations:[{...raw.administrativeRelations[0],placeId:'place.synthetic.aa.unknown'}]});const pkg=packageV1(),ids=identities();expect(()=>createSettlementRegistry(ids,[unknown],[{packageId:unknown.packageId,fingerprint:unknown.fingerprint}],identityManifest(ids),geography())).toThrow();expect(validateSettlementPackage(pkg)).toBe(true);});
 it('rejects cross-country administrative relations without inferring country',()=>{const raw=rawPackage(),foreign=withSettlementPackageFingerprint({...raw,administrativeRelations:[{...raw.administrativeRelations[0],partitionId:'geography.synthetic-bb-v1',placeId:'place.synthetic.bb.cell'}]}),ids=identities();expect(()=>createSettlementRegistry(ids,[foreign],[{packageId:foreign.packageId,fingerprint:foreign.fingerprint}],identityManifest(ids),geography())).toThrow('Invalid Settlement registry');});
 it('requires all source and decision references to resolve with matching lineage kinds',()=>{const raw=rawPackage();expect(()=>withSettlementPackageFingerprint({...raw,settlements:[{...raw.settlements[0],sourceIds:['geography.source.missing-v1']}]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,administrativeRelations:[{...raw.administrativeRelations[0],decisionIds:['settlement-decision.missing-v1']}]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,administrativeRelations:[{...raw.administrativeRelations[0],basis:'derived-spatial',decisionIds:[mappingDecision.id]}]})).toThrow();});
 it('does not retain caller aliases in packages, registries, or runtime results',()=>{const raw=rawPackage(),pkg=withSettlementPackageFingerprint(raw),ids=identities(),manifest=identityManifest(ids),packageManifest=[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}],canonical=createSettlementRegistry(ids,[pkg],packageManifest,manifest,geography()),mutable=structuredClone(canonical),runtime=createSettlementRuntime(mutable,geography());(raw.settlements as SettlementV1[])[0]=(settlement('changed',[displayName('changed','Changed')]) as SettlementV1);(mutable.packages[0].settlements[0].names[0] as {text:string}).text='Caller mutation';(mutable.identities[0] as {countryId:string}).countryId='bb';expect(runtime.registry).toEqual(canonical);expect(runtime.getSettlement(pkg.packageId,'settlement.synthetic.aa.cross')?.names[0].text).not.toBe('Caller mutation');expect(Object.isFrozen(runtime.registry.packages[0].settlements[0].names)).toBe(true);expect(()=>((runtime.registry.packages as SettlementPackageV1[])[0]=packageV2())).toThrow();});
 it('rejects sparse, accessor-backed, symbolic, hidden, unsupported-prototype, and malformed content predictably',()=>{const pkg=packageV1(),sparse=[...pkg.settlements] as SettlementV1[];delete sparse[1];expect(validateSettlementPackage({...pkg,settlements:sparse})).toBe(false);let accessed=false;const accessor={...pkg};Object.defineProperty(accessor,'countryId',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validateSettlementPackage(accessor)).toBe(false);expect(accessed).toBe(false);expect(validateSettlementPackage({...pkg,[Symbol('extra')]:true})).toBe(false);const hidden={...pkg};Object.defineProperty(hidden,'extra',{value:true});expect(validateSettlementPackage(hidden)).toBe(false);expect(validateSettlementPackage(Object.assign(Object.create({inherited:true}),pkg))).toBe(false);expect(validateSettlementPackage({...pkg,effectiveDate:{year:0,month:1,day:1}})).toBe(false);expect(validateSettlementPackage({...pkg,fingerprint:'bad'})).toBe(false);const revoked=Proxy.revocable(pkg,{});revoked.revoke();expect(validateSettlementPackage(revoked.proxy)).toBe(false);});
 it('rejects hostile registry envelopes without invoking accessors',()=>{const canonical=registry();let accessed=false;const accessor={...canonical};Object.defineProperty(accessor,'version',{enumerable:true,get(){accessed=true;throw Error('hostile');}});expect(validateSettlementRegistry(accessor,geography())).toBe(false);expect(accessed).toBe(false);expect(validateSettlementRegistry({...canonical,[Symbol('extra')]:true},geography())).toBe(false);const hidden={...canonical};Object.defineProperty(hidden,'extra',{value:true});expect(validateSettlementRegistry(hidden,geography())).toBe(false);expect(validateSettlementRegistry(Object.assign(Object.create({inherited:true}),canonical),geography())).toBe(false);const revoked=Proxy.revocable(canonical,{});revoked.revoke();expect(validateSettlementRegistry(revoked.proxy,geography())).toBe(false);});
 it('rejects duplicate identifiers, malformed tagged unions, and unexpected nested fields',()=>{const raw=rawPackage(),first=raw.settlements[0],firstRelation=raw.administrativeRelations[0];expect(()=>withSettlementPackageFingerprint({...raw,settlements:[first,first]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,gaps:[raw.gaps[0],raw.gaps[0]]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,administrativeRelations:[{...firstRelation,relation:'primary' as never}]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,administrativeRelations:[{...firstRelation,basis:'unknown' as never}]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,decisions:[{...mappingDecision,classification:'official' as never}]})).toThrow();expect(()=>withSettlementPackageFingerprint({...raw,settlements:[{...first,extra:true} as SettlementV1]})).toThrow();});
 it('resolves only exact package identities with no default or latest alias',()=>{const runtime=createSettlementRuntime(registry(),geography());expect(runtime.package('settlements.synthetic-aa-2024-v1')?.packageId).toBe('settlements.synthetic-aa-2024-v1');expect(runtime.package('latest')).toBeUndefined();expect(runtime.getSettlement('missing','settlement.synthetic.aa.testville')).toBeUndefined();expect(()=>runtime.listSettlements('missing','aa')).toThrow('Unknown Settlement package');});
 it('uses deterministic indexed lookup at synthetic national scale',()=>{const count=5000,settlements=Array.from({length:count},(_,index)=>{const id=String(index).padStart(5,'0');return settlement(`scale-${id}`,[displayName(`scale-${id}`,`Scale ${id}`)]);}),pkg=withSettlementPackageFingerprint(rawPackage('settlements.synthetic-aa-scale-v1',date,{settlements,administrativeRelations:[],decisions:[],gaps:[]})),ids=settlements.map(item=>({settlementId:item.settlementId,countryId:'aa'})),canonical=createSettlementRegistry(ids,[pkg],[{packageId:pkg.packageId,fingerprint:pkg.fingerprint}],identityManifest(ids),geography()),runtime=createSettlementRuntime(canonical,geography());expect(runtime.listSettlements(pkg.packageId,'aa')).toHaveLength(count);for(const index of [0,17,499,2048,4999])expect(runtime.getSettlement(pkg.packageId,settlements[index].settlementId)).toBeDefined();expect(Reflect.ownKeys(runtime.registry.packages[0]).some(key=>typeof key==='string'&&/map|cache|index/i.test(key))).toBe(false);},15000);
 it('keeps generic Settlement production modules country-neutral and one-way dependent on Geography',()=>{const settlementModules=import.meta.glob<string>(['./*.ts','!./*.test.ts'],{eager:true,query:'?raw',import:'default'}),otherOwners=import.meta.glob<string>(['../*.ts','../../core/**/*.ts','../../human/**/*.ts','../../politics/**/*.ts','../../save.ts','../../../data/uk/**/*.ts','../../../persistence/**/*.ts'],{eager:true,query:'?raw',import:'default'});for(const [path,source] of Object.entries(settlementModules)){expect(source,path).not.toMatch(/from\s+['"][^'"]*(?:human|population|person|politics|persistence|save|countryStart|newGame|data\/uk|ui|react)/i);expect(source,path).not.toMatch(/Math\.random|Date\.now|randomUUID/);expect(source,path).not.toMatch(/\b(?:England|Wales|Scotland|Northern Ireland|ONS|NISRA|NRS)\b/);}for(const [path,source] of Object.entries(otherOwners))expect(source,path).not.toMatch(/geography\/settlements/);});
});
