import {describe,expect,it} from 'vitest';
import {chance,choose,createRandomness,deriveFloat,float,integer,shuffle,source,validRandomness,weightedChoice} from './rng';

describe('deterministic named randomness',()=>{
 it('isolates named mutable streams and preserves a supplied root seed',()=>{const a=createRandomness(42),b=createRandomness(42),politics=source(a,'politics.elections');float(a,'relationships.test');expect(politics.float()).toBe(source(b,'politics.elections').float());expect(a.rootSeed).toBe(42);});
 it('keeps property-like stream names isolated without touching object prototypes',()=>{const state=createRandomness(43),before=Object.prototype.hasOwnProperty.call(Object.prototype,'state');float(state,'__proto__');float(state,'constructor');expect(Object.prototype.hasOwnProperty.call(Object.prototype,'state')).toBe(before);expect(Object.keys(state.streams)).toEqual(['__proto__','constructor']);});
 it('offers deterministic ranges, chances and collection choices',()=>{const a=createRandomness(8),b=createRandomness(8),one=source(a,'test'),two=source(b,'test');expect(integer(a,'range',3,3)).toBe(3);expect(chance(a,'chance',1)).toBe(true);expect(chance(a,'chance',0)).toBe(false);expect(choose(one,['a','b','c'])).toBe(choose(two,['a','b','c']));expect(()=>integer(a,'range',4,3)).toThrow();expect(()=>chance(a,'chance',1.1)).toThrow();});
 it('keeps keyed derivation pure and independent of stream cursors',()=>{const state=createRandomness(17),before=structuredClone(state),first=deriveFloat(17,'uk|election|mereford-1');float(state,'politics.elections');expect(deriveFloat(17,'uk|election|mereford-1')).toBe(first);expect(before).not.toEqual(state);expect(deriveFloat(18,'uk|election|mereford-1')).not.toBe(first);});
 it('selects weighted ordered collections deterministically and rejects unusable inputs',()=>{const items=[{id:'a',weight:1},{id:'b',weight:3}],a=source(createRandomness(19),'weights'),b=source(createRandomness(19),'weights');expect(weightedChoice(a,items,x=>x.weight)).toEqual(weightedChoice(b,items,x=>x.weight));expect(()=>weightedChoice(source(createRandomness(1),'bad'),[{id:'a',weight:-1}],x=>x.weight)).toThrow();expect(()=>weightedChoice(source(createRandomness(1),'zero'),[{id:'a',weight:0}],x=>x.weight)).toThrow();});
 it('never selects a zero-weight entry at the zero boundary',()=>{expect(weightedChoice({float:()=>0},[{id:'zero',weight:0},{id:'positive',weight:1}],x=>x.weight).id).toBe('positive');});
 it('shuffles immutably with only its supplied source',()=>{const items=['a','b','c','d'],original=[...items],a=shuffle(source(createRandomness(5),'shuffle'),items),b=shuffle(source(createRandomness(5),'shuffle'),items);expect(items).toEqual(original);expect(a).toEqual(b);expect(a).toHaveLength(items.length);});
 it('accepts the maximum safe cursor but fails before advancing it into an invalid integer',()=>{const state=createRandomness(7);state.streams.edge={algorithm:'lcg32-v1',state:1,cursor:Number.MAX_SAFE_INTEGER};expect(validRandomness(state)).toBe(true);const before=structuredClone(state);expect(()=>float(state,'edge')).toThrow('exhausted');expect(state).toEqual(before);});
});
